var test = require('blue-tape');
var getCoords = require('city-to-coords');
var json2csv = require('json2csv');
var fs = require('fs')

//import getCoords from 'city-to-coords';
//cities = ["Cape Town", "Lusake", "London", "Nairobi", "Paris", "Dublin"]

// getCoords('NYC')
//   .then((coords) => {
//     console.log(coords);
//   });



cities =
    [
    "Kaliningrad oblast",
    "Campania",
    "Molise",
    "Jihlava",
    "Besançon",
    "Cahul",
    "Chelyabinsk oblast",
    "Lódz Voivodeship",
    "Krasnodar region",
    "Latgale Region",
    "Ararat Province",
    "Harju County",
    "Krasnodar region",
    "Chelyabinsk oblast",
    "Liguria",
    "York",
    "Tyrol",
    "Bratislava Region",
    "Varna Province",
    "Salzburg",
    "Kemerovo oblast",
    "Swansea",
    "Samtskhe-Javakheti",
    "Châteauroux",
    "Belgrade",
    "Blagoevgrad Province",
    "Vorarlberg",
    "Košice Region",
    "Mura",
    "Bratislava Region",
    "Brest",
    "Chernihiv region",
    "City of  Zagreb",
    "Carinthia",
    "Central Slovenia",
    "Košice Region",
    "Auxerre",
    "Basel",
    "Aosta Valley",
    "Aosta Valley",
    "Šiauliai County",
    "Drava",
    "Biarritz",
    "Kharkiv region",
    "Calabria",
    "More in...",
    "Lazio",
    "Chemnitz",
    "Sofia Province",
    "Centru",
    "Cologne",
    "Brno",
    "Dundee",
    "Chernivtsi region",
    "Neubrandenburg",
    "Dnipropetrovsk region",
    "Lombardy",
    "Gävle",
    "Kaliningrad oblast",
    "Kirov oblast",
    "Calabria",
    "Krasnodar region",
    "Stara Zagora Province",
    "Ivano-Frankivsk region",
    "Bryansk oblast",
    "Marche",
    "Charleville-Mézières",
    "Karlovac",
    "Kosovo and Metohija",
    "Sofia",
    "Düsseldorf",
    "Emmen",
    "Truro",
    "Belfast",
    "Campania",
    "Stockton-on-Tees",
    "Marche",
    "Vorarlberg",
    "Sofia",
    "Hradec Králové",
    "Copenhagen",
    "Kaposvár",
    "Fgura",
    "Carcassonne",
    "Panevezys County",
    "Bryansk oblast",
    "Vitsyebsk",
    "Khabarovsk region",
    "Košice Region",
    "Jyväskylä",
    "Basilicata",
    "Eastern Region",
    "Stara Zagora Province",
    "More in...",
    "Swindon",
    "Fier County",
    "Helsinki",
    "Altai Region",
    "Baku",
    "Kaluga oblast",
    "Graubünden",
    "More in...",
    "Charleville-Mézières",
    "Piedmont",
    "Ivano-Frankivsk region",
    "Southeast Slovenia",
    "Harju County",
    "Tyrol",
    "Besançon",
    "Eindhoven",
    "More in...",
    "Ulm",
    "Shetland Islands",
    "Brod-Posavina",
    "Piedmont",
    "Lelystad",
    "Elbasan County",
    "Maastricht",
    "Vienna",
    "Kosovo and Metohija",
    "Gomel",
    "Győr",
    "Burgas Province",
    "Düsseldorf",
    "Ivano-Frankivsk region",
    "Košice Region",
    "Middelburg",
    "Kaliningrad oblast",
    "Calais",
    "Oxford",
    "Doboj",
    "Järvamaa",
    "Kristiansand",
    "Alicante",
    "Šumadija and Western Serbia",
    "Caen",
    "Carinthia",
    "Angers",
    "Dnipropetrovsk region",
    "Chartres",
    "Centru",
    "Lódz Voivodeship",
    "More in...",
    "Brussels",
    "Cherkasy region",
    "Hiiumaa",
    "Kurzeme Region",
    "City of  Zagreb",
    "Joensuu",
    "Karachay–Cherkess Republic",
    "Karlovac",
    "Banská Bystrica Region",
    "Kostroma oblast",
    "Chernihiv region",
    "Kirov oblast",
    "Kurgan oblast",
    "More in...",
    "Baztan",
    "Munich",
    "Andorra la Vella",
    "Dublin",
    "Edinburgh",
    "Klaipeda County",
    "Den Helder",
    "Banská Bystrica Region",
    "Bilbao",
    "Latgale Region",
    "Nord-Est",
    "Shetland Islands",
    "Kirov oblast",
    "Campania",
    "Barcelona",
    "Würzburg",
    "Colchester",
    "Šiauliai County",
    "Targovishte Province",
    "Marijampole County",
    "Blagoevgrad Province",
    "Kardzhali Province",
    "Chelyabinsk oblast",
    "Dobrich Province",
    "Brest",
    "Lower Sava",
    "'s-Hertogenbosch",
    "Békéscsaba",
    "York",
    "Burgenland",
    "Karlovy Vary",
    "Piedmont",
    "Greater Poland Voivodeship",
    "Joensuu",
    "Lelystad",
    "Ankara",
    "Krasonyarsk region",
    "Lisboa",
    "Antalya",
    "Chartres",
    "Enschede",
    "Brest",
    "Kosovo and Metohija",
    "Belgorod oblast",
    "Cherbourg",
    "Zemgale Region",
    "Gävle",
    "Carinthia",
    "Caen",
    "Diyarbakir",
    "Burgas Province",
    "Aurich",
    "Varna Province",
    "Utena County",
    "Jura",
    "Kouvola",
    "Besançon",
    "Central Sava",
    "Khabarovsk region",
    "Dnipropetrovsk region",
    "Agen",
    "Ayr",
    "Amur oblast",
    "Kurzeme Region",
    "Autonomous Republic of Crimea",
    "Gävle",
    "Athina",
    "Borlänge",
    "Eastern Region",
    "Oxford",
    "Caen",
    "Minsk",
    "Auxerre",
    "Angoulême",
    "Auxerre",
    "More in...",
    "Göteborg",
    "Varna Province",
    "Wrexham",
    "Bourges",
    "Chelyabinsk oblast",
    "Auxerre",
    "Lovech Province",
    "Breda",
    "Kaposvár",
    "Budapest",
    "Antalya",
    "Upper Austria",
    "Fier County",
    "Győr",
    "Andorra la Vella",
    "Greek Islands",
    "Ulm",
    "Dnipropetrovsk region",
    "Bilbao",
    "Northeastern Region",
    "Chelyabinsk oblast",
    "Brussels",
    "More in...",
    "Brno",
    "Abruzzo",
    "Würzburg",
    "Campania",
    "Namur",
    "Doboj",
    "Salzburg",
    "Joensuu",
    "Vorarlberg",
    "Savinja",
    "Berlin",
    "Taurage County",
    "Košice Region",
    "Upper Carniola",
    "Lódz Voivodeship",
    "Amur oblast",
    "Komi Republic",
    "Mura",
    "Ida-Virumaa",
    "Chelyabinsk oblast",
    "Ivano-Frankivsk region",
    "Den Helder",
    "Savinja",
    "Gomel",
    "Greek Islands",
    "Brest",
    "Dublin",
    "Cherbourg",
    "Campania",
    "Burgenland",
    "Gomel",
    "Minsk",
    "Avignon",
    "Adana",
    "Koprivnica-Križevci",
    "Brighton",
    "Lelystad",
    "Liège",
    "Irkutsk oblast",
    "Coastal–Karst",
    "More in...",
    "Lower Silesian Voivodeship",
    "Southend-on-Sea",
    "Calabria",
    "Khabarovsk region",
    "Kouvola",
    "Savinja",
    "Den Helder",
    "Veliko Tarnovo Province",
    "City of  Zagreb",
    "Košice Region",
    "Oxford",
    "Munich",
    "Jihlava",
    "Tournai",
    "Belgrade",
    "Astrakhan oblast",
    "Chartres",
    "Belgrade",
    "Belgorod oblast",
    "Vienna",
    "Varna Province",
    "Chernihiv region",
    "Savinja",
    "Sofia",
    "Khanty-Mansi Autonomous Area",
    "Styria",
    "Alicante",
    "Istria",
    "Fier County",
    "More in...",
    "Peterborough",
    "Irkutsk oblast",
    "Lower Silesian Voivodeship",
    "Lombardy",
    "Aragatsotn Province",
    "Kherson region",
    "Chernihiv region",
    "Aberystwyth",
    "Liguria",
    "Middelburg",
    "Jura",
    "Salzburg",
    "Bruges",
    "Arkhangelsk oblast",
    "Šiauliai County",
    "Kaluga oblast",
    "Basel",
    "Calabria",
    "Burgas Province",
    "Copenhagen",
    "Emilia–Romagna",
    "Centru",
    "More in...",
    "Doboj",
    "Borlänge",
    "Upper Austria",
    "Fier County",
    "Jura",
    "Berlin",
    "Albi",
    "Carcassonne",
    "Gomel",
    "Blackpool",
    "Blagoevgrad Province",
    "Harju County",
    "Lódz Voivodeship",
    "Irkutsk oblast",
    "Baztan",
    "Caernarfon",
    "Göteborg",
    "Bryansk oblast",
    "Göteborg",
    "Greek Islands",
    "Stara Zagora Province",
    "Agen",
    "Burgas Province",
    "Brest",
    "Bjelovar-Bilogora",
    "Bergen",
    "Hasselt",
    "Irkutsk oblast",
    "Alicante",
    "Apeldoorn",
    "Kosovo and Metohija",
    "Andorra la Vella",
    "Ghent",
    "More in...",
    "Telšiai County",
    "Marche",
    "Brest",
    "Komi Republic",
    "Göteborg",
    "Cherkasy region",
    "Istria",
    "Győr",
    "Savinja",
    "Antalya",
    "City of  Zagreb",
    "Barcelona",
    "Kristiansand",
    "Belgrade",
    "Debrecen",
    "Southeast Slovenia",
    "Adana",
    "Upper Carniola",
    "Marche",
    "Biarritz",
    "Kirov oblast",
    "Auxerre",
    "Eastern Region",
    "Dorchester",
    "Tournai",
    "Avignon",
    "Dobrich Province",
    "Järvamaa",
    "Savinja",
    "Budapest",
    "Friuli-Venezia Giulia",
    "Calais",
    "Ayr",
    "Karlovy Vary",
    "Belfast",
    "Irkutsk oblast",
    "Besançon",
    "Kyustendil Province",
    "Mtskheta-Mtianeti",
    "Kecskemét",
    "Lelystad",
    "Portsmouth-Southampton",
    "Bucharest-Ilfov",
    "Samtskhe-Javakheti",
    "Upper Austria",
    "Molise",
    "Altai Region",
    "Budapest",
    "Ghent",
    "Hasselt",
    "Nord-Est",
    "Bijeljina",
    "Angers",
    "Liège",
    "Ankara",
    "Abruzzo",
    "Hasselt",
    "Brno",
    "Bijeljina",
    "Maastricht",
    "Namur",
    "Middelburg",
    "Bern",
    "Chalon-sur-Saône",
    "Banja Luka",
    "Drava",
    "Charleville-Mézières",
    "Dubrovnik–Neretva",
    "Eindhoven",
    "Elbasan County",
    "Hämeenlinna",
    "Kosovo and Metohija",
    "Calabria",
    "Kotayk' Province",
    "Friuli-Venezia Giulia",
    "Nottingham",
    "Khanty-Mansi Autonomous Area",
    "Kecskemét",
    "'s-Hertogenbosch",
    "Lombardy",
    "Derry",
    "Lubusz Voivodeship",
    "Ghent",
    "Bremerhaven",
    "Vienna",
    "Tyrol",
    "Istria",
    "Kostroma oblast",
    "Krasnodar region",
    "Pelagonia",
    "Harju County",
    "Bristol",
    "Lubusz Voivodeship",
    "Aberdeen",
    "Bijeljina",
    "Chartres",
    "Bursa",
    "Ida-Virumaa",
    "Baztan",
    "Peterborough",
    "Angoulême",
    "Vidin Province",
    "Swansea",
    "Kuyavian-Pomeranian Voivodeship",
    "Tbilisi",
    "Belgrade",
    "Calabria",
    "Lazio",
    "Autonomous Republic of Crimea",
    "Diyarbakir",
    "More in...",
    "Dubrovnik–Neretva",
    "Barcelona",
    "Kaunas County",
    "Balti",
    "Apeldoorn",
    "Wrexham",
    "Groningen",
    "Jihlava",
    "Portsmouth-Southampton",
    "Kosovo and Metohija",
    "Chisinau",
    "Jihlava",
    "Krasonyarsk region",
    "Chisinau",
    "Liège",
    "Portsmouth-Southampton",
    "Diyarbakir",
    "Bourges",
    "Angers",
    "Aix-en-Provence",
    "Marijampole County",
    "Wrexham",
    "Bielefeld",
    "Edinburgh",
    "Dublin",
    "Campania",
    "Mons",
    "Šiauliai County",
    "Irkutsk oblast",
    "City of  Zagreb",
    "More in...",
    "Kaliningrad oblast",
    "Southeast Slovenia",
    "Amiens",
    "Győr",
    "Gomel",
    "Southeast Slovenia",
    "Astrakhan oblast",
    "Kyustendil Province",
    "Bielefeld",
    "Bratislava Region",
    "Amiens",
    "Ivano-Frankivsk region",
    "Altai Region",
    "Southeast Slovenia",
    "Chernivtsi region",
    "Würzburg",
    "Dumfries",
    "Vorarlberg",
    "Abkhazia",
    "Aix-en-Provence",
    "Drava",
    "Bern",
    "Greater Poland Voivodeship",
    "Charleville-Mézières",
    "Lower Austria",
    "Chechen Republic",
    "Apulia",
    "Liguria",
    "Greater Poland Voivodeship",
    "Ayr",
    "Budapest",
    "Liguria",
    "Aosta Valley",
    "Stuttgart",
    "Dublin",
    "Namur",
    "Drava",
    "Doboj",
    "Kuyavian-Pomeranian Voivodeship",
    "Haskovo Province",
    "Arkhangelsk oblast",
    "Istria",
    "Chemnitz",
    "Campania",
    "Barcelona",
    "Bordeaux",
    "Sheffield",
    "Avignon",
    "Hämeenlinna",
    "Adana",
    "Central Slovenia",
    "Chalon-sur-Saône",
    "Carinthia",
    "Emilia–Romagna",
    "Angoulême",
    "Kristiansand",
    "Lower Silesian Voivodeship",
    "Den Haag",
    "Derry",
    "Angoulême",
    "Derby",
    "Dnipropetrovsk region",
    "Avignon",
    "Central Slovenia",
    "Kurgan oblast",
    "Namur",
    "Telšiai County",
    "Helsinki",
    "Abruzzo",
    "Vilnius county",
    "Istria",
    "Basel",
    "Avignon",
    "Lubusz Voivodeship",
    "Brest",
    "Elbasan County",
    "Hämeenlinna",
    "Liège",
    "Ankara",
    "Kaliningrad oblast",
    "Vienna",
    "Belgrade",
    "Würzburg",
    "Blackpool",
    "Aberystwyth",
    "Châteauroux",
    "Telšiai County",
    "Kaluga oblast",
    "Donetsk region",
    "Briceni",
    "Arkhangelsk oblast",
    "Aurich",
    "Basel",
    "Friuli-Venezia Giulia",
    "Kirov oblast",
    "Marche",
    "Carinthia",
    "Rostock",
    "Kabardino-Balkar Republic",
    "Irkutsk oblast",
    "Aix-en-Provence",
    "Arkhangelsk oblast",
    "Styria",
    "Carinthia",
    "Gävle",
    "Varna Province",
    "Bristol",
    "Ivanovo oblast",
    "Nord-Est",
    "Baku",
    "Bilbao",
    "Budapest",
    "Kherson region",
    "Ashkirk",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Almere",
    "More in...",
    "Sofia",
    "Braunschweig-Wolfsburg",
    "Charleroi",
    "Graubünden",
    "Amiens",
    "Chernihiv region",
    "Belgrade",
    "Sheffield",
    "More in...",
    "Lubusz Voivodeship",
    "Karlovac",
    "Järvamaa",
    "Caen",
    "Dortmund",
    "York",
    "Chernihiv region",
    "Avignon",
    "Antwerp",
    "Southeast Slovenia",
    "Calabria",
    "Biarritz",
    "Kyustendil Province",
    "Lubusz Voivodeship",
    "Cherbourg",
    "Gorizia",
    "Ivanovo oblast",
    "Kaluga oblast",
    "Southend-on-Sea",
    "Krasonyarsk region",
    "Kyustendil Province",
    "Bergen",
    "Greater Poland Voivodeship",
    "Den Helder",
    "Birmingham",
    "Telšiai County",
    "Bruges",
    "Liguria",
    "Bourges",
    "Cologne",
    "Besançon",
    "Enschede",
    "Lelystad",
    "Dobrich Province",
    "Klaipeda County",
    "Ceské Budejovice",
    "Agen",
    "More in...",
    "Jyväskylä",
    "York",
    "Győr",
    "Bergen",
    "Komi Republic",
    "Gorizia",
    "Chelyabinsk oblast",
    "Debrecen",
    "Taunton",
    "Aurich",
    "Irkutsk oblast",
    "Gävle",
    "Ida-Virumaa",
    "Gomel",
    "Vienna",
    "Kardzhali Province",
    "Lubusz Voivodeship",
    "Caen",
    "Nottingham",
    "Hasselt",
    "Vitsyebsk",
    "Kherson region",
    "Ceské Budejovice",
    "Chernivtsi region",
    "Edinburgh",
    "Helsinki",
    "Truro",
    "Ulm",
    "Amsterdam",
    "Basilicata",
    "Kostroma oblast",
    "More in...",
    "Schwerin",
    "Cherbourg",
    "Molise",
    "Liguria",
    "Bursa",
    "Drava",
    "Bergen",
    "Norwich",
    "Lubusz Voivodeship",
    "Chuvash Republic",
    "Doboj",
    "Chechen Republic",
    "Charleville-Mézières",
    "Kristiansand",
    "Derry",
    "Lombardy",
    "Athina",
    "Charleville-Mézières",
    "Barcelona",
    "Hiiumaa",
    "Ankara",
    "Southeast Slovenia",
    "Lombardy",
    "Besançon",
    "Adana",
    "More in...",
    "Brno",
    "Jyväskylä",
    "Budapest",
    "Krasonyarsk region",
    "Khanty-Mansi Autonomous Area",
    "Bordeaux",
    "Upper Carniola",
    "Baztan",
    "Dumfries",
    "Göteborg",
    "Autonomous Republic of Crimea",
    "Brest",
    "Győr",
    "Middelburg",
    "Krasonyarsk region",
    "Lower Silesian Voivodeship",
    "Eindhoven",
    "More in...",
    "Banská Bystrica Region",
    "Telšiai County",
    "Styria",
    "Baku",
    "Komi Republic",
    "Hämeenlinna",
    "Järvamaa",
    "Chelyabinsk oblast",
    "Hiiumaa",
    "Nord-Est",
    "Eger",
    "Adana",
    "Vitsyebsk",
    "Bijeljina",
    "Kirov oblast",
    "Würzburg",
    "Cologne",
    "Košice Region",
    "Marijampole County",
    "Panevezys County",
    "Taunton",
    "Den Helder",
    "Ida-Virumaa",
    "Newcastle",
    "Chisinau",
    "Lower Sava",
    "Geneve-Annemasse",
    "Truro",
    "Hämeenlinna",
    "Harju County",
    "Elbasan County",
    "More in...",
    "Middelburg",
    "Bergen",
    "Klaipeda County",
    "Jyväskylä",
    "Amur oblast",
    "More in...",
    "Piedmont",
    "Aix-en-Provence",
    "Geneve-Annemasse",
    "Fier County",
    "Khanty-Mansi Autonomous Area",
    "Jihlava",
    "Khabarovsk region",
    "Borlänge",
    "Brest",
    "Šiauliai County",
    "Sofia",
    "Gomel",
    "Veliko Tarnovo Province",
    "Astrakhan oblast",
    "Budapest",
    "Budapest",
    "Kirov oblast",
    "Kabardino-Balkar Republic",
    "Lower Silesian Voivodeship",
    "Arkhangelsk oblast",
    "Bratislava Region",
    "Hämeenlinna",
    "Vidin Province",
    "Middelburg",
    "Würzburg",
    "Baztan",
    "Chisinau",
    "Agen",
    "Chuvash Republic",
    "Šumadija and Western Serbia",
    "Haskovo Province",
    "Alicante",
    "Passau",
    "Bordeaux",
    "Doboj",
    "Gorizia",
    "Vilnius county",
    "Jura",
    "Calais",
    "Kharkiv region",
    "Piedmont",
    "Khanty-Mansi Autonomous Area",
    "Passau",
    "Düsseldorf",
    "Győr",
    "Ceské Budejovice",
    "Kaposvár",
    "Karlovy Vary",
    "Caernarfon",
    "Veliko Tarnovo Province",
    "Debrecen",
    "Abruzzo",
    "Lazio",
    "Göteborg",
    "Albi",
    "Aberdeen",
    "Sheffield",
    "Rostock",
    "Andorra la Vella",
    "Marche",
    "Banská Bystrica Region",
    "Aosta Valley",
    "Lombardy",
    "Friuli-Venezia Giulia",
    "Marche",
    "Khanty-Mansi Autonomous Area",
    "Khabarovsk region",
    "Mura",
    "Avignon",
    "Apeldoorn",
    "Burgenland",
    "Groningen",
    "Minsk",
    "Greater Poland Voivodeship",
    "Baku",
    "Chalon-sur-Saône",
    "Győr",
    "Helsinki",
    "Koprivnica-Križevci",
    "Borlänge",
    "Lazio",
    "Ankara",
    "Marijampole County",
    "Kuyavian-Pomeranian Voivodeship",
    "Kaposvár",
    "Angers",
    "Sofia",
    "Tyrol",
    "Abkhazia",
    "Vidin Province",
    "Basilicata",
    "Cambridge",
    "Châteauroux",
    "Kostroma oblast",
    "Charleville-Mézières",
    "Apeldoorn",
    "Aran",
    "Klaipeda County",
    "Dundee",
    "Abruzzo",
    "Salzburg",
    "Upper Carniola",
    "Shida Kartli",
    "Hiiumaa",
    "Apeldoorn",
    "Andorra la Vella",
    "Schwerin",
    "Liège",
    "Mura",
    "Jura",
    "Hiiumaa",
    "Calais",
    "Dobrich Province",
    "Kamchatka Peninsula",
    "Ankara",
    "Göteborg",
    "Andorra la Vella",
    "Fier County",
    "Imereti",
    "Central Sava",
    "Ivanovo oblast",
    "Portsmouth-Southampton",
    "Kaluga oblast",
    "Cologne",
    "Ghent",
    "Sofia",
    "Barnstaple",
    "More in...",
    "Cardiff",
    "More in...",
    "Baztan",
    "Berlin",
    "Chernihiv region",
    "Lower Sava",
    "Krasnodar region",
    "Athina",
    "Caen",
    "Apeldoorn",
    "Liguria",
    "Sheffield",
    "Järvamaa",
    "Aosta Valley",
    "Jura",
    "Brod-Posavina",
    "Piedmont",
    "Lublin Voivodeship",
    "Haskovo Province",
    "Krasnodar region",
    "Kecskemét",
    "Antalya",
    "Aalborg",
    "Kemerovo oblast",
    "Antigua",
    "Arkhangelsk oblast",
    "Lublin Voivodeship",
    "Angoulême",
    "Vienna",
    "Istria",
    "Stockton-on-Tees",
    "Arkhangelsk oblast",
    "Athina",
    "Šiauliai County",
    "Lublin Voivodeship",
    "Birmingham",
    "Göteborg",
    "Chernihiv region",
    "Tournai",
    "Bursa",
    "Ghent",
    "Bilbao",
    "Autonomous Republic of Crimea",
    "Lódz Voivodeship",
    "Absheron",
    "Baztan",
    "Chelyabinsk oblast",
    "Upper Austria",
    "Tbilisi",
    "Bryansk oblast",
    "Göteborg",
    "Eindhoven",
    "Gomel",
    "Eger",
    "Diyarbakir",
    "Brest",
    "Uelzen",
    "Komi Republic",
    "More in...",
    "Copenhagen",
    "Ghent",
    "Chalon-sur-Saône",
    "Southend-on-Sea",
    "Kirov oblast",
    "Emilia–Romagna",
    "Colchester",
    "Vienna",
    "Chelyabinsk oblast",
    "Ivanovo oblast",
    "Den Helder",
    "Vitsyebsk",
    "Breda",
    "Pelagonia",
    "Ceské Budejovice",
    "Chernihiv region",
    "Kaunas County",
    "Lublin Voivodeship",
    "Banja Luka",
    "Banja Luka",
    "Chelyabinsk oblast",
    "Brest",
    "Hasselt",
    "Ceské Budejovice",
    "Peterborough",
    "Baku",
    "Agen",
    "Khanty-Mansi Autonomous Area",
    "Caernarfon",
    "Den Haag",
    "Krasonyarsk region",
    "Lódz Voivodeship",
    "Molise",
    "Basilicata",
    "Liège",
    "Karlovy Vary",
    "Utena County",
    "Šumadija and Western Serbia",
    "Lublin Voivodeship",
    "Khabarovsk region",
    "Athina",
    "Vilnius county",
    "Kouvola",
    "Lublin Voivodeship",
    "Krasnodar region",
    "Baku",
    "Portsmouth-Southampton",
    "Schwerin",
    "Nuremberg",
    "Molise",
    "Zemgale Region",
    "Emilia–Romagna",
    "Chuvash Republic",
    "Kurzeme Region",
    "Northeastern Region",
    "Hämeenlinna",
    "Upper Austria",
    "More in...",
    "Kaluga oblast",
    "Ivanovo oblast",
    "Kaluga oblast",
    "Hradec Králové",
    "Lower Silesian Voivodeship",
    "Borlänge",
    "Peterborough",
    "Dubrovnik–Neretva",
    "Astrakhan oblast",
    "Emmen",
    "Apeldoorn",
    "Tyrol",
    "Kaluga oblast",
    "Utena County",
    "More in...",
    "City of  Zagreb",
    "Friuli-Venezia Giulia",
    "Bjelovar-Bilogora",
    "Belgrade",
    "Istria",
    "Klaipeda County",
    "Oxford",
    "Caen",
    "Koprivnica-Križevci",
    "Kaunas County",
    "Friuli-Venezia Giulia",
    "Joensuu",
    "Oxford",
    "Belfast",
    "Antalya",
    "Middelburg",
    "Altai Region",
    "Lubusz Voivodeship",
    "Samtskhe-Javakheti",
    "Antwerp",
    "Brest",
    "Ivano-Frankivsk region",
    "Carcassonne",
    "Komi Republic",
    "Kemerovo oblast",
    "Shida Kartli",
    "Würzburg",
    "Karlovy Vary",
    "Kherson region",
    "Minsk",
    "More in...",
    "Chelyabinsk oblast",
    "Besançon",
    "Lisboa",
    "Krasonyarsk region",
    "Vidin Province",
    "Dobrich Province",
    "Debrecen",
    "Kostroma oblast",
    "Lublin Voivodeship",
    "Bursa",
    "Burgenland",
    "Chernihiv region",
    "Montana Province",
    "Dubrovnik–Neretva",
    "Alicante",
    "Taurage County",
    "Styria",
    "Cherbourg",
    "Nottingham",
    "Veliko Tarnovo Province",
    "Besançon",
    "Brest",
    "Telšiai County",
    "Lisboa",
    "Arkhangelsk oblast",
    "Minsk",
    "Kaposvár",
    "Doboj",
    "Châteauroux",
    "Biarritz",
    "Belgorod oblast",
    "Charleville-Mézières",
    "Groningen",
    "Friuli-Venezia Giulia",
    "Zemgale Region",
    "Caernarfon",
    "Bourges",
    "Kurgan oblast",
    "Marijampole County",
    "Banská Bystrica Region",
    "Nord-Est",
    "Chernihiv region",
    "Auxerre",
    "Angers",
    "Styria",
    "Helsinki",
    "Chernihiv region",
    "Banská Bystrica Region",
    "Bratislava Region",
    "Carinthia",
    "Ivano-Frankivsk region",
    "Hiiumaa",
    "Kaluga oblast",
    "Abruzzo",
    "Hradec Králové",
    "Den Haag",
    "Angers",
    "Tyrol",
    "Maastricht",
    "Lelystad",
    "Krasonyarsk region",
    "Kvemo Kartli",
    "Komi Republic",
    "Lesser Poland Voivodeship",
    "Békéscsaba",
    "Göteborg",
    "Lelystad",
    "Bruges",
    "Lisboa",
    "Astrakhan oblast",
    "Ida-Virumaa",
    "Chisinau",
    "Eger",
    "Vitsyebsk",
    "Cherkasy region",
    "Middelburg",
    "Ivanovo oblast",
    "Khabarovsk region",
    "Antwerp",
    "Vorarlberg",
    "Central Slovenia",
    "Békéscsaba",
    "Arkhangelsk oblast",
    "Autonomous Republic of Crimea",
    "Panevezys County",
    "Annecy",
    "Aosta Valley",
    "Vienna",
    "Brest",
    "Bayreuth",
    "Kaposvár",
    "Panevezys County",
    "Banja Luka",
    "Dubrovnik–Neretva",
    "Karlovac",
    "Southeast Slovenia",
    "Châteauroux",
    "Leeuwarden",
    "Cherkasy region",
    "Colchester",
    "Molise",
    "Belgrade",
    "Würzburg",
    "Lubusz Voivodeship",
    "Eger",
    "Aalborg",
    "Dnipropetrovsk region",
    "Biarritz",
    "Lublin Voivodeship",
    "Astrakhan oblast",
    "Tbilisi",
    "Helsinki",
    "Klaipeda County",
    "Kyustendil Province",
    "Montana Province",
    "Angoulême",
    "Calais",
    "Bratislava Region",
    "Caernarfon",
    "Antigua",
    "Athina",
    "Autonomous Republic of Crimea",
    "Ceské Budejovice",
    "Derry",
    "Koprivnica-Križevci",
    "Aragatsotn Province",
    "More in...",
    "Molise",
    "Würzburg",
    "Harju County",
    "Kaunas County",
    "Dresden",
    "Marijampole County",
    "Alicante",
    "Dubrovnik–Neretva",
    "Emilia–Romagna",
    "Antalya",
    "Jura",
    "Swansea",
    "Bremerhaven",
    "Kostroma oblast",
    "Brno",
    "Gomel",
    "Ankara",
    "Lovech Province",
    "Liège",
    "Kharkiv region",
    "Calais",
    "Blackpool",
    "More in...",
    "Geneve-Annemasse",
    "Lódz Voivodeship",
    "Amiens",
    "Krasnodar region",
    "Cherkasy region",
    "Birmingham",
    "Altai Region",
    "Nord-Est",
    "Utena County",
    "Kurgan oblast",
    "Chelyabinsk oblast",
    "More in...",
    "Agen",
    "Klaipeda County",
    "Calais",
    "Angers",
    "Kuyavian-Pomeranian Voivodeship",
    "Blagoevgrad Province",
    "Piedmont",
    "Bryansk oblast",
    "Ankara",
    "Dublin",
    "Middelburg",
    "Chalon-sur-Saône",
    "Middelburg",
    "Dubrovnik–Neretva",
    "Liguria",
    "Taunton",
    "Avignon",
    "Lombardy",
    "Kaunas County",
    "Central Sava",
    "Taurage County",
    "Hradec Králové",
    "Jihlava",
    "Cherkasy region",
    "Norwich",
    "Emilia–Romagna",
    "Molise",
    "Edinburgh",
    "Nord-Est",
    "Pelagonia",
    "Hiiumaa",
    "Sofia",
    "Kirov oblast",
    "Panevezys County",
    "Calais",
    "Lesser Poland Voivodeship",
    "Hiiumaa",
    "Marche",
    "Karlovy Vary",
    "Fier County",
    "Chernihiv region",
    "Debrecen",
    "Copenhagen",
    "Békéscsaba",
    "Agen",
    "Lower Silesian Voivodeship",
    "More in...",
    "Budapest",
    "Liguria",
    "Calabria",
    "Newcastle",
    "Barnstaple",
    "Amiens",
    "Krasnodar region",
    "Salzburg",
    "Bucharest-Ilfov",
    "Calais",
    "Ashkirk",
    "Hradec Králové",
    "Portsmouth-Southampton",
    "Sheffield",
    "Vilnius county",
    "Ivano-Frankivsk region",
    "Vilnius county",
    "Kristiansand",
    "Kaunas County",
    "Helsinki",
    "Aix-en-Provence",
    "Vilnius county",
    "Carinthia",
    "Lazio",
    "Blackpool",
    "Burgenland",
    "Adana",
    "Ida-Virumaa",
    "Alicante",
    "Albi",
    "Lisboa",
    "Hradec Králové",
    "Greek Islands",
    "Kamchatka Peninsula",
    "Bratislava Region",
    "Kristiansand",
    "Šiauliai County",
    "Varna Province",
    "Briceni",
    "Albi",
    "Latgale Region",
    "Győr",
    "Angers",
    "Athina",
    "Aix-en-Provence",
    "Aosta Valley",
    "Lesser Poland Voivodeship",
    "Lubusz Voivodeship",
    "Bergen",
    "Haskovo Province",
    "Albi",
    "Antalya",
    "Zemgale Region",
    "Apulia",
    "Brest",
    "City of  Zagreb",
    "Cherbourg",
    "Bergen",
    "More in...",
    "Győr",
    "Birmingham",
    "More in...",
    "Portsmouth-Southampton",
    "Aix-en-Provence",
    "Istria",
    "Centru",
    "Amiens",
    "Barcelona",
    "Utena County",
    "Central Sava",
    "Khabarovsk region",
    "Järvamaa",
    "Nord-Est",
    "Kaposvár",
    "Southend-on-Sea",
    "Dublin",
    "Aberystwyth",
    "Baku",
    "Dubrovnik–Neretva",
    "Drava",
    "Aosta Valley",
    "Lódz Voivodeship",
    "Banja Luka",
    "Aosta Valley",
    "Tbilisi",
    "Brest",
    "Newcastle",
    "Basel",
    "Belgrade",
    "Dubrovnik–Neretva",
    "More in...",
    "Klaipeda County",
    "Ulm",
    "Lelystad",
    "Coastal–Karst",
    "Tbilisi",
    "Antalya",
    "Aran",
    "Mura",
    "Krasnodar region",
    "Panevezys County",
    "Eger",
    "Vorarlberg",
    "Calabria",
    "Kurzeme Region",
    "Banja Luka",
    "Telšiai County",
    "Järvamaa",
    "Würzburg",
    "Antigua",
    "Bratislava Region",
    "Newcastle",
    "Marche",
    "Šiauliai County",
    "York",
    "Utena County",
    "Zemgale Region",
    "Peterborough",
    "Ivanovo oblast",
    "Biarritz",
    "York",
    "Alicante",
    "Den Helder",
    "Bristol",
    "Norwich",
    "Bijeljina",
    "Agen",
    "Belfast",
    "Carcassonne",
    "Centru",
    "Hradec Králové",
    "Apulia",
    "Amsterdam",
    "Abruzzo",
    "Angoulême",
    "Brno",
    "Copenhagen",
    "Budapest",
    "Joensuu",
    "Arkhangelsk oblast",
    "Athina",
    "Dnipropetrovsk region",
    "Cardiff",
    "Savinja",
    "Salzburg",
    "Sofia",
    "Hradec Králové",
    "Norwich",
    "Bourges",
    "Donetsk region",
    "Plymouth",
    "Tournai",
    "Targovishte Province",
    "Piedmont",
    "Swindon",
    "Nord-Est",
    "Vilnius county",
    "Kaliningrad oblast",
    "Cherbourg",
    "Khanty-Mansi Autonomous Area",
    "Adana",
    "Lazio",
    "Newcastle",
    "Chuvash Republic",
    "Brest",
    "Emilia–Romagna",
    "Vitsyebsk",
    "Jewish Autonomous Region",
    "Brod-Posavina",
    "Kecskemét",
    "Oxford",
    "Kecskemét",
    "Jyväskylä",
    "Chernihiv region",
    "Bryansk oblast",
    "Joensuu",
    "Apulia",
    "Bordeaux",
    "Kuyavian-Pomeranian Voivodeship",
    "Enschede",
    "Khabarovsk region",
    "Haskovo Province",
    "Ivano-Frankivsk region",
    "Kardzhali Province",
    "Baku",
    "Győr",
    "Tournai",
    "Greater Poland Voivodeship",
    "Angoulême",
    "Lódz Voivodeship",
    "Friuli-Venezia Giulia",
    "Maastricht",
    "Vilnius county",
    "Leeuwarden",
    "Karlovac",
    "Auxerre",
    "Hämeenlinna",
    "Groningen",
    "Arkhangelsk oblast",
    "Bursa",
    "Molise",
    "Kristiansand",
    "Ankara",
    "Lower Silesian Voivodeship",
    "Hämeenlinna",
    "Molise",
    "Banja Luka",
    "Dnipropetrovsk region",
    "Coastal–Karst",
    "Belgrade",
    "Brest",
    "Cherbourg",
    "Alytus County",
    "Biarritz",
    "Ararat Province",
    "Kemerovo oblast",
    "Lisboa",
    "Hiiumaa",
    "Southeast Slovenia",
    "Avignon",
    "Istria",
    "Alytus County",
    "Upper Austria",
    "Bonn",
    "Carcassonne",
    "Gävle",
    "Aurich",
    "Cherkasy region",
    "Centru",
    "Lazio",
    "Gomel",
    "Ida-Virumaa",
    "Budapest",
    "More in...",
    "Bursa",
    "Angoulême",
    "Göteborg",
    "Tournai",
    "Namur",
    "Baku",
    "Kurzeme Region",
    "Chemnitz",
    "Kristiansand",
    "Nottingham",
    "Kosovo and Metohija",
    "Banská Bystrica Region",
    "Kamchatka Peninsula",
    "Stara Zagora Province",
    "Aberystwyth",
    "Ida-Virumaa",
    "Bratislava Region",
    "Amur oblast",
    "Cherbourg",
    "Utena County",
    "Apulia",
    "Northeastern Region",
    "Bryansk oblast",
    "Vienna",
    "Altai Region",
    "Chelyabinsk oblast",
    "Fier County",
    "Calabria",
    "Kherson region",
    "Lower Silesian Voivodeship",
    "Tyrol",
    "Copenhagen",
    "Bryansk oblast",
    "Jyväskylä",
    "Blagoevgrad Province",
    "Antalya",
    "Lesser Poland Voivodeship",
    "Bergen",
    "Groningen",
    "Drava",
    "Southeast Slovenia",
    "Vilnius county",
    "Gomel",
    "Central Sava",
    "Lisboa",
    "Debrecen",
    "Ankara",
    "Chernihiv region",
    "Kaluga oblast",
    "Namur",
    "Basilicata",
    "Derry",
    "Kirov oblast",
    "Blagoevgrad Province",
    "Vitsyebsk",
    "Burgenland",
    "Khabarovsk region",
    "Ida-Virumaa",
    "Kakheti",
    "Irkutsk oblast",
    "Belgorod oblast",
    "Campania",
    "Karlovy Vary",
    "Apulia",
    "Järvamaa",
    "Friuli-Venezia Giulia",
    "Cherkasy region",
    "Banská Bystrica Region",
    "Copenhagen",
    "Cherkasy region",
    "Groningen",
    "Adana",
    "Bjelovar-Bilogora",
    "Greek Islands",
    "Inner Carniola–Karst",
    "Carinthia",
    "Auxerre",
    "Utena County",
    "Lelystad",
    "Jyväskylä",
    "Liguria",
    "Lower Silesian Voivodeship",
    "Doboj",
    "Sofia",
    "Brest",
    "Carinthia",
    "Leeuwarden",
    "Antwerp",
    "Vratsa Province",
    "Burgenland",
    "Lombardy",
    "Tournai",
    "Aosta Valley",
    "Campania",
    "Järvamaa",
    "Dundee",
    "Chisinau",
    "Minsk",
    "Barnstaple",
    "Gorizia",
    "Győr",
    "Dorchester",
    "Banja Luka",
    "Gävle",
    "Aalborg",
    "Arkhangelsk oblast",
    "Krasonyarsk region",
    "Avignon",
    "Varna Province",
    "Aberdeen",
    "Ceské Budejovice",
    "Latgale Region",
    "Barcelona",
    "Antigua",
    "Jyväskylä",
    "Albi",
    "Mura",
    "Burgas Province",
    "Belfast",
    "Bucharest-Ilfov",
    "Gomel",
    "Kouvola",
    "Brest",
    "Blagoevgrad Province",
    "Greek Islands",
    "Molise",
    "Upper Carniola",
    "Eindhoven",
    "Vorarlberg",
    "Cardiff",
    "Salzburg",
    "Greater Poland Voivodeship",
    "Bijeljina",
    "Dortmund",
    "Den Helder",
    "Piedmont",
    "Wrexham",
    "Chernivtsi region",
    "Antalya",
    "Ayr",
    "Bryansk oblast",
    "Sofia",
    "Chalon-sur-Saône",
    "Centru",
    "Rostock",
    "Kirov oblast",
    "Košice Region",
    "Andorra la Vella",
    "Athina",
    "Utena County",
    "Basel",
    "Bruges",
    "Namur",
    "Irkutsk oblast",
    "Fier County",
    "Latgale Region",
    "Greater Poland Voivodeship",
    "Gävle",
    "Portsmouth-Southampton",
    "Doboj",
    "Marijampole County",
    "Hasselt",
    "Kakheti",
    "Dublin",
    "Telšiai County",
    "Kharkiv region",
    "Würzburg",
    "Zemgale Region",
    "Den Helder",
    "Biarritz",
    "Campania",
    "Šiauliai County",
    "Maastricht",
    "Zemgale Region",
    "Békéscsaba",
    "Lubusz Voivodeship",
    "Dortmund",
    "York",
    "Upper Carniola",
    "Taurage County",
    "Altai Region",
    "Eger",
    "Cherbourg",
    "Dobrich Province",
    "Basel",
    "Marburg",
    "Kirov oblast",
    "Banská Bystrica Region",
    "Hasselt",
    "Angoulême",
    "Vorarlberg",
    "Kotayk' Province",
    "Bilbao",
    "Lubusz Voivodeship",
    "Šiauliai County",
    "Fier County",
    "Amiens",
    "Donetsk region",
    "Lower Sava",
    "Friuli-Venezia Giulia",
    "Den Helder",
    "Greek Islands",
    "Autonomous Republic of Crimea",
    "Bristol",
    "Chartres",
    "Colchester",
    "Targovishte Province",
    "Khanty-Mansi Autonomous Area",
    "Dubrovnik–Neretva",
    "Pelagonia",
    "Edinburgh",
    "Passau",
    "Jura",
    "Dublin",
    "Annecy",
    "Nord-Est",
    "Adana",
    "Marijampole County",
    "Calais",
    "Enschede",
    "Budapest",
    "Châteauroux",
    "Graubünden",
    "Stuttgart",
    "Bilbao",
    "Kristiansand",
    "Aberdeen",
    "Harju County",
    "Blackpool",
    "Dorchester",
    "Marche",
    "Colchester",
    "Doboj",
    "Dublin",
    "Lombardy",
    "Breda",
    "Drava",
    "Khanty-Mansi Autonomous Area",
    "Geneve-Annemasse",
    "Blagoevgrad Province",
    "Bursa",
    "Targovishte Province",
    "Albi",
    "Hiiumaa",
    "Charleville-Mézières",
    "Banja Luka",
    "Diyarbakir",
    "Maastricht",
    "Kaposvár",
    "Kemerovo oblast",
    "Baztan",
    "Göteborg",
    "Telšiai County",
    "Antigua",
    "Kecskemét",
    "Ida-Virumaa",
    "Bilbao",
    "Birmingham",
    "Alytus County",
    "Helsinki",
    "Gävle",
    "Jyväskylä",
    "Braunschweig-Wolfsburg",
    "Den Haag",
    "Kharkiv region",
    "Lesser Poland Voivodeship",
    "Greater Poland Voivodeship",
    "Lower Austria",
    "Aberystwyth",
    "Gävle",
    "Kouvola",
    "Norwich",
    "Enschede",
    "Lelystad",
    "Amur oblast",
    "Kemerovo oblast",
    "Harju County",
    "Nord-Est",
    "Mura",
    "Bourges",
    "Blackpool",
    "Eindhoven",
    "Dnipropetrovsk region",
    "More in...",
    "Chalon-sur-Saône",
    "Borlänge",
    "Burgenland",
    "Den Haag",
    "Arkhangelsk oblast",
    "Harju County",
    "Bratislava Region",
    "Norwich",
    "Jyväskylä",
    "Taunton",
    "Besançon",
    "Basilicata",
    "Athina",
    "Panevezys County",
    "Nord-Est",
    "Bijeljina",
    "Burgenland",
    "Győr",
    "Kamchatka Peninsula",
    "Molise",
    "Kurgan oblast",
    "Charleville-Mézières",
    "Upper Carniola",
    "Tbilisi",
    "Veliko Tarnovo Province",
    "Shida Kartli",
    "Wrexham",
    "Wrexham",
    "Drava",
    "Vilnius county",
    "Kharkiv region",
    "Birmingham",
    "Bender",
    "Plymouth",
    "Kristiansand",
    "Caen",
    "Geneve-Annemasse",
    "Angoulême",
    "Kristiansand",
    "Vilnius county",
    "Chelyabinsk oblast",
    "More in...",
    "Békéscsaba",
    "Varna Province",
    "Eger",
    "Ashkirk",
    "Järvamaa",
    "Bilbao",
    "More in...",
    "Brno",
    "Inner Carniola–Karst",
    "Emilia–Romagna",
    "Central Slovenia",
    "Almere",
    "Autonomous Republic of Crimea",
    "Nottingham",
    "Borlänge",
    "Joensuu",
    "Copenhagen",
    "Apeldoorn",
    "Chernivtsi region",
    "Albi",
    "Kamchatka Peninsula",
    "Kosovo and Metohija",
    "Lombardy",
    "Khanty-Mansi Autonomous Area",
    "Würzburg",
    "Central Slovenia",
    "Taunton",
    "Oxford",
    "Biarritz",
    "Alicante",
    "Antalya",
    "Salzburg",
    "Ghent",
    "Kherson region",
    "Bilbao",
    "City of  Zagreb",
    "Savinja",
    "Borlänge",
    "Kherson region",
    "Emilia–Romagna",
    "Andorra la Vella",
    "Autonomous Republic of Crimea",
    "Northampton",
    "Southend-on-Sea",
    "Zemgale Region",
    "Antigua",
    "Karlovy Vary",
    "Debrecen",
    "Chernihiv region",
    "Kosovo and Metohija",
    "Tournai",
    "Doboj",
    "Centru",
    "Chuvash Republic",
    "Emilia–Romagna",
    "Vidin Province",
    "Drava",
    "Kharkiv region",
    "Breda",
    "Bijeljina",
    "Bordeaux",
    "Kaunas County",
    "Bilbao",
    "Nottingham",
    "Hiiumaa",
    "Karlovac",
    "Gomel",
    "Banja Luka",
    "Astrakhan oblast",
    "Bucharest-Ilfov",
    "Ceské Budejovice",
    "Pelagonia",
    "Jura",
    "Chalon-sur-Saône",
    "Chartres",
    "Bjelovar-Bilogora",
    "Düsseldorf",
    "More in...",
    "Haskovo Province",
    "Stoke-on-Trent",
    "Hämeenlinna",
    "Kherson region",
    "Kouvola",
    "Dobrich Province",
    "Kemerovo oblast",
    "Auxerre",
    "Caen",
    "Eger",
    "Bryansk oblast",
    "Tbilisi",
    "Lelystad",
    "More in...",
    "More in...",
    "Chernivtsi region",
    "Marche",
    "Düsseldorf",
    "Dubrovnik–Neretva",
    "Chernivtsi region",
    "Arkhangelsk oblast",
    "Bryansk oblast",
    "Aix-en-Provence",
    "Irkutsk oblast",
    "More in...",
    "Brighton",
    "Fier County",
    "Annecy",
    "Koprivnica-Križevci",
    "Donetsk region",
    "Lombardy",
    "Joensuu",
    "Friuli-Venezia Giulia",
    "Sofia",
    "Järvamaa",
    "Karlovac",
    "Kemerovo oblast",
    "Adana",
    "More in...",
    "Aberystwyth",
    "Lublin Voivodeship",
    "Lombardy",
    "Alytus County",
    "Enschede",
    "Minsk",
    "Gomel",
    "Ivanovo oblast",
    "Lisboa",
    "Banská Bystrica Region",
    "Upper Austria",
    "Astrakhan oblast",
    "Kaunas County",
    "Andorra la Vella",
    "Adana",
    "Panevezys County",
    "Banská Bystrica Region",
    "Andorra la Vella",
    "Kecskemét",
    "Friuli-Venezia Giulia",
    "Šumadija and Western Serbia",
    "Irkutsk oblast",
    "Jura",
    "Elbasan County",
    "Bjelovar-Bilogora",
    "Lovech Province",
    "Taurage County",
    "Dnipropetrovsk region",
    "Khanty-Mansi Autonomous Area",
    "Ceské Budejovice",
    "Drava",
    "Southend-on-Sea",
    "Encamp",
    "Châteauroux",
    "Vidin Province",
    "Central Slovenia",
    "Portsmouth-Southampton",
    "Centru",
    "Balti",
    "Kaliningrad oblast",
    "Barcelona",
    "Cherkasy region",
    "Antwerp",
    "Antigua",
    "Alicante",
    "Mura",
    "Zemgale Region",
    "Nottingham",
    "Karlovac",
    "Dumfries",
    "Klaipeda County",
    "Tournai",
    "Astrakhan oblast",
    "Nuremberg",
    "Liguria",
    "Kristiansand",
    "Kuyavian-Pomeranian Voivodeship",
    "Dundee",
    "Kaliningrad oblast",
    "Basilicata",
    "Emilia–Romagna",
    "Middelburg",
    "Ganja-Gazakh",
    "Swindon",
    "Angoulême",
    "Kaliningrad oblast",
    "Nord-Est",
    "Lubusz Voivodeship",
    "Autonomous Republic of Crimea",
    "Chalon-sur-Saône",
    "Eger",
    "Abruzzo",
    "Bryansk oblast",
    "Lisboa",
    "Bruges",
    "Krasnodar region",
    "Bursa",
    "More in...",
    "Minsk",
    "Chernivtsi region",
    "Centru",
    "Göteborg",
    "Swindon",
    "Calabria",
    "Centru",
    "Tbilisi",
    "Calabria",
    "Järvamaa",
    "Lisboa",
    "Belgorod oblast",
    "Den Haag",
    "Styria",
    "Budapest",
    "Kouvola",
    "More in...",
    "Würzburg",
    "Kosovo and Metohija",
    "Veliko Tarnovo Province",
    "Liguria",
    "Middelburg",
    "Emmen",
    "Annecy",
    "Charleville-Mézières",
    "Belgorod oblast",
    "Kharkiv region",
    "Lisboa",
    "Brest",
    "Košice Region",
    "Upper Austria",
    "Ivano-Frankivsk region",
    "Gävle",
    "Avignon",
    "More in...",
    "Istria",
    "Banská Bystrica Region",
    "Yambol Province",
    "Molise",
    "Burgenland",
    "Lesser Poland Voivodeship",
    "Swansea",
    "Oxford",
    "Marche",
    "Coastal–Karst",
    "Göteborg",
    "Ceské Budejovice",
    "Dobrich Province",
    "Geneve-Annemasse",
    "Kemerovo oblast",
    "Koprivnica-Križevci",
    "Montana Province",
    "Bucharest-Ilfov",
    "Apeldoorn",
    "Angers",
    "Banská Bystrica Region",
    "Bjelovar-Bilogora",
    "Truro",
    "Vitsyebsk",
    "Pelagonia",
    "Charleville-Mézières",
    "Sheffield",
    "Altai Region",
    "Järvamaa",
    "Veliko Tarnovo Province",
    "Aosta Valley",
    "Emilia–Romagna",
    "Burgas Province",
    "Calabria",
    "Blackpool",
    "Minsk",
    "Békéscsaba",
    "Taunton",
    "Kaunas County",
    "Lisboa",
    "Brno",
    "Stoke-on-Trent",
    "Vilnius county",
    "Istria",
    "Marche",
    "Ashkirk",
    "Baku",
    "Hiiumaa",
    "Basilicata",
    "Dresden",
    "Ayr",
    "Panevezys County",
    "Bjelovar-Bilogora",
    "Den Helder",
    "Greater Poland Voivodeship",
    "York",
    "Wrexham",
    "Krasonyarsk region",
    "Dublin",
    "Lubusz Voivodeship",
    "Auxerre",
    "Chalon-sur-Saône",
    "Kostroma oblast",
    "Klaipeda County",
    "Košice Region",
    "Styria",
    "Vienna",
    "Kaunas County",
    "Caernarfon",
    "Brest",
    "Edinburgh",
    "Carcassonne",
    "Yambol Province",
    "Birmingham",
    "Charleroi",
    "Fier County",
    "Athina",
    "Minsk",
    "Kaunas County",
    "Amur oblast",
    "Antwerp",
    "Oxford",
    "Minsk",
    "Fgura",
    "Bijeljina",
    "Breda",
    "City of  Zagreb",
    "Biarritz",
    "Athina",
    "Kouvola",
    "Kabardino-Balkar Republic",
    "Kemerovo oblast",
    "Elbasan County",
    "Stuttgart",
    "Carcassonne",
    "Békéscsaba",
    "Montana Province",
    "Brussels",
    "Bijeljina",
    "Bruges",
    "Kurgan oblast",
    "Hämeenlinna",
    "Den Helder",
    "Hradec Králové",
    "Cherkasy region",
    "Kurzeme Region",
    "Carinthia",
    "Annecy",
    "Doboj",
    "More in...",
    "Campania",
    "Dibër County",
    "Calais",
    "Istria",
    "Blagoevgrad Province",
    "Ceské Budejovice",
    "Auxerre",
    "Berlin",
    "Minsk",
    "Carcassonne",
    "Plymouth",
    "Diyarbakir",
    "Brussels",
    "Caen",
    "More in...",
    "Tournai",
    "Bursa",
    "Fgura",
    "Greek Islands",
    "Leeuwarden",
    "Lankaran",
    "Uelzen",
    "Panevezys County",
    "Chuvash Republic",
    "Biarritz",
    "Aix-en-Provence",
    "Telšiai County",
    "Donetsk region",
    "Mura",
    "Altai Republic",
    "Biarritz",
    "Centru",
    "Helsinki",
    "York",
    "Lazio",
    "Debrecen",
    "Utena County",
    "Den Helder",
    "Kherson region",
    "Chelyabinsk oblast",
    "Marche",
    "Coastal–Karst",
    "Annecy",
    "More in...",
    "Chartres",
    "Hämeenlinna",
    "Styria",
    "Ida-Virumaa",
    "Bordeaux",
    "Eger",
    "Besançon",
    "Lesser Poland Voivodeship",
    "Brest",
    "Istria",
    "Bijeljina",
    "Lesser Poland Voivodeship",
    "Shetland Islands",
    "Lublin Voivodeship",
    "Berlin",
    "Eger",
    "York",
    "Styria",
    "Abruzzo",
    "Pelagonia",
    "Lombardy",
    "Coastal–Karst",
    "Neubrandenburg",
    "Jihlava",
    "Kemerovo oblast",
    "Biarritz",
    "Annecy",
    "Carcassonne",
    "Oxford",
    "Komi Republic",
    "Kuyavian-Pomeranian Voivodeship",
    "Balti",
    "Edinburgh",
    "Lazio",
    "Kaliningrad oblast",
    "Ashkirk",
    "Donetsk region",
    "Calais",
    "Bern",
    "Schwerin",
    "Ivanovo oblast",
    "Istria",
    "Albi",
    "Kurgan oblast",
    "Vidin Province",
    "Ceské Budejovice",
    "Graubünden",
    "City of  Zagreb",
    "Namur",
    "Dnipropetrovsk region",
    "Aix-en-Provence",
    "Basilicata",
    "Drava",
    "Kaposvár",
    "Eger",
    "Gabrovo Province",
    "Eindhoven",
    "Baztan",
    "Aix-en-Provence",
    "Altai Republic",
    "Banja Luka",
    "Karlovy Vary",
    "Neubrandenburg",
    "Zemgale Region",
    "Calabria",
    "Dnipropetrovsk region",
    "Bucharest-Ilfov",
    "Carcassonne",
    "Kirov oblast",
    "Greek Islands",
    "Lovech Province",
    "Karlovac",
    "Angers",
    "Lelystad",
    "Kabardino-Balkar Republic",
    "Aurich",
    "Donetsk region",
    "Budapest",
    "Swindon",
    "Adana",
    "Kaluga oblast",
    "Den Haag",
    "Jyväskylä",
    "Athina",
    "Kurgan oblast",
    "Savinja",
    "Krasonyarsk region",
    "Leeuwarden",
    "Bijeljina",
    "Emilia–Romagna",
    "Drava",
    "Liège",
    "Cardiff",
    "Karlovac",
    "Brussels",
    "Bayreuth",
    "Ida-Virumaa",
    "Pelagonia",
    "Kuyavian-Pomeranian Voivodeship",
    "Alytus County",
    "Carinthia",
    "Utena County",
    "Kostroma oblast",
    "Bursa",
    "Aosta Valley",
    "Greek Islands",
    "Greek Islands",
    "Apulia",
    "Bijeljina",
    "Gävle",
    "Mtskheta-Mtianeti",
    "Belfast",
    "Briceni",
    "Karlovac",
    "Marburg",
    "Upper Carniola",
    "Baku",
    "Kaunas County",
    "Brest",
    "Annecy",
    "Bucharest-Ilfov",
    "Wrexham",
    "Liège",
    "Lombardy",
    "Ghent",
    "Donetsk region",
    "Altai Region",
    "Tbilisi",
    "Hradec Králové",
    "Châteauroux",
    "Minsk",
    "Lesser Poland Voivodeship",
    "Bergen",
    "Nord-Est",
    "Cherkasy region",
    "Burgas Province",
    "Aosta Valley",
    "Marijampole County",
    "Andorra la Vella",
    "Châteauroux",
    "Banja Luka",
    "Latgale Region",
    "Central Slovenia",
    "Coastal–Karst",
    "Chernivtsi region",
    "Groningen",
    "Nottingham",
    "Imereti",
    "Ivano-Frankivsk region",
    "Lódz Voivodeship",
    "Vorarlberg",
    "Chelyabinsk oblast",
    "Enschede",
    "Bender",
    "Békéscsaba",
    "Taurage County",
    "Calabria",
    "Calais",
    "Ceské Budejovice",
    "Dundee",
    "Friuli-Venezia Giulia",
    "Cambridge",
    "Carinthia",
    "Montana Province",
    "Ida-Virumaa",
    "Centru",
    "Marburg",
    "Altai Region",
    "Vilnius county",
    "Burgenland",
    "Bursa",
    "Stuttgart",
    "Adana",
    "More in...",
    "Angoulême",
    "Düsseldorf",
    "Lesser Poland Voivodeship",
    "Basilicata",
    "Burgas Province",
    "More in...",
    "Piedmont",
    "Alicante",
    "Lower Sava",
    "Samegrelo-Zemo Svaneti",
    "Fier County",
    "Copenhagen",
    "Komi Republic",
    "Caen",
    "Aran",
    "Ashkirk",
    "Angoulême",
    "Carinthia",
    "Dortmund",
    "Kabardino-Balkar Republic",
    "More in...",
    "Kosovo and Metohija",
    "Jura",
    "Gävle",
    "Ivano-Frankivsk region",
    "Ghent",
    "Ayr",
    "Würzburg",
    "Aalborg",
    "Kuyavian-Pomeranian Voivodeship",
    "Gomel",
    "Carcassonne",
    "Košice Region",
    "Arkhangelsk oblast",
    "Kostroma oblast",
    "Bilbao",
    "Birmingham",
    "Antalya",
    "Bristol",
    "Birmingham",
    "Bourges",
    "Savinja",
    "Haskovo Province",
    "Bursa",
    "Jura",
    "Bratislava Region",
    "Bursa",
    "More in...",
    "Latgale Region",
    "Nottingham",
    "Carinthia",
    "More in...",
    "Lower Silesian Voivodeship",
    "Alytus County",
    "Cardiff",
    "Namur",
    "Hradec Králové",
    "Central Slovenia",
    "Kemerovo oblast",
    "Copenhagen",
    "Békéscsaba",
    "Diyarbakir",
    "Abruzzo",
    "Portsmouth-Southampton",
    "More in...",
    "Nord-Est",
    "Fier County",
    "Vitsyebsk",
    "Hiiumaa",
    "Amur oblast",
    "Taunton",
    "Ashkirk",
    "Bucharest-Ilfov",
    "Jura",
    "Helsinki",
    "Den Haag",
    "Latgale Region",
    "Amiens",
    "Campania",
    "Blagoevgrad Province",
    "Bergen",
    "Upper Carniola",
    "Greek Islands",
    "Autonomous Republic of Crimea",
    "Veliko Tarnovo Province",
    "Gävle",
    "Brussels",
    "Kherson region",
    "Jihlava",
    "Lesser Poland Voivodeship",
    "Derry",
    "Arkhangelsk oblast",
    "Sofia",
    "Greater Poland Voivodeship",
    "Northeastern Region",
    "Albi",
    "Liège",
    "Shetland Islands",
    "Khanty-Mansi Autonomous Area",
    "Ankara",
    "Belfast",
    "Kyustendil Province",
    "Oxford",
    "Plymouth",
    "Angoulême",
    "Krasnodar region",
    "Besançon",
    "Helsinki",
    "Tyrol",
    "Vorarlberg",
    "Ivanovo oblast",
    "Kyustendil Province",
    "Agen",
    "Campania",
    "Košice Region",
    "Auxerre",
    "Cologne",
    "Hradec Králové",
    "Friuli-Venezia Giulia",
    "Caen",
    "Taunton",
    "Kecskemét",
    "Styria",
    "Cottbus",
    "Central Slovenia",
    "Friuli-Venezia Giulia",
    "Tournai",
    "Upper Carniola",
    "Kurgan oblast",
    "Donetsk region",
    "Vitsyebsk",
    "Copenhagen",
    "Lelystad",
    "Chartres",
    "Jihlava",
    "Astrakhan oblast",
    "Greater Poland Voivodeship",
    "Durrës County",
    "Emilia–Romagna",
    "Kuyavian-Pomeranian Voivodeship",
    "Fgura",
    "Bordeaux",
    "Baku",
    "Alytus County",
    "Bender",
    "Coastal–Karst",
    "City of  Zagreb",
    "Emilia–Romagna",
    "Marijampole County",
    "Lublin Voivodeship",
    "Upper Carniola",
    "Baztan",
    "Kaliningrad oblast",
    "Baztan",
    "Charleville-Mézières",
    "Bordeaux",
    "York",
    "Northampton",
    "Aalborg",
    "Sofia",
    "Kouvola",
    "Haskovo Province",
    "Dorchester",
    "Chuvash Republic",
    "Banská Bystrica Region",
    "Namur",
    "Baztan",
    "Oxford",
    "Košice Region",
    "Kurgan oblast",
    "Komi Republic",
    "Bucharest-Ilfov",
    "Baztan",
    "Montana Province",
    "Pelagonia",
    "Kuyavian-Pomeranian Voivodeship",
    "Besançon",
    "Harju County",
    "Groningen",
    "Greater Poland Voivodeship",
    "Antalya",
    "Joensuu",
    "Marche",
    "Braunschweig-Wolfsburg",
    "Bordeaux",
    "Albi",
    "Burgas Province",
    "Upper Austria",
    "Jyväskylä",
    "Carcassonne",
    "Ankara",
    "Apulia",
    "Chuvash Republic",
    "Šiauliai County",
    "Kecskemét",
    "Kaluga oblast",
    "Vitsyebsk",
    "Kostroma oblast",
    "Piedmont",
    "Baku",
    "Karlovy Vary",
    "Piedmont",
    "Abkhazia",
    "Telšiai County",
    "Krasnodar region",
    "Jihlava",
    "Molise",
    "Borlänge",
    "Hiiumaa",
    "Upper Carniola",
    "Chechen Republic",
    "Portsmouth-Southampton",
    "Bucharest-Ilfov",
    "Kharkiv region",
    "Telšiai County",
    "Khanty-Mansi Autonomous Area",
    "Northeastern Region",
    "Fier County",
    "Banja Luka",
    "Donetsk region",
    "Aalborg",
    "Šumadija and Western Serbia",
    "More in...",
    "Stoke-on-Trent",
    "Doboj",
    "Blackpool",
    "Sheffield",
    "Chartres",
    "Caernarfon",
    "Kaliningrad oblast",
    "Liguria",
    "Middelburg",
    "Debrecen",
    "Greek Islands",
    "Lódz Voivodeship",
    "Derry",
    "Southeast Slovenia",
    "Alytus County",
    "York",
    "Chernivtsi region",
    "Dortmund",
    "Fier County",
    "Apulia",
    "Coastal–Karst",
    "Ivanovo oblast",
    "Tbilisi",
    "Basilicata",
    "Chartres",
    "Šumadija and Western Serbia",
    "Alicante",
    "Savinja",
    "Doboj",
    "Abruzzo",
    "Copenhagen",
    "Vorarlberg",
    "Khabarovsk region",
    "Taunton",
    "Jura",
    "Bielefeld",
    "Ceské Budejovice",
    "Jyväskylä",
    "Centru",
    "Irkutsk oblast",
    "Brussels",
    "Vorarlberg",
    "Bratislava Region",
    "Cherbourg",
    "Brest",
    "Békéscsaba",
    "Kirov oblast",
    "Antwerp",
    "Kostroma oblast",
    "Kirov oblast",
    "Basel",
    "Eger",
    "Jura",
    "Dobrich Province",
    "More in...",
    "Enschede",
    "Norwich",
    "Enschede",
    "Blagoevgrad Province",
    "Enschede",
    "Marburg",
    "Emilia–Romagna",
    "Upper Austria",
    "Kouvola",
    "Ankara",
    "Hämeenlinna",
    "Greater Poland Voivodeship",
    "Burgas Province",
    "Panevezys County",
    "Stoke-on-Trent",
    "Donetsk region",
    "Biarritz",
    "Krasonyarsk region",
    "Sofia Province",
    "Caernarfon",
    "Colchester",
    "Ganja-Gazakh",
    "Komi Republic",
    "Joensuu",
    "Belgorod oblast",
    "York",
    "Brest",
    "Kaposvár",
    "Tyrol",
    "Adana",
    "Eger",
    "Kaluga oblast",
    "Den Haag",
    "Kvemo Kartli",
    "Barcelona",
    "Chechen Republic",
    "Kaunas County",
    "Latgale Region",
    "Centru",
    "Ghent",
    "Ida-Virumaa",
    "Vidin Province",
    "Charleville-Mézières",
    "Mtskheta-Mtianeti",
    "Khabarovsk region",
    "City of  Zagreb",
    "Stoke-on-Trent",
    "Bijeljina",
    "Kirov oblast",
    "Bremerhaven",
    "Minsk",
    "Berlin",
    "Antalya",
    "Brno",
    "Telšiai County",
    "Utena County",
    "Lesser Poland Voivodeship",
    "Irkutsk oblast",
    "Carcassonne",
    "Koprivnica-Križevci",
    "Aragatsotn Province",
    "Chalon-sur-Saône",
    "Cardiff",
    "Upper Austria",
    "Kaluga oblast",
    "Avignon",
    "Auxerre",
    "Lazio",
    "Dibër County",
    "Liguria",
    "Krasnodar region",
    "Centru",
    "Besançon",
    "Portsmouth-Southampton",
    "Tournai",
    "Montana Province",
    "Bilbao",
    "Sofia",
    "Liguria",
    "Adana",
    "Daghlig Shirvan",
    "Kyustendil Province",
    "Berlin",
    "Irkutsk oblast",
    "Budapest",
    "Arkhangelsk oblast",
    "Brussels",
    "Wrexham",
    "Breda",
    "Latgale Region",
    "Bayonne",
    "Dublin",
    "Swansea",
    "Lazio",
    "Karlovac",
    "Lesser Poland Voivodeship",
    "Central Slovenia",
    "Kurzeme Region",
    "Lower Silesian Voivodeship",
    "Karlovy Vary",
    "Southeast Slovenia",
    "Mura",
    "Burgas Province",
    "Utena County",
    "Salzburg",
    "Apulia",
    "Ivanovo oblast",
    "Bryansk oblast",
    "Fier County",
    "Brod-Posavina",
    "Vorarlberg",
    "Varna Province",
    "Chisinau",
    "Stoke-on-Trent",
    "Győr",
    "Derry",
    "Nord-Est",
    "Alicante",
    "Jihlava",
    "Nord-Est",
    "Ivano-Frankivsk region",
    "Peterborough",
    "Encamp",
    "Abruzzo",
    "Hiiumaa",
    "Swindon",
    "Lódz Voivodeship",
    "Hradec Králové",
    "Agen",
    "Antwerp",
    "Varna Province",
    "Ivanovo oblast",
    "Varna Province",
    "Győr",
    "Den Haag",
    "Avignon",
    "Bern",
    "Lisboa",
    "Dorchester",
    "Brno",
    "Diyarbakir",
    "Groningen",
    "Dobrich Province",
    "Bratislava Region",
    "Banja Luka",
    "Latgale Region",
    "Belgorod oblast",
    "Bratislava Region",
    "Košice Region",
    "Kakheti",
    "Liège",
    "Altai Republic",
    "Karachay–Cherkess Republic",
    "Harju County",
    "Blackpool",
    "Upper Carniola",
    "York",
    "Dorchester",
    "Brest",
    "Upper Carniola",
    "Jihlava",
    "Fgura",
    "Kharkiv region",
    "Albi",
    "Bielefeld",
    "Dnipropetrovsk region",
    "Calais",
    "Tournai",
    "Helsinki",
    "Diyarbakir",
    "Basilicata",
    "Athina",
    "Vilnius county",
    "Bayonne",
    "York",
    "Kharkiv region",
    "Šumadija and Western Serbia",
    "Lódz Voivodeship",
    "Châteauroux",
    "Donetsk region",
    "Aalborg",
    "Annecy",
    "Kuyavian-Pomeranian Voivodeship",
    "Arkhangelsk oblast",
    "Bursa",
    "Sheffield",
    "Belgorod oblast",
    "Sofia Province",
    "Biarritz",
    "Kecskemét",
    "Apeldoorn",
    "Bergen",
    "Kostroma oblast",
    "Bijeljina",
    "Cahul",
    "Chisinau",
    "Karlovac",
    "Mons",
    "Karlovy Vary",
    "Blagoevgrad Province",
    "Sofia",
    "Banská Bystrica Region",
    "Stara Zagora Province",
    "Chechen Republic",
    "Tyrol",
    "Vienna",
    "Barcelona",
    "Carinthia",
    "Chisinau",
    "Lódz Voivodeship",
    "Northeastern Region",
    "Colchester",
    "Bratislava Region",
    "Bordeaux",
    "Diyarbakir",
    "Oxford",
    "Taunton",
    "Győr",
    "Fgura",
    "Newcastle",
    "Burgas Province",
    "Ulm",
    "Irkutsk oblast",
    "Den Haag",
    "Kouvola",
    "Utena County",
    "Kherson region",
    "Mura",
    "Kaluga oblast",
    "Bordeaux",
    "Banja Luka",
    "Centru",
    "Lisboa",
    "Donetsk region",
    "Lesser Poland Voivodeship",
    "Ankara",
    "Bordeaux",
    "Autonomous Republic of Crimea",
    "Kecskemét",
    "Chartres",
    "Marche",
    "Ceské Budejovice",
    "Bursa",
    "Bender",
    "Kouvola",
    "More in...",
    "Barcelona",
    "Ivanovo oblast",
    "Alytus County",
    "Gabrovo Province",
    "Plymouth",
    "Bratislava Region",
    "Amur oblast",
    "Besançon",
    "Namur",
    "Gabrovo Province",
    "Ivanovo oblast",
    "Kosovo and Metohija",
    "Kirov oblast",
    "Gorizia",
    "Avignon",
    "Kharkiv region",
    "Bjelovar-Bilogora",
    "Friuli-Venezia Giulia",
    "More in...",
    "Šiauliai County",
    "Den Haag",
    "Bijeljina",
    "City of  Zagreb",
    "Kaunas County",
    "Karachay–Cherkess Republic",
    "Hiiumaa",
    "Göteborg",
    "Chisinau",
    "Abruzzo",
    "Dnipropetrovsk region",
    "Carinthia",
    "Calabria",
    "Nuremberg",
    "Helsinki",
    "Borlänge",
    "Antwerp",
    "Kuyavian-Pomeranian Voivodeship",
    "Taurage County",
    "Hradec Králové",
    "Blagoevgrad Province",
    "Bijeljina",
    "Joensuu",
    "Upper Carniola",
    "Greek Islands",
    "Vienna",
    "Montana Province",
    "Auxerre",
    "Arkhangelsk oblast",
    "Angers",
    "Abruzzo",
    "Abruzzo",
    "Arkhangelsk oblast",
    "Ankara",
    "Jihlava",
    "Annecy",
    "Lisboa",
    "Plymouth",
    "Karlovy Vary",
    "Saarbrücken",
    "Panevezys County",
    "Debrecen",
    "Lubusz Voivodeship",
    "Belgrade",
    "Šiauliai County",
    "Gomel",
    "Yambol Province",
    "Vitsyebsk",
    "Kristiansand",
    "Swansea",
    "Kaliningrad oblast",
    "Cherbourg",
    "Belgorod oblast",
    "Central Sava",
    "Greek Islands",
    "Eindhoven",
    "More in...",
    "Aosta Valley",
    "Komi Republic",
    "Lubusz Voivodeship",
    "Alytus County",
    "Antigua",
    "Passau",
    "Ghent",
    "More in...",
    "Banja Luka",
    "Jõgeva County",
    "Charleville-Mézières",
    "Stara Zagora Province",
    "Emilia–Romagna",
    "Central Slovenia",
    "Belgrade",
    "Shetland Islands",
    "Lower Austria",
    "Ida-Virumaa",
    "Maastricht",
    "Central Sava",
    "Panevezys County",
    "Krasnodar region",
    "Dumfries",
    "Calabria",
    "Lisboa",
    "Graubünden",
    "Komi Republic",
    "Upper Carniola",
    "Calabria",
    "Bremerhaven",
    "Kouvola",
    "Lazio",
    "Angers",
    "Belgorod oblast",
    "Altai Region",
    "Lazio",
    "Kirov oblast",
    "Bryansk oblast",
    "Helsinki",
    "City of  Zagreb",
    "Brest",
    "Lower Sava",
    "Ida-Virumaa",
    "More in...",
    "Järvamaa",
    "Barcelona",
    "Albi",
    "Albi",
    "Komi Republic",
    "Kurzeme Region",
    "Leeuwarden",
    "Styria",
    "Brno",
    "Lazio",
    "Bucharest-Ilfov",
    "Leeuwarden",
    "Den Helder",
    "Châteauroux",
    "Angoulême",
    "Järvamaa",
    "Karlovy Vary",
    "Upper Austria",
    "Dobrich Province",
    "Kharkiv region",
    "Gabrovo Province",
    "Bratislava Region",
    "Auxerre",
    "Brest",
    "Kherson region",
    "Basilicata",
    "Doboj",
    "Abruzzo",
    "Tbilisi",
    "Belgorod oblast",
    "Kirov oblast",
    "Nord-Est",
    "Vidin Province",
    "Taunton",
    "Aberystwyth",
    "Stara Zagora Province",
    "Irkutsk oblast",
    "Andorra la Vella",
    "Bursa",
    "Blackpool",
    "Swindon",
    "Krasnodar region",
    "Bilbao",
    "More in...",
    "Kristiansand",
    "Järvamaa",
    "Bjelovar-Bilogora",
    "Cherbourg",
    "More in...",
    "Dnipropetrovsk region",
    "Dumfries",
    "Montana Province",
    "Lesser Poland Voivodeship",
    "Khanty-Mansi Autonomous Area",
    "Cherkasy region",
    "Barcelona",
    "Shetland Islands",
    "Ida-Virumaa",
    "Blagoevgrad Province",
    "More in...",
    "York",
    "Alytus County",
    "Belgorod oblast",
    "Aberdeen",
    "More in...",
    "Vienna",
    "Koprivnica-Križevci",
    "Enschede",
    "Liguria",
    "Belgorod oblast",
    "Brussels",
    "Marijampole County",
    "Kharkiv region",
    "Marche",
    "Carcassonne",
    "Alicante",
    "Altai Region",
    "Kaliningrad oblast",
    "Auxerre",
    "Vratsa Province",
    "Friuli-Venezia Giulia",
    "Abruzzo",
    "Sheffield",
    "Minsk",
    "Biarritz",
    "Biarritz",
    "Chernihiv region",
    "Greater Poland Voivodeship",
    "Borlänge",
    "Šiauliai County",
    "Chartres",
    "Békéscsaba",
    "Basilicata",
    "Belfast",
    "Kaliningrad oblast",
    "Debrecen",
    "Truro",
    "Kecskemét",
    "Leeuwarden",
    "Baztan",
    "Pelagonia",
    "Brno",
    "Antigua",
    "Chelyabinsk oblast",
    "Autonomous Republic of Crimea",
    "Dnipropetrovsk region",
    "Ayr",
    "Drava",
    "Altai Region",
    "Peterborough",
    "Savinja",
    "Košice Region",
    "Bourges",
    "Derby",
    "Avignon",
    "Gorizia",
    "Antalya",
    "Lublin Voivodeship",
    "Annecy",
    "Dumfries",
    "Tyrol",
    "Győr",
    "Adana",
    "Kaunas County",
    "Apeldoorn",
    "Abruzzo",
    "Burgas Province",
    "Châteauroux",
    "Vidin Province",
    "Gomel",
    "Châteauroux",
    "Stara Zagora Province",
    "Kabardino-Balkar Republic",
    "Karlovac",
    "Neubrandenburg",
    "Nord-Est",
    "Nottingham",
    "Kuyavian-Pomeranian Voivodeship",
    "Kaluga oblast",
    "Agen",
    "Krasonyarsk region",
    "Diyarbakir",
    "Šumadija and Western Serbia",
    "Alicante",
    "Bruges",
    "Arkhangelsk oblast",
    "Baku",
    "Biarritz",
    "Fgura",
    "Amur oblast",
    "Chisinau",
    "Den Haag",
    "Jõgeva County",
    "Jyväskylä",
    "Carinthia",
    "Pelagonia",
    "Brno",
    "Istria",
    "Salzburg",
    "Kouvola",
    "Budapest",
    "Komi Republic",
    "Upper Carniola",
    "Newcastle",
    "Kherson region",
    "Peterborough",
    "Molise",
    "Harju County",
    "Apulia",
    "Uelzen",
    "Budapest",
    "Marche",
    "Bruges",
    "Birmingham",
    "Neubrandenburg",
    "Chechen Republic",
    "Altai Region",
    "Apulia",
    "Pelagonia",
    "Calabria",
    "Enschede",
    "Avignon",
    "Liguria",
    "Koprivnica-Križevci",
    "Blagoevgrad Province",
    "Altai Region",
    "City of  Zagreb",
    "Donetsk region",
    "Amiens",
    "Brno",
    "Aix-en-Provence",
    "Banja Luka",
    "Bursa",
    "Bjelovar-Bilogora",
    "Aix-en-Provence",
    "Lombardy",
    "Kirov oblast",
    "Wrexham",
    "Kristiansand",
    "Békéscsaba",
    "Antigua",
    "Drava",
    "Lower Silesian Voivodeship",
    "Vilnius county",
    "Alytus County",
    "Kyustendil Province",
    "Apeldoorn",
    "Harju County",
    "Kharkiv region",
    "Vienna",
    "Ivanovo oblast",
    "Tyrol",
    "Gabrovo Province",
    "Banská Bystrica Region",
    "Kostroma oblast",
    "Savinja",
    "Šumadija and Western Serbia",
    "Donetsk region",
    "Ankara",
    "Gävle",
    "Lovech Province",
    "Dublin",
    "Apulia",
    "More in...",
    "Helsinki",
    "Šumadija and Western Serbia",
    "Northampton",
    "Lubusz Voivodeship",
    "Ulm",
    "Ashkirk",
    "More in...",
    "Cherkasy region",
    "Baku",
    "Chelyabinsk oblast",
    "Autonomous Republic of Crimea",
    "Bourges",
    "Lelystad",
    "Piedmont",
    "Marburg",
    "Kaluga oblast",
    "Apulia",
    "Aosta Valley",
    "Burgenland",
    "Kaunas County",
    "More in...",
    "Aurich",
    "Belgrade",
    "Lazio",
    "Elbasan County",
    "Eindhoven",
    "Kotayk' Province",
    "Sofia",
    "Wrexham",
    "Ghent",
    "Järvamaa",
    "Antigua",
    "Kardzhali Province",
    "Agen",
    "Ayr",
    "Lublin Voivodeship",
    "Kristiansand",
    "Chalon-sur-Saône",
    "Coastal–Karst",
    "Sheffield",
    "Marijampole County",
    "Lesser Poland Voivodeship",
    "Jyväskylä",
    "Marijampole County",
    "Chisinau",
    "Helsinki",
    "Kaliningrad oblast",
    "Caernarfon",
    "Göteborg",
    "Balti",
    "Brest",
    "Würzburg",
    "Latgale Region",
    "Namur",
    "Vitsyebsk",
    "More in...",
    "Apulia",
    "Altai Region",
    "Châteauroux",
    "Liège",
    "Kurgan oblast",
    "Lovech Province",
    "Munich",
    "Bjelovar-Bilogora",
    "Burgas Province",
    "Apeldoorn",
    "Drava",
    "Savinja",
    "More in...",
    "Cherbourg",
    "Jõgeva County",
    "Friuli-Venezia Giulia",
    "Banja Luka",
    "Brest",
    "Mura",
    "Järvamaa",
    "Charleroi",
    "Kouvola",
    "Bucharest-Ilfov",
    "More in...",
    "Kristiansand",
    "Hradec Králové",
    "Salzburg",
    "Amur oblast",
    "Lublin Voivodeship",
    "Marijampole County",
    "Mons",
    "Targovishte Province",
    "Debrecen",
    "Bergen",
    "Helsinki",
    "Zemgale Region",
    "Fgura",
    "Burgas Province",
    "Molise",
    "Kherson region",
    "Cherkasy region",
    "Astrakhan oblast",
    "City of  Zagreb",
    "Central Slovenia",
    "Panevezys County",
    "Krasnodar region",
    "Chartres",
    "Joensuu",
    "Eger",
    "Budapest",
    "Doboj",
    "Avignon",
    "Jewish Autonomous Region",
    "Amur oblast",
    "Salzburg",
    "Bayonne",
    "Sheffield",
    "Varna Province",
    "Elbasan County",
    "More in...",
    "Dubrovnik–Neretva",
    "Utena County",
    "Sofia Province",
    "Khabarovsk region",
    "Cambridge",
    "Portsmouth-Southampton",
    "Bursa",
    "Bordeaux",
    "Klaipeda County",
    "Krasnodar region",
    "Jura",
    "Kaliningrad oblast",
    "Auxerre",
    "Eastern Region",
    "Bilbao",
    "Annecy",
    "Besançon",
    "Bratislava Region",
    "Cottbus",
    "Vorarlberg",
    "Brod-Posavina",
    "Brest",
    "Upper Austria",
    "Cherkasy region",
    "Marche",
    "Lombardy",
    "Central Sava",
    "Friuli-Venezia Giulia",
    "Ghent",
    "Cardiff",
    "Amiens",
    "Balti",
    "Kamchatka Peninsula",
    "Gabrovo Province",
    "Coastal–Karst",
    "Vienna",
    "Aberdeen",
    "York",
    "Utena County",
    "Charleville-Mézières",
    "Kharkiv region",
    "Schwerin",
    "Apulia",
    "Andorra la Vella",
    "Klaipeda County",
    "Piedmont",
    "Northeastern Region",
    "Tbilisi",
    "Berlin",
    "Eger",
    "City of  Zagreb",
    "Barcelona",
    "Biarritz",
    "Antigua",
    "Gorizia",
    "Ivano-Frankivsk region",
    "Irkutsk oblast",
    "Lódz Voivodeship",
    "Piedmont",
    "Taurage County",
    "Nuremberg",
    "Hämeenlinna",
    "Šiauliai County",
    "Joensuu",
    "Samegrelo-Zemo Svaneti",
    "Cherkasy region",
    "Lower Silesian Voivodeship",
    "Nuremberg",
    "Savinja",
    "Bruges",
    "Koprivnica-Križevci",
    "Dibër County",
    "Brest",
    "Borlänge",
    "Kecskemét",
    "Gomel",
    "Altai Region",
    "Newcastle",
    "Upper Carniola",
    "Emilia–Romagna",
    "Hiiumaa",
    "Jihlava",
    "Harju County",
    "Bilbao",
    "Middelburg",
    "Karachay–Cherkess Republic",
    "Bijeljina",
    "Krasonyarsk region",
    "Istria",
    "Stara Zagora Province",
    "Bourges",
    "Piedmont",
    "Khabarovsk region",
    "Karachay–Cherkess Republic",
    "Aix-en-Provence",
    "Tbilisi",
    "Kaliningrad oblast",
    "Varna Province",
    "Bordeaux",
    "More in...",
    "Antwerp",
    "Athina",
    "Ganja-Gazakh",
    "Fgura",
    "Nottingham",
    "Bucharest-Ilfov",
    "Pelagonia",
    "Karlovy Vary",
    "Jyväskylä",
    "Bourges",
    "Uelzen",
    "Debrecen",
    "Sofia",
    "Bursa",
    "Tournai",
    "Tyrol",
    "Harju County",
    "Irkutsk oblast",
    "Chernihiv region",
    "Piedmont",
    "Vitsyebsk",
    "Kecskemét",
    "More in...",
    "Irkutsk oblast",
    "Burgas Province",
    "Aosta Valley",
    "Debrecen",
    "Edinburgh",
    "Lower Silesian Voivodeship",
    "Antalya",
    "Ghent",
    "Utena County",
    "Alicante",
    "'s-Hertogenbosch",
    "Bordeaux",
    "Cherbourg",
    "Lublin Voivodeship",
    "Cologne",
    "Komi Republic",
    "Panevezys County",
    "Angoulême",
    "Châteauroux",
    "More in...",
    "Lelystad",
    "Kosovo and Metohija",
    "Brest",
    "Northeastern Region",
    "Gävle",
    "Kherson region",
    "Diyarbakir",
    "Blagoevgrad Province",
    "Latgale Region",
    "Oxford",
    "Ankara",
    "More in...",
    "Munich",
    "Gomel",
    "Varna Province",
    "Central Sava",
    "Berlin",
    "Bucharest-Ilfov",
    "Apulia",
    "Gorizia",
    "Avignon",
    "Cherkasy region",
    "Alicante",
    "Kosovo and Metohija",
    "Plymouth",
    "Helsinki",
    "Breda",
    "Khanty-Mansi Autonomous Area",
    "Lazio",
    "Varna Province",
    "Edinburgh",
    "City of  Zagreb",
    "Chisinau",
    "Piedmont",
    "More in...",
    "Copenhagen",
    "Harju County",
    "Gävle",
    "Blagoevgrad Province",
    "Antigua",
    "Enschede",
    "Diyarbakir",
    "Antigua",
    "Middelburg",
    "Namur",
    "Göteborg",
    "Colchester",
    "Shetland Islands",
    "Namur",
    "Kouvola",
    "Joensuu",
    "Athina",
    "Caen",
    "Biarritz",
    "Cardiff",
    "Ashkirk",
    "Graubünden",
    "Chelyabinsk oblast",
    "Den Haag",
    "Styria",
    "Kemerovo oblast",
    "Bucharest-Ilfov",
    "Bremerhaven",
    "Altai Region",
    "Békéscsaba",
    "Besançon",
    "Nottingham",
    "Avignon",
    "Varna Province",
    "Ankara",
    "Marijampole County",
    "Greek Islands",
    "Salzburg",
    "Cherbourg",
    "Minsk",
    "Apeldoorn",
    "Minsk",
    "Dumfries",
    "Annecy",
    "Truro",
    "Sofia",
    "Marijampole County",
    "Namur",
    "Altai Republic",
    "Charleville-Mézières",
    "Swindon",
    "Amiens",
    "Kardzhali Province",
    "Doboj",
    "Copenhagen",
    "Belgrade",
    "Blagoevgrad Province",
    "Almere",
    "Istria",
    "Kosovo and Metohija",
    "Bjelovar-Bilogora",
    "Karachay–Cherkess Republic",
    "Bursa",
    "Alytus County",
    "Lower Silesian Voivodeship",
    "Dublin",
    "Amsterdam",
    "Mura",
    "Békéscsaba",
    "Central Slovenia",
    "Kamchatka Peninsula",
    "Kaluga oblast",
    "Dundee",
    "Berlin",
    "Campania",
    "Borlänge",
    "Besançon",
    "Donetsk region",
    "Leeuwarden",
    "Stockton-on-Tees",
    "Albi",
    "Bilbao",
    "Borlänge",
    "Greek Islands",
    "Molise",
    "Aix-en-Provence",
    "Blackpool",
    "Avignon",
    "More in...",
    "Dobrich Province",
    "Eger",
    "Šumadija and Western Serbia",
    "Panevezys County",
    "Bjelovar-Bilogora",
    "Sofia",
    "Varna Province",
    "Encamp",
    "Dobrich Province",
    "Albi",
    "Kemerovo oblast",
    "More in...",
    "Agen",
    "Diyarbakir",
    "Brest",
    "Bourges",
    "Coastal–Karst",
    "Emilia–Romagna",
    "Kherson region",
    "Coastal–Karst",
    "Burgas Province",
    "Angers",
    "Helsinki",
    "Targovishte Province",
    "Belgorod oblast",
    "Carinthia",
    "Vitsyebsk",
    "Burgenland",
    "Belgorod oblast",
    "Carinthia",
    "Krasnodar region",
    "Altai Region",
    "Southend-on-Sea",
    "York",
    "Lovech Province",
    "Carcassonne",
    "Chisinau",
    "Angers",
    "Apulia",
    "Southend-on-Sea",
    "Calais",
    "Ghent",
    "Kirov oblast",
    "Namur",
    "Kamchatka Peninsula",
    "Swansea",
    "Drava",
    "Basilicata",
    "Middelburg",
    "Latgale Region",
    "Auxerre",
    "Lublin Voivodeship",
    "Ida-Virumaa",
    "Liguria",
    "Diyarbakir",
    "Khanty-Mansi Autonomous Area",
    "Salzburg",
    "Košice Region",
    "Albi",
    "Baztan",
    "Dublin",
    "More in...",
    "Carinthia",
    "Vidin Province",
    "Swindon",
    "Veliko Tarnovo Province",
    "More in...",
    "Karlovy Vary",
    "Adana",
    "Campania",
    "Chuvash Republic",
    "Lisboa",
    "Kostroma oblast",
    "Bilbao",
    "Cahul",
    "Marche",
    "Ghent",
    "Central Slovenia",
    "Panevezys County",
    "Zemgale Region",
    "Ankara",
    "Savinja",
    "Styria",
    "Enschede",
    "Kharkiv region",
    "Belgorod oblast",
    "Hämeenlinna",
    "Khanty-Mansi Autonomous Area",
    "Kyustendil Province",
    "Calabria",
    "Saarbrücken",
    "Barcelona",
    "Hradec Králové",
    "Brest",
    "Sofia Province",
    "Tournai",
    "Haskovo Province",
    "Istria",
    "Carcassonne",
    "Besançon",
    "Dublin",
    "Hiiumaa",
    "Ghent",
    "Hiiumaa",
    "Lublin Voivodeship",
    "Khanty-Mansi Autonomous Area",
    "Chisinau",
    "Dobrich Province",
    "Greek Islands",
    "Bonn",
    "Auxerre",
    "Vilnius county",
    "Campania",
    "Kecskemét",
    "Berlin",
    "Antalya",
    "Eger",
    "Astrakhan oblast",
    "Fier County",
    "Bern",
    "Emmen",
    "Kristiansand",
    "Panevezys County",
    "Elbasan County",
    "Daghlig Shirvan",
    "Aosta Valley",
    "Diyarbakir",
    "Greater Poland Voivodeship",
    "Istria",
    "Samegrelo-Zemo Svaneti",
    "Molise",
    "Albi",
    "Astrakhan oblast",
    "Southeast Slovenia",
    "Liguria",
    "More in...",
    "Lazio",
    "Burgas Province",
    "Chisinau",
    "Molise",
    "Dubrovnik–Neretva",
    "Vitsyebsk",
    "Würzburg",
    "Alytus County",
    "Klaipeda County",
    "Minsk",
    "Caen",
    "Munich",
    "Adana",
    "Kyustendil Province",
    "Shetland Islands",
    "Derby",
    "Donetsk region",
    "Khabarovsk region",
    "Šiauliai County",
    "Bryansk oblast",
    "Kurgan oblast",
    "Carinthia",
    "Cherbourg",
    "Kuyavian-Pomeranian Voivodeship",
    "Mons",
    "Dumfries",
    "Bremerhaven",
    "Ida-Virumaa",
    "Würzburg",
    "Kosovo and Metohija",
    "Barcelona",
    "Lombardy",
    "Khanty-Mansi Autonomous Area",
    "Stara Zagora Province",
    "Swansea",
    "Bourges",
    "Békéscsaba",
    "Coastal–Karst",
    "Carcassonne",
    "Taunton",
    "Kaunas County",
    "Elbasan County",
    "Joensuu",
    "Basilicata",
    "Ceské Budejovice",
    "Šumadija and Western Serbia",
    "Šumadija and Western Serbia",
    "Groningen",
    "Lódz Voivodeship",
    "Ida-Virumaa",
    "Dubrovnik–Neretva",
    "Marijampole County",
    "Aberdeen",
    "Liguria",
    "Chisinau",
    "Vilnius county",
    "Belgrade",
    "Antigua",
    "Uelzen",
    "Adjara",
    "Šiauliai County",
    "Dobrich Province",
    "Adana",
    "Pelagonia",
    "Bourges",
    "Mons",
    "More in...",
    "Besançon",
    "Elbasan County",
    "Southeast Slovenia",
    "Bayreuth",
    "Avignon",
    "Pelagonia",
    "Antalya",
    "Kurzeme Region",
    "Krasonyarsk region",
    "Jihlava",
    "Karlovy Vary",
    "Bourges",
    "More in...",
    "Oxford",
    "Kyustendil Province",
    "Enschede",
    "Aalborg",
    "Andorra la Vella",
    "Altai Republic",
    "Liège",
    "Jyväskylä",
    "Aberdeen",
    "Passau",
    "Banja Luka",
    "Apulia",
    "Angers",
    "Coastal–Karst",
    "Kostroma oblast",
    "Angers",
    "Saarbrücken",
    "Koprivnica-Križevci",
    "Diyarbakir",
    "Carcassonne",
    "Krasnodar region",
    "Baku",
    "Agen",
    "Khabarovsk region",
    "Lódz Voivodeship",
    "Jihlava",
    "Norwich",
    "Amiens",
    "Burgenland",
    "Banja Luka",
    "Imereti",
    "Krasonyarsk region",
    "Baztan",
    "Altai Republic",
    "Varna Province",
    "Centru",
    "Bordeaux",
    "Ivano-Frankivsk region",
    "Kristiansand",
    "Breda",
    "Järvamaa",
    "Lisboa",
    "Marijampole County",
    "Barcelona",
    "Mura",
    "Kharkiv region",
    "Belgorod oblast",
    "Emilia–Romagna",
    "Bilbao",
    "Piedmont",
    "Antwerp",
    "Veliko Tarnovo Province",
    "Würzburg",
    "Vilnius county",
    "Bryansk oblast",
    "Liège",
    "Plymouth",
    "Eindhoven",
    "Norwich",
    "Fgura",
    "Bucharest-Ilfov",
    "Brod-Posavina",
    "Portsmouth-Southampton",
    "Aberystwyth",
    "Alytus County",
    "Abkhazia",
    "Dnipropetrovsk region",
    "Shetland Islands",
    "Swindon",
    "Brod-Posavina",
    "Caen",
    "Lazio",
    "Kosovo and Metohija",
    "Bender",
    "Amiens",
    "Balti",
    "Sofia Province",
    "Aalborg",
    "Truro",
    "Kuyavian-Pomeranian Voivodeship",
    "Amiens",
    "Panevezys County",
    "Bilbao",
    "Abruzzo",
    "Bender",
    "Lisboa",
    "Birmingham",
    "Debrecen",
    "Alytus County",
    "Dundee",
    "Autonomous Republic of Crimea",
    "Šumadija and Western Serbia",
    "Basilicata",
    "Marche",
    "Antwerp",
    "Maastricht",
    "Plymouth",
    "Harju County",
    "Komi Republic",
    "Ivano-Frankivsk region",
    "Chechen Republic",
    "Békéscsaba",
    "Altai Region",
    "Kaluga oblast",
    "Koprivnica-Križevci",
    "Brighton",
    "Dnipropetrovsk region",
    "Šiauliai County",
    "Banja Luka",
    "Annecy",
    "Győr",
    "Kurgan oblast",
    "Kemerovo oblast",
    "Dubrovnik–Neretva",
    "Chernihiv region",
    "Aix-en-Provence",
    "Cherkasy region",
    "Upper Austria",
    "Guba-Khachmaz",
    "Latgale Region",
    "Lower Sava",
    "Marburg",
    "Dumfries",
    "Dubrovnik–Neretva",
    "Swindon",
    "Chalon-sur-Saône",
    "Angoulême",
    "Hasselt",
    "Kostroma oblast",
    "Lubusz Voivodeship",
    "Aosta Valley",
    "Ayr",
    "Autonomous Republic of Crimea",
    "Belgorod oblast",
    "Annecy",
    "Bursa",
    "Šumadija and Western Serbia",
    "Koprivnica-Križevci",
    "Brest",
    "Bourges",
    "Aberystwyth",
    "Latgale Region",
    "Bender",
    "Calabria",
    "Truro",
    "Elbasan County",
    "Bjelovar-Bilogora",
    "Cherkasy region",
    "Charleville-Mézières",
    "Kaposvár",
    "Enschede",
    "Komi Republic",
    "Istria",
    "Tbilisi",
    "Lisboa",
    "Bryansk oblast",
    "Carinthia",
    "Kurzeme Region",
    "Kuyavian-Pomeranian Voivodeship",
    "Donetsk region",
    "Vratsa Province",
    "Tbilisi",
    "Kostroma oblast",
    "Molise",
    "Hasselt",
    "Agen",
    "Kouvola",
    "Basilicata",
    "Taurage County",
    "Chernivtsi region",
    "Montana Province",
    "Kurzeme Region",
    "Košice Region",
    "Kecskemét",
    "More in...",
    "Uelzen",
    "Bristol",
    "Aosta Valley",
    "Antigua",
    "Lazio",
    "Kurgan oblast",
    "Banská Bystrica Region",
    "Kouvola",
    "Southeast Slovenia",
    "Copenhagen",
    "Belgorod oblast",
    "Inner Carniola–Karst",
    "Joensuu",
    "Eindhoven",
    "Göteborg",
    "Joensuu",
    "Lublin Voivodeship",
    "Salzburg",
    "Budapest",
    "Bourges",
    "Portsmouth-Southampton",
    "Kostroma oblast",
    "Maastricht",
    "Kouvola",
    "Lower Silesian Voivodeship",
    "Antigua",
    "Chartres",
    "Doboj",
    "Bratislava Region",
    "Jyväskylä",
    "Hradec Králové",
    "Doboj",
    "Ivano-Frankivsk region",
    "Ankara",
    "Styria",
    "Blagoevgrad Province",
    "Molise",
    "Vratsa Province",
    "Antigua",
    "Kharkiv region",
    "Bordeaux",
    "Chalon-sur-Saône",
    "Kurzeme Region",
    "Munich",
    "Bielefeld",
    "Lombardy",
    "Kyustendil Province",
    "Würzburg",
    "Lódz Voivodeship",
    "Kyustendil Province",
    "Varna Province",
    "Antigua",
    "Aosta Valley",
    "Blackpool",
    "Dnipropetrovsk region",
    "Khanty-Mansi Autonomous Area",
    "Albi",
    "Dublin",
    "Andorra la Vella",
    "Drava",
    "Birmingham",
    "Kabardino-Balkar Republic",
    "Athina",
    "Belgrade",
    "Zemgale Region",
    "Cahul",
    "Dobrich Province",
    "Ivano-Frankivsk region",
    "Varna Province",
    "Caen",
    "Autonomous Republic of Crimea",
    "Brno",
    "Järvamaa",
    "Hämeenlinna",
    "Angers",
    "Middelburg",
    "Andorra la Vella",
    "Chernihiv region",
    "Basilicata",
    "Charleville-Mézières",
    "Truro",
    "Latgale Region",
    "Aix-en-Provence",
    "Albi",
    "Greek Islands",
    "Jewish Autonomous Region",
    "Autonomous Republic of Crimea",
    "Belgrade",
    "Bern",
    "Kurgan oblast",
    "Dublin",
    "Lisboa",
    "Coastal–Karst",
    "Khabarovsk region",
    "Kaunas County",
    "Chisinau",
    "Kaliningrad oblast",
    "Lódz Voivodeship",
    "Antwerp",
    "Diyarbakir",
    "Stara Zagora Province",
    "Friuli-Venezia Giulia",
    "Belgorod oblast",
    "Baku",
    "Aix-en-Provence",
    "Komi Republic",
    "Altai Region",
    "Aosta Valley",
    "Neubrandenburg",
    "Brno",
    "Coastal–Karst",
    "Greater Poland Voivodeship",
    "Diyarbakir",
    "Joensuu",
    "Würzburg",
    "Joensuu",
    "Varna Province",
    "Klaipeda County",
    "Eindhoven",
    "Donetsk region",
    "Antigua",
    "Angoulême",
    "Aalborg",
    "Kaposvár",
    "Alytus County",
    "Peterborough",
    "Utena County",
    "Krasonyarsk region",
    "Basel",
    "Brussels",
    "Lazio",
    "Vidin Province",
    "Kvemo Kartli",
    "Cottbus",
    "Khabarovsk region",
    "Kurgan oblast",
    "Geneve-Annemasse",
    "Bayonne",
    "Chernihiv region",
    "Amiens",
    "Bratislava Region",
    "Ivano-Frankivsk region",
    "Brest",
    "Besançon",
    "Khabarovsk region",
    "Apulia",
    "Geneve-Annemasse",
    "Berlin",
    "Kristiansand",
    "Utena County",
    "Edinburgh",
    "Kaunas County",
    "Diyarbakir",
    "Harju County",
    "Bucharest-Ilfov",
    "Utena County",
    "Brest",
    "Taunton",
    "Centru",
    "Agen",
    "Carinthia",
    "Burgas Province",
    "Kharkiv region",
    "Krasnodar region",
    "Carcassonne",
    "Fgura",
    "Vitsyebsk",
    "Passau",
    "Antalya",
    "Tbilisi",
    "Vitsyebsk",
    "Montana Province",
    "Upper Carniola",
    "Kaunas County",
    "Khabarovsk region",
    "Kemerovo oblast",
    "Savinja",
    "Kaliningrad oblast",
    "Agen",
    "Aix-en-Provence",
    "Kurgan oblast",
    "Eger",
    "Dublin",
    "Donetsk region",
    "Autonomous Republic of Crimea",
    "Vidin Province",
    "Haskovo Province",
    "Lower Silesian Voivodeship",
    "Bratislava Region",
    "Kherson region",
    "Kamchatka Peninsula",
    "Schwerin",
    "Minsk",
    "More in...",
    "Dnipropetrovsk region",
    "Plymouth",
    "Upper Austria",
    "Alicante",
    "Basilicata",
    "Apeldoorn",
    "Drava",
    "Würzburg",
    "Šumadija and Western Serbia",
    "Abruzzo",
    "Basilicata",
    "Gävle",
    "Kaluga oblast",
    "Dundee",
    "Gorizia",
    "Kherson region",
    "Baztan",
    "Kherson region",
    "Jihlava",
    "Järvamaa",
    "Truro",
    "Ida-Virumaa",
    "More in...",
    "Göteborg",
    "Amiens",
    "Coastal–Karst",
    "Daghlig Shirvan",
    "Fier County",
    "Kurzeme Region",
    "Nuremberg",
    "Šumadija and Western Serbia",
    "Burgenland",
    "Hämeenlinna",
    "Hämeenlinna",
    "Kurzeme Region",
    "Tyrol",
    "Dumfries",
    "Dubrovnik–Neretva",
    "Adana",
    "Barcelona",
    "Copenhagen",
    "Vorarlberg",
    "Copenhagen",
    "Swansea",
    "Kaposvár",
    "Vitsyebsk",
    "Savinja",
    "Aberdeen",
    "Bayonne",
    "Central Slovenia",
    "Blagoevgrad Province",
    "Kherson region",
    "Lombardy",
    "Bucharest-Ilfov",
    "Helsinki",
    "Chalon-sur-Saône",
    "Astrakhan oblast",
    "Ghent",
    "Groningen",
    "Greek Islands",
    "Debrecen",
    "Joensuu",
    "Chelyabinsk oblast",
    "Lombardy",
    "Klaipeda County",
    "Jura",
    "Kharkiv region",
    "Kecskemét",
    "Baztan",
    "Stara Zagora Province",
    "Styria",
    "Andorra la Vella",
    "Chisinau",
    "Baztan",
    "Campania",
    "Autonomous Republic of Crimea",
    "Alytus County",
    "Bonn",
    "Bordeaux",
    "Saarbrücken",
    "Savinja",
    "Targovishte Province",
    "Lazio",
    "Chuvash Republic",
    "Belfast",
    "Chalon-sur-Saône",
    "Ararat Province",
    "Drava",
    "Besançon",
    "Dundee",
    "Athina",
    "Stuttgart",
    "Hasselt",
    "Autonomous Republic of Crimea",
    "Bijeljina",
    "Zemgale Region",
    "Namur",
    "Ivano-Frankivsk region",
    "Southeast Slovenia",
    "Greater Poland Voivodeship",
    "Hiiumaa",
    "Banská Bystrica Region",
    "Kardzhali Province",
    "Charleville-Mézières",
    "Gomel",
    "Göteborg",
    "Chalon-sur-Saône",
    "Jihlava",
    "Saarbrücken",
    "City of  Zagreb",
    "Kemerovo oblast",
    "Birmingham",
    "Alicante",
    "Den Helder",
    "Kherson region",
    "Kemerovo oblast",
    "Karlovy Vary",
    "Den Haag",
    "Kurgan oblast",
    "Utena County",
    "Lombardy",
    "Southend-on-Sea",
    "Liguria",
    "More in...",
    "Baku",
    "Bjelovar-Bilogora",
    "Belgrade",
    "Burgas Province",
    "Kaluga oblast",
    "Tbilisi",
    "Jyväskylä",
    "Athina",
    "Sheffield",
    "Blagoevgrad Province",
    "Klaipeda County",
    "Belgrade",
    "Middelburg",
    "Kouvola",
    "Cherbourg",
    "Hasselt",
    "Kurgan oblast",
    "Alytus County",
    "Liège",
    "Peterborough",
    "Dresden",
    "Greek Islands",
    "More in...",
    "Liège",
    "Karlovy Vary",
    "Bilbao",
    "Charleville-Mézières",
    "Kaliningrad oblast",
    "Fgura",
    "Gorizia",
    "Tbilisi",
    "Stuttgart",
    "Emilia–Romagna",
    "Fgura",
    "Lódz Voivodeship",
    "Harju County",
    "Hiiumaa",
    "Chalon-sur-Saône",
    "Norwich",
    "Kurzeme Region",
    "Wrexham",
    "Burgas Province",
    "Gävle",
    "Mura",
    "Latgale Region",
    "Harju County",
    "Gomel",
    "Northeastern Region",
    "Joensuu",
    "Apulia",
    "Hämeenlinna",
    "Debrecen",
    "Friuli-Venezia Giulia",
    "Plymouth",
    "Vitsyebsk",
    "Bijeljina",
    "Munich",
    "Ankara",
    "Munich",
    "Kecskemét",
    "Adana",
    "Irkutsk oblast",
    "Amiens",
    "Swindon",
    "Taunton",
    "Kosovo and Metohija",
    "Agen",
    "Khabarovsk region",
    "Diyarbakir",
    "Liège",
    "Bilbao",
    "Belfast",
    "Karlovac",
    "Klaipeda County",
    "Taunton",
    "Hradec Králové",
    "Dortmund",
    "Agen",
    "Elbasan County",
    "Athina",
    "Klaipeda County",
    "Wrexham",
    "Kemerovo oblast",
    "Peterborough",
    "Ceské Budejovice",
    "Ayr",
    "Klaipeda County",
    "Hasselt",
    "Groningen",
    "Central Slovenia",
    "Munich",
    "Brest",
    "Cherkasy region",
    "Kaunas County",
    "Dumfries",
    "Kecskemét",
    "Angoulême",
    "Namur",
    "Savinja",
    "Amur oblast",
    "Kaposvár",
    "Ceské Budejovice",
    "Hämeenlinna",
    "Kostroma oblast",
    "Kuyavian-Pomeranian Voivodeship",
    "Calais",
    "Middelburg",
    "Liège",
    "Brno",
    "Bordeaux",
    "Auxerre",
    "Eger",
    "Derry",
    "Donetsk region",
    "Göteborg",
    "Breda"
]

// var fields = ['city', 'coordinates'];

// cities.map(function(city, coords) {

//     getCoords(city)
//         .then((coords, cities) => {
//             results  = (city + " : " + JSON.stringify(coords));
//             var fields = ['city', 'coordinates'];
//             json2csv({
//                 data: results,
//                 fields: fields
//             }, function(err, csv) {
//                 if (err)
//                     console.log(err)
//                 fs.writeFile('data.csv', csv, function(err) {
//                     if (err) {
//                         console.log(err);
//                     } else {
//                         console.log('shit\'s working bruh!');
//                     }
//                 })
//             })
//         });
// })
// for (var i = 0; i <= cities.length; i++) {
//     getCoords(cities[i])
//         .then((coords, cities) => {
//             console.log(cities[i] + " : " + JSON.stringify(coords));
//         });
// };
// json2csv({data: (city,JSON.stringify(coords)), fields: fields},function(err,csv){
// 	if(err)
// 		console.log(err)
// 	fs.writeFile('data.csv',csv, function(err){
// 		if (err) 
// 			throw err
// 		console.log('shit\'s working niggah!');

// 	})
// })





// ================ 	WORKING CODE 	 ================//
// var fields = ['city', 'coordinates'];

cities.map(function(city, coords) {
    getCoords(city)
        .then((coords, cities) => {
            //var infoz = [];
            infoz = [city, coords];
            //infoz.push(results)
            //results = (city + " : " + JSON.stringify(coords));
            //infoz = (infoz[0])
            //console.log(infoz)
            data = {
                "city": infoz[0],
                "coords": infoz[1]
            }
            //console.log(data)
            fs.appendFile("datanstuff.txt", JSON.stringify(data), function(err) {
                if (err) {
                    return console.log(err);
                }

                console.log("The file was saved!");
            });
            //return data
        });


})
//var todo =





//console.log(resultsnstuff)

// // for (var i = 0; i <= cities.length; i++) {
// //     getCoords(cities[i])
// //         .then((coords, cities) => {
// //             console.log(cities[i] + " : " + JSON.stringify(coords));
// //         });
// // };
// json2csv({data: (city,JSON.stringify(coords)), fields: fields},function(err,csv){
// 	if(err)
// 		console.log(err)
// 	fs.writeFile('data.csv',csv, function(err){
// 		if (err) 
// 			throw err
// 		console.log('shit\'s working niggah!');

// 	})
// })