var getCoords = require('city-to-coords');
var getCoords = require('city-to-coords');
var json2csv = require('json2csv');
var fs = require('fs')
var csvjson = require('csvjson');
var cities = [
"city",
"Losser, Netherlands",
"Kuopio, Finland",
"Gotse Delchev, Bulgaria",
"Mažeikiai, Lithuania",
"Nachod, Czech Republic",
"'s-Graveland, Netherlands",
"Rethymno, Greece",
"Cahul, Moldova",
"Harlingen, Netherlands",
"Mechelen, Belgium",
"Helsinki, Finland",
"Helsinki, Finland",
"Ameide, Netherlands",
"Yablanitsa, Bulgaria",
"Karlovy Vary, Czech Republic",
"Vilnius, Lithuania",
"Zwolle, Netherlands",
"Espoo, Finland",
"Pärnu, Estonia",
"Kishinev, Moldova",
"Vienna, Austria",
"Cakovec, Croatia",
"Copenhagen, Denmark",
"Nicosia, Cyprus",
"Bydgoszcz, Poland",
"Vitebsk, Belarus",
"Chania, Greece",
"Krk, Croatia",
"Anna, Estonia",
"Kicevo, Macedonia",
"Podgorica, Montenegro",
"Brussels, Belgium",
"Haaksbergen, Netherlands",
"Velika Kladuša, Bosnia and Herzegovina",
"Czestochowa, Poland",
"Liepaja, Latvia",
"Lopik, Netherlands",
"Sliven, Bulgaria",
"Bregenz, Austria",
"Kolding, Denmark",
"Biala Podlaska, Poland",
"Vammala, Finland",
"Jirnsum, Netherlands",
"Nivaa, Denmark",
"Hulsberg, Netherlands",
"Mogilev, Mogilyov Oblast , Belarus",
"Pernå, Finland",
"Wrocław, Poland",
"Valletta, Malta",
"Helsinki, Finland",
"Rousse, Bulgaria",
"София, Bulgaria",
"Patras, Greece",
"Tuzla, Bosnia and Herzegovina",
"Amsterdam, Netherlands",
"Slavonski Brod, Croatia",
"Jelah, Bosnia and Herzegovina",
"Lichtaart, Belgium",
"Varna, Bulgaria",
"Hundested, Denmark",
"Langstraat, Netherlands",
"Vaduz, Liechtenstein",
"Pardubice, Czech Republic",
"Gradacac, Bosnia and Herzegovina",
"Namur, Belgium",
"Tripolis, Greece",
"Grodno, Belarus",
"Tammela, Finland",
"Baku, Azerbaijan",
"Kuopio, Finland",
"Wierden, Netherlands",
"Borculo, Netherlands",
"Zary, Poland",
"Limassol, Cyprus",
"Gdynia, Poland",
"Wrocław, Poland",
"Argos, Greece",
"Mouscron, Belgium",
"Fredericia, Denmark",
"Siatista, Greece",
"Den Haag, Netherlands",
"Razlog, Bulgaria",
"Arta, Greece",
"Nes, Netherlands",
"Kyparissia, Greece",
"Hommelvik, Norway",
"Rousse, Bulgaria",
"Vennesla, Norway",
"DRAMMEN, Norway",
"Klaipeda, Klaipeda/Palanga, Lithuania",
"Testrup, Denmark",
"Varna, Bulgaria",
"София, Bulgaria",
"København, Denmark",
"Vushtrri, Albania",
"Drachten, Netherlands",
"Katowice, Poland",
"Greipstad, Norway",
"Zielona Góra, Poland",
"Skopje, Macedonia",
"Riga, Latvia",
"Svilengrad, Bulgaria",
"Almas, Møre og Romsdal , Norway",
"Innsbruck, Austria",
"Nicosia, Cyprus",
"Balti, Moldova",
"Olomouc, Czech Republic",
"Vaduz, Liechtenstein",
"Nicosia, Cyprus",
"Chavriata, Greece",
"Heist-op-den-Berg, Belgium",
"Diest, Belgium",
"Oslo, Norway",
"Oslo, Norway",
"Zuidlaren, Netherlands",
"Dobrich, Bulgaria",
"Rodenrijs, Netherlands",
"Tallinn, Estonia",
"Kladno, Czech Republic",
"Barendrecht, Netherlands",
"Ioannina, Greece",
"Bree, Belgium",
"Przemysl, Poland",
"Vratsa, Bulgaria",
"Rzeszow, Poland",
"Varaždin, Croatia",
"Chania, Greece",
"Kardla, Estonia",
"Kozani, Greece",
"Enschede, Netherlands",
"Brussels, Belgium",
"Herceg Novi, Montenegro",
"Riga, Latvia",
"Võru, Estonia",
"Lodz, Poland",
"Riga, Latvia",
"Zwolle, Netherlands",
"Zutphen, Netherlands",
"Rhodes, Greece",
"Chelm, Poland",
"Valasske Mezirici, Czech Republic",
"Dubrovnik, Croatia",
"Copenhagen, Denmark",
"Tbilisi, Georgia",
"Nijmegen, Netherlands",
"Mostar, Bosnia and Herzegovina",
"Rzeszów, Poland",
"Łódź, Poland",
"Nijmegen, Netherlands",
"Mytilini, Greece",
"Praha, Czech Republic",
"Oslo, Oslo, Norway",
"Huissen, Netherlands",
"Trondheim, Norway",
"Dalane, Telemark , Norway",
"Olsztyn, Poland",
"Bilthoven, Netherlands",
"Copenhagen, Denmark",
"Κρανίδιον, Greece",
"Sofia, Sofia, Bulgaria",
"Narva, Estonia",
"Minsk, Belarus",
"Plovdiv, Bulgaria",
"Poznan, Poland",
"Wien, Austria",
"Olsztyn, Poland",
"Castricum, Netherlands",
"Donji Vakuf, Bosnia and Herzegovina",
"Blagoevgrad, Bulgaria",
"Twello, Netherlands",
"Vienna, Austria",
"Erica, Netherlands",
"Larisa, Greece",
"Kontiolahti, Finland",
"Vilnius, Lithuania",
"Kristiansand, Norway",
"Skopje, Macedonia",
"Ignalina, Lithuania",
"Zundert, Netherlands",
"Radom, Poland",
"Westdorpe, Netherlands",
"Visoko, Bosnia and Herzegovina",
"Xanthi, Greece",
"Gliwice, Poland",
"Gorzow Slaski, Poland",
"Papendrecht, Netherlands",
"Łódź, Poland",
"Rovaniemi, Finland",
"Mogilev, Belarus",
"Groningen, Netherlands",
"Poznan, Poland",
"Enschede, Netherlands",
"Zagreb, Croatia",
"Nicosia, Cyprus",
"København, Denmark",
"Liberec, Czech Republic",
"Kielce, Poland",
"Bregenz, Austria",
"Wingene, Belgium",
"Kaarina, Finland",
"Klaipeda, Klaipeda/Palanga, Lithuania",
"Bedum, Netherlands",
"Corfu, Greece",
"Serres, Greece",
"Rijeka, Croatia",
"Rotterdam, Netherlands",
"Lahti, Finland",
"Maastricht, Netherlands",
"Putten, Netherlands",
"Siteia, Greece",
"Riihimäki, Finland",
"Thasos, Greece",
"Pula, Croatia",
"Beaumont, Belgium",
"Capelle aan den IJssel, Netherlands",
"Alexandroupoli, Greece",
"Patras, Greece",
"Nijverdal, Netherlands",
"Łódź, Poland",
"Linz, Austria",
"Limassol, Limassol, Cyprus",
"Bydgoszcz, Poland",
"Ylöjärvi, Finland",
"Oulu, Finland",
"Katowice, Poland",
"Leiden, Netherlands",
"Praha, Czech Republic",
"Oberpullendorf, Austria",
"Lamia, Greece",
"Krapkowice, Poland",
"Riga, Latvia",
"Smilde, Netherlands",
"Kavala, Greece",
"Lerik, Azerbaijan",
"København, Denmark",
"Terneuzen, Netherlands",
"Rzeszów, Poland",
"Jihlava, Czech Republic",
"Gorzów Wielkopolski, Poland",
"Reykjavík, Iceland",
"Hilversum, Netherlands",
"Joutseno, Finland",
"Bosanska Krupa, Bosnia and Herzegovina",
"Sliven, Bulgaria",
"Soest, Netherlands",
"Λάρισα, Greece",
"Thronos, Greece",
"Noord-Scharwoude, Netherlands",
"Karditsa, Greece",
"Wieringerwaard, Netherlands",
"Sarajevo, Bosnia and Herzegovina",
"Salzburg, Salzburg, Austria",
"Sofia, Bulgaria",
"Warszawa, Poland",
"Radom, Poland",
"Aalst, Belgium",
"Klagenfurt, Austria",
"Zielona Góra, Poland",
"Wageningen, Netherlands",
"Alkmaar, Netherlands",
"Tallinn, Estonia",
"Chios, Greece",
"Hollola, Finland",
"Opole, Poland",
"Victoria, MT, Malta",
"Lublin, Poland",
"Fier, Albania",
"Gdańsk, Poland",
"Saalfelden am Steinernen Meer, Austria",
"Kosove, Albania",
"Pardubice, Czech Republic",
"Riga, Riga, Latvia",
"Mont Rigi, Belgium",
"Walbrzych, Poland",
"Szczecin, Poland",
"Plovdiv, Bulgaria",
"Gent, Belgium",
"Tallinn, Estonia",
"Sarajevo, Bosnia and Herzegovina",
"Baranovichi, Belarus",
"Yerevan, Armenia",
"Askim, Norway",
"Dordrecht, Netherlands",
"Groningen, Netherlands",
"Chania, Greece",
"Dubrovnik, Croatia",
"Rotterdam, Netherlands",
"Sippola, Finland",
"Monaco, Monaco",
"Lillehammer, Norway",
"Sarajevo, Bosnia and Herzegovina",
"Bunschoten, Netherlands",
"Haapsalu, Estonia",
"Klaipeda, Klaipeda/Palanga, Lithuania",
"Salzburg, Austria",
"Pazardzhik, Bulgaria",
"Skopje, Macedonia",
"Szczecinek, Poland",
"Nokia, Finland",
"Tartu, Estonia",
"Warszawa, Poland",
"Trikala, Greece",
"Liege, Belgium",
"Wien, Austria",
"København, Denmark",
"Bijelo Polje, Montenegro",
"Egmond aan Zee, Netherlands",
"Praha, Czech Republic",
"Alexandroupoli, Greece",
"Tournai, Belgium",
"Albertslund, Denmark",
"Colfontaine, 7340, Belgium",
"Grodzisk Mazowiecki, Poland",
"Trondheim, Norway",
"Haderslev, Denmark",
"Tirana, Albania",
"København, Denmark",
"Burgas, Bulgaria",
"Slagelse, Denmark",
"Grodno, Belarus",
"Pärnu, Estonia",
"Tirane, Albania",
"Maaseik, Belgium",
"Rousse, Bulgaria",
"Mytilini, Greece",
"Zwolle, Netherlands",
"Vilnius, Lithuania",
"Heraklion, Greece",
"Burgas, Bulgaria",
"Hamrun, MT, Malta",
"Egem, Belgium",
"Oude Baan, Belgium",
"Rechnitz, Burgenland, Austria",
"Minsk, Belarus",
"Daugavpils, Latvia",
"Požega, Croatia",
"Plzeň, Czech Republic",
"Baku, Azerbaijan",
"Mechelen, Belgium",
"Middelburg, Netherlands",
"Prilep, Macedonia",
"Innsbruck, Austria",
"Białystok, Poland",
"Jyväskylä, Finland",
"Almelo, Netherlands",
"Minsk, Belarus",
"Chania, Greece",
"Patras, Greece",
"Chios, Greece",
"Dragør, Denmark",
"Nachod, Czech Republic",
"Lublin, Poland",
"Binche, Belgium",
"Utena, Lithuania",
"Paphos, Cyprus",
"Brussels, Belgium",
"Ringe, Denmark",
"Bielsko-Biala, Warsaw Warszawa, Poland",
"Gdynia, Poland",
"Bydgoszcz, Poland",
"Białystok, Poland",
"Kyustendil, Bulgaria",
"Kastoria, Greece",
"Arendal, Norway",
"Písek, Czech Republic",
"Jirnsum, Netherlands",
"Nicosia, Cyprus",
"Sofia, Bulgaria",
"Corinth, Greece",
"Polten, Niederosterreich, Austria",
"Grouw, Netherlands",
"Minsk, Belarus",
"Beverwijk, Netherlands",
"Ersfjordbotn, Troms, Norway",
"Dubrovnik, Croatia",
"Iraklion, Greece",
"Zielona Góra, Poland",
"Inowroclaw, Poland",
"Daugavpils, Latvia",
"Tallinn, Estonia",
"Nendeln, Liechtenstein",
"Dendermonde, Belgium",
"Lubaczow, Poland",
"Grodno, Belarus",
"Roosendaal, Netherlands",
"Turku, Finland",
"Lelystad, FL, Netherlands",
"Rhodes, Greece",
"Warzachewka Polska, Poland",
"Oulu, Finland",
"Haaren, Netherlands",
"Pernå, Finland",
"Aalborg, Denmark",
"Strumica, Macedonia",
"Meulebeke, Belgium",
"Kaunas, Lithuania",
"Margraten, Netherlands",
"Kortrijk, Belgium",
"Valmiyera, Latvia",
"Volos, Greece",
"Herent, Belgium",
"Krnjevo, Macedonia",
"Corfu, Greece",
"Tábor, Czech Republic",
"Klaipeda, Lithuania",
"Kohtla-Nomme, Estonia",
"Ioannina, Greece",
"Velsen, Netherlands",
"Levadeia, Greece",
"Bruxelles, Belgium",
"Komotini, Greece",
"Oostkamp, Belgium",
"Sippola, Finland",
"Hasselt, Belgium",
"Antwerp, Belgium",
"Purmerend, Netherlands",
"Baku, Azerbaijan",
"Konin, Poland",
"Genk, Belgium",
"Opole, Poland",
"Kaarina, Finland",
"Hum na Sutli, Croatia",
"Chios, Greece",
"Voorne, Netherlands",
"Copenhagen, Denmark",
"Glamoc, Bosnia and Herzegovina",
"Rhenen, Netherlands",
"Vocklabruck, Austria",
"Tallinn, Estonia",
"Gouda, Netherlands",
"Herceg-Novi, Montenegro",
"Kuopio, Finland",
"Grodno, Grodno Region, Belarus",
"Shumen, Bulgaria",
"Bergem, Luxembourg",
"Gomel, Belarus",
"Zagreb, Croatia",
"Warszawa, Poland",
"Vitebsk, Belarus",
"Kantara, Cyprus",
"Reykjavík, Iceland",
"Zagreb, Croatia",
"Hattem, Netherlands",
"Bielsko, Poland",
"Marijampole, Marijampole, Lithuania",
"Gornja Breza, Bosnia and Herzegovina",
"Chomutov, Czech Republic",
"Amsterdam, Netherlands",
"Sippola, Finland",
"Nicosia, Cyprus",
"Shumen, Bulgaria",
"Norre Lyngby, Denmark",
"Heraklion, Greece",
"Stavanger, Norway",
"Breskens, Netherlands",
"Sparti, Greece",
"Tampere, Finland",
"Wien, Austria",
"Gizycko, Poland",
"Rhodes, Greece",
"Lamia, Greece",
"Dieren, Netherlands",
"Kuopio, Finland",
"Stadskanaal, Netherlands",
"Skopje, Macedonia",
"Jyväskylä, Finland",
"Msida, Malta",
"Riga, Latvia",
"Sosnowiec, Poland",
"Horsens, Denmark",
"Amsterdam, Netherlands",
"Leende, Netherlands",
"Decin, Czech Republic",
"Amsterdam, Netherlands",
"Liberec, Czech Republic",
"Jyväskylä, Finland",
"Gharghur, Malta",
"Velika Gorica, Croatia",
"Lelystad, Netherlands",
"Zdroj, Poland",
"Tesanj, Bosnia and Herzegovina",
"Innsbruck, Austria",
"Leeuwarden, Netherlands",
"Arnhem, Netherlands",
"Łódź, Poland",
"Bad Ischl, Oberösterreich, Austria",
"Tampere, Finland",
"Split, Croatia",
"Slupsk, Poland",
"Almere-Buiten, Netherlands",
"Den Haag, Netherlands",
"Oslo, Norway",
"Enschede, Netherlands",
"Ostrava, Czech Republic",
"Amsterdam, Netherlands",
"Banja Luka, Bosnia and Herzegovina",
"Klagenfurt, Carinthia, Austria",
"Cazin, Bosnia and Herzegovina",
"Salo, Finland",
"Kraljevec Sesvetski, Croatia",
"Praha, Czech Republic",
"Heraklion, Greece",
"Zielona Gora, Poland",
"Rijeka, Croatia",
"Hippolytushoef, Netherlands",
"Birzebbuga, Malta",
"Loon op Zand, Netherlands",
"Riga, Latvia",
"Sint-niklaas, Belgium",
"Vis, Bulgaria",
"Pori, Finland",
"Tampere, Finland",
"Nieuw-Bergen, Netherlands",
"Schagen, Netherlands",
"Nordborg, Denmark",
"Corfu, Greece",
"Blagoevgrad, Bulgaria",
"Tampere, Finland",
"Oslo, Norway",
"Warszawa, Poland",
"Alkmaar, Netherlands",
"Imotski, Croatia",
"Jihlava, Czech Republic",
"Wien, Austria",
"Imatra, Finland",
"Sarajevo, Bosnia and Herzegovina",
"Hoeilaart, Belgium",
"Katowice, Poland",
"Espoo, Finland",
"Zlín, Czech Republic",
"Λάρισα, Greece",
"Lith, Netherlands",
"Wloclawek, Poland",
"Aalst, Belgium",
"Copenhagen, Denmark",
"София, Bulgaria",
"Legnica, Poland",
"Korce, Albania",
"Luxembourg, Luxembourg",
"Inkeroinen, Finland",
"Goes, Netherlands",
"Warszawa, Poland",
"Alphen aan den Rijn, Netherlands",
"Alytus, Alytus, Lithuania",
"Parnu, Estonia",
"Pärnu, Estonia",
"София, Bulgaria",
"Den Helder, Netherlands",
"Klagenfurt, Austria",
"Roosendaal, Netherlands",
"Lahti, Finland",
"Iecava, Latvia",
"Rethymno, Greece",
"София, Bulgaria",
"Tuzla, Bosnia and Herzegovina",
"Plovdiv, Bulgaria",
"Lublin, Poland",
"Rhodes, Greece",
"Den Helder, Netherlands",
"Lomza, Poland",
"Haarlem, Netherlands",
"Brest, Belarus",
"Oslo, Norway",
"Druskininkai, Lithuania",
"Tartu, Estonia",
"Koeru, Estonia",
"Spittal an der Drau, Carinthia, Austria",
"Bruxelles, Belgium",
"Opole, Poland",
"Aarhus, Denmark",
"Praha, Czech Republic",
"Ostrava, Czech Republic",
"Bregenz, Austria",
"Kraków, Poland",
"Roosendaal, Netherlands",
"Grojec, Poland",
"Brest, Belarus",
"Linz, Upper Austria, Austria",
"Liberec, Czech Republic",
"Fier, Albania",
"Šibenik, Croatia",
"Smolyan, Bulgaria",
"Elblag, Poland",
"Apeldoorn, Netherlands",
"Elbasan, Albania",
"Zaltbommel, Netherlands",
"Helsinki, Finland",
"Kozani, Greece",
"Tartu, Estonia",
"Smolyan, Bulgaria",
"Agstafa, Azerbaijan",
"Hjallerup, Denmark",
"Kohtla-Nomme, Parnu, Estonia",
"Berazino, Belarus",
"Minsk, Belarus",
"Osijek, Croatia",
"Kiihtelysvaara, Finland",
"Sanaiika, Greece",
"Blagoevgrad, Bulgaria",
"Joensuu, Finland",
"Den Burg, Netherlands",
"Deil, Netherlands",
"Drammen, Buskerud , Norway",
"Λάρισα, Greece",
"Lamia, Greece",
"Turku, Finland",
"Vukovar, Croatia",
"Gomel, Belarus",
"Balk, Netherlands",
"Pila, Poland",
"Rethymno, Crete, Greece",
"Salzburg, Austria",
"София, Bulgaria",
"Hulsberg, Netherlands",
"Karditsa, Greece",
"Volos, Greece",
"Delden, Netherlands",
"Ath, Belgium",
"Wiekevorst, Belgium",
"Corfu, Greece",
"Tórshavn, Faroe Islands",
"Mojkovac, Montenegro",
"Amsterdam, Netherlands",
"Riga, Latvia",
"Tournai, Belgium",
"Oulu, Finland",
"Güzelyurt, Cyprus",
"Charleroi, Belgium",
"Copenhagen, Denmark",
"Nicosia, Cyprus",
"Tripoli, Greece",
"Yerevan, Armenia",
"Kalamata, Greece",
"Hameenkyro, Finland",
"Valkenswaard, Netherlands",
"Vlore, Albania",
"Reykjavík, Iceland",
"Tampere, Finland",
"Zlín, Czech Republic",
"Ostroleka, Poland",
"Montana, Bulgaria",
"Brugelette, Belgium",
"Hollola, Finland",
"Langa, Denmark",
"Tirana, Albania",
"Helsinki, Finland",
"Gniezno, Poland",
"Lida, Belarus",
"Den Bosch, Netherlands",
"Hilversum, Netherlands",
"Zagreb, Croatia",
"Prague, Czech Republic",
"Svendborg, Denmark",
"Smilde, Netherlands",
"София, Bulgaria",
"Eerbeek, Netherlands",
"Ptolemaida, Greece",
"Plock, Poland",
"Den Haag, Netherlands",
"Bakar, Croatia",
"PREVEZA, Greece",
"Ghent, Belgium",
"Hardenberg, Netherlands",
"Łódź, Poland",
"Nicosia, Cyprus",
"Gronsveld, Netherlands",
"Nowy Sacz, Poland",
"Corfu, Greece",
"Gomel, Belarus",
"Tábor, Czech Republic",
"Linz, Austria",
"Sliedrecht, Netherlands",
"Šiauliai, Lithuania",
"Haapsalu, Estonia",
"Narva, Narva, Estonia",
"Yerevan, Yerevan, Armenia",
"Hilversum, Netherlands",
"Kukës, Albania",
"Sarande, Albania",
"Nicosia, Cyprus",
"Narva, Estonia",
"Racibórz, Poland",
"Linnamae, Estonia",
"Tarnów, Poland",
"Liberec, Czech Republic",
"Brussels, Belgium",
"Elassóna, Greece",
"Copenhagen, Denmark",
"Warszawa, Poland",
"Tirana, Albania",
"Kodra, Albania",
"Semmering, Niederosterreich, Austria",
"Struga, Macedonia",
"Prilep, Macedonia",
"Breezand, Netherlands",
"Samos, Greece",
"Gorzow, Poland",
"Lappeenranta, Finland",
"Wrocław, Poland",
"Paola, Malta",
"Ringsted, Denmark",
"Liberec, Czech Republic",
"Xanthi, Greece",
"Dugo Selo Lasinjsko, Croatia",
"Victoria, Malta",
"Sliven, Bulgaria",
"Brussels, Belgium",
"Marijampole, Marijampole, Lithuania",
"Brcko, Bosnia and Herzegovina",
"Ouddorp, Netherlands",
"Graz, Austria",
"Vilnius, Lithuania",
"Monte-Carlo, Monaco",
"Agrinio, Greece",
"Jevnaker, Oppland , Norway",
"Tournai, Belgium",
"Lochem, Netherlands",
"Aghios Nikolaos, Greece",
"Venray, Netherlands",
"Stavanger, Norway",
"Ridderkerk, Netherlands",
"Raalte, Netherlands",
"Rhodes, Greece",
"Oulu, Finland",
"Unterach, Oberosterreich, Austria",
"Yerevan, Armenia",
"Tampere, Finland",
"Andorra la Vella, Andorra",
"Warszawa, Poland",
"Morag, Poland",
"Namur, Belgium",
"Amfissa, Greece",
"Louvain-la-Neuve, Belgium",
"Pula, Croatia",
"Kozani, Greece",
"Patras, Greece",
"Zagreb, Croatia",
"Šiauliai, Lithuania",
"Hilversum, Netherlands",
"Warszawa, Poland",
"Kraków, Poland",
"Jelenia Góra, Poland",
"Kos, Greece",
"Ruse, Bulgaria",
"Heraklion, Greece",
"Helsinki, Finland",
"Varna, Bulgaria",
"Ter Aar, Netherlands",
"Plzeň, Czech Republic",
"Wien, Austria",
"Tubize, Belgium",
"Utrecht, Netherlands",
"Hobro, Denmark",
"Nový Jičín, Czech Republic",
"Klagenfurt, Carinthia, Austria",
"Harlingen, Netherlands",
"Białystok, Poland",
"Petrov, Czech Republic",
"Oslo, Norway",
"Eindhoven, Netherlands",
"Plovdiv, Bulgaria",
"Rhodes, Greece",
"Innsbruck, Austria",
"Võru, Voru, Estonia",
"Wien, Austria",
"Bergen, Norway",
"Hollola, Finland",
"Namur, Belgium",
"København, Denmark",
"Kuressaare, Saaremaa, Estonia",
"Thrapsanon, Greece",
"София, Bulgaria",
"Sisak, Croatia",
"Tampere, Finland",
"Marsa, Malta",
"Baku, Azerbaijan",
"Tirana, Albania",
"Chisinau, Moldova",
"Monaco, Monaco",
"Brest, Belarus",
"Zeist, Netherlands",
"Samos, Greece",
"Oslo, Norway",
"Schoten, Belgium",
"Tbilisi, Georgia",
"Kalymnos, Greece",
"København, Denmark",
"Tallinn, Estonia",
"Paide, Estonia",
"Loon op Zand, Netherlands",
"Turku, Finland",
"Wrocław, Poland",
"Maastricht, Netherlands",
"Klaipeda, Lithuania",
"Tallinn, Estonia",
"Eurajoki, Finland",
"Baku, Azerbaijan",
"Osijek, Croatia",
"Antwerpen, Belgium",
"Hodonín, Czech Republic",
"Pärnu, Estonia",
"Gdańsk, Poland",
"Menaldum, Netherlands",
"Gostivar, Macedonia",
"Gennep, Netherlands",
"Tampere, Finland",
"Patras, Greece",
"Dalfsen, Netherlands",
"Pogradec, Albania",
"Vrazici, Bosnia and Herzegovina",
"Amaliada, Greece",
"Loon op Zand, Netherlands",
"Tirana, Albania",
"Hilversum, Netherlands",
"Bruxelles, Belgium",
"Oostzaan, Netherlands",
"Rotterdam, Netherlands",
"Gharghur, Malta",
"Yevlakh, Azerbaijan",
"Salzburg, Austria",
"Tallinn, Estonia",
"Tomislavgrad, Bosnia and Herzegovina",
"Kutno, Poland",
"Emmen, Netherlands",
"Zugdidi, Georgia",
"Nykobing Sjaelland, Denmark",
"Bijeljina, Bosnia and Herzegovina",
"Kraljevica, Croatia",
"Riga, Latvia",
"Chojnice, Poland",
"Uithoorn, Netherlands",
"Hulsberg, Netherlands",
"Vinkovci, Croatia",
"Khania, Greece",
"Amersfoort, Netherlands",
"Urk, Netherlands",
"Gabrovo, Bulgaria",
"Enschede, Netherlands",
"Jesenik , Czech Republic",
"Puttershoek, Netherlands",
"Sarajevo, Bosnia and Herzegovina",
"Chisinau, Moldova",
"Zagreb, Croatia",
"Kuopio, Finland",
"Ostrava, Czech Republic",
"Wrocław, Poland",
"Warszawa, Poland",
"Stjordalshalsen, Norway",
"Λάρισα, Greece",
"Zagreb, Croatia",
"Pula, Croatia",
"Poznan, Poland",
"Estinnes-au-Mont, Belgium",
"Palade, Estonia",
"Kalampaka, Greece",
"Liège, Belgium",
"Turnhout, Belgium",
"Valasske Mezirici, Czech Republic",
"Tirana, Albania",
"Vienna, Austria",
"Sofija, Bulgaria",
"Gdańsk, Poland",
"Ostrava, Czech Republic",
"Zagreb, Croatia",
"Ilawa, Poland",
"Ústí nad Labem, Czech Republic",
"Λάρισα, Greece",
"Riga, Latvia",
"Katowice, Poland",
"Enschede, Netherlands",
"Denekamp, Netherlands",
"Olsztyn, Poland",
"Tartu, Estonia",
"Hilversum, Netherlands",
"Viljandi, Estonia",
"Czestochowa, Poland",
"Nicosia, Cyprus",
"Gorzow Slaski, Poland",
"Amfilochia, Greece",
"Alkmaar, Netherlands",
"Kielce, Poland",
"Praha, Czech Republic",
"Amsterdam, Netherlands",
"Riga, Latvia",
"Blagoevgrad, Bulgaria",
"Eurajoki, Finland",
"Tripoli, Greece",
"Vilnius, Lithuania",
"Bloemendaal, Netherlands",
"Chios, Greece",
"Charleroi, Belgium",
"Kuressaare, Estonia",
"Patras, Greece",
"Belchatow, Poland",
"Tartu, Estonia",
"Sveta Nedjelja, Croatia",
"Izegem, Belgium",
"Telavi, Georgia",
"Osijek, Croatia",
"Eupen, Belgium",
"Ahoinen, Finland",
"Landsmeer, Netherlands",
"Gomel, Gomel Oblast , Belarus",
"Riga, Latvia",
"Zeddam, Netherlands",
"Oslo, Norway",
"Otepää, Voru, Estonia",
"Elsinore, Denmark",
"Cetinje, Montenegro",
"Graz, Austria",
"Ignalina, Ignalina, Lithuania",
"Skardet, Troms, Norway",
"Koeru, Estonia",
"Vitebsk, Belarus",
"Hilversum, Netherlands",
"Achthuizen, Netherlands",
"Leszno, Poland",
"Eibergen, Netherlands",
"Odzak, Bosnia and Herzegovina",
"Hollola, Finland",
"Kortrijk, Belgium",
"Ioannina, Greece",
"Uden, Netherlands",
"Eurajoki, Finland",
"Rauma, Finland",
"Nicosia, Cyprus",
"Homyel, Belarus",
"Tirana, Albania",
"Novy Jicin, Czech Republic",
"Symi, Greece",
"Ath, Belgium",
"Zadar, Croatia",
"Roosendaal, Netherlands",
"Turku, Finland",
"Struga, Macedonia",
"Narva, Narva, Estonia",
"Grodno, Grodno Region, Belarus",
"Ermelo, Netherlands",
"Kraków, Poland",
"Kaarina, Finland",
"Liège, Belgium",
"Gorzow Slaski, Poland",
"Brno, Czech Republic",
"Malbork, Poland",
"Liepaja, Latvia",
"Minsk, Belarus",
"Lappeenranta, Finland",
"Espoo, Finland",
"Den Helder, Netherlands",
"Korce, Albania",
"Froland, Aust-Agder , Norway",
"Praha, Czech Republic",
"Kortrijk, Belgium",
"Bijeljina, Bosnia and Herzegovina",
"Diemen, Netherlands",
"Chisinau, Moldova",
"Hilversum, Netherlands",
"Oslo, Norway",
"Bydgoszcz, Poland",
"Lamia, Greece",
"Smilde, Netherlands",
"Nicosia, Cyprus",
"Utena, Lithuania",
"Ilok, Croatia",
"Lublin, Poland",
"Velika Gorica, Croatia",
"Vilnius, Lithuania",
"Tallinn, Estonia",
"Agrinio, Greece",
"Rotterdam, Netherlands",
"Kotka, Finland",
"Mierlo, Netherlands",
"Volos, Greece",
"Jumet, Belgium",
"Koprivnica, Croatia",
"Kumanovo, Macedonia",
"Varaždin, Croatia",
"Ghent, Belgium",
"Montfoort, Netherlands",
"Bydgoszcz, Poland",
"Suwalki, Poland",
"Arendal, Norway",
"Rødovre, Denmark",
"Bender, Transnistria, Moldova",
"Ivanec, Croatia",
"София, Bulgaria",
"Roelofarendsveen, Netherlands",
"Corfu, Greece",
"Corfu, Greece",
"Praha, Czech Republic",
"Loon op Zand, Netherlands",
"Patras, Greece",
"Helsinki, Finland",
"Vage, Oppland , Norway",
"Arnhem, Netherlands",
"Geleen, Netherlands",
"Bad Aussee, Austria",
"Huy, Belgium",
"Donji Miholjac, Croatia",
"Iraklion, Greece",
"Alexandroupoli, Greece",
"Vilnius, Lithuania",
"Smilde, Netherlands",
"Torun, Poland",
"Poznan, Poland",
"Preveza, Greece",
"Bruck an der Mur, Styria, Austria",
"Ham, Belgium",
"Chisinau, Moldova",
"Srebrenik, Bosnia and Herzegovina",
"Zagreb, Croatia",
"Silistra, Bulgaria",
"Sneek, Netherlands",
"Trutnov, Czech Republic",
"Antwerp, Belgium",
"Ugchelen, Netherlands",
"Leiderdorp, Netherlands",
"Praha, Czech Republic",
"Hämeenlinna, Finland",
"Zuidwolde, Netherlands",
"Tirana, Albania",
"Olomouc, Czech Republic",
"Kuressaare, Estonia",
"Livadia, Greece",
"Mostar, Bosnia and Herzegovina",
"Gramsbergen, Netherlands",
"Moravska Trebova, Czech Republic",
"Heraklion, Greece",
"Tampere, Finland",
"Horst, Netherlands",
"Kozani, Greece",
"Nafplion, Greece",
"Joutseno, Finland",
"Lahti, Finland",
"Nysa, Poland",
"Zevenaar, Netherlands",
"Cospicua, Malta",
"Chisinau, Moldova",
"Κομοτηνή, Greece",
"Kuopio, Finland",
"Sant Joan de les Abadesses, Andorra",
"Kepno, Poland",
"Taurage, Lithuania",
"Ishull-Lezhe, Albania",
"Orhei, Moldova",
"Wladyslawowo, Poland",
"Katowice, Poland",
"Lienz, Tyrol, Austria",
"Lokeren, Belgium",
"Emmen, Netherlands",
"Sint-Denijs-Westrem, Belgium",
"Bydgoszcz, Poland",
"Viesite, Latvia",
"Czestochowa, Poland",
"Narva, Narva, Estonia",
"Trikala, Greece",
"Liezen, Austria",
"Den Bosch, Netherlands",
"Liège, Belgium",
"Nicosia, Cyprus",
"Tbilisi, Georgia",
"Sarajevo, Bosnia and Herzegovina",
"Grodno, Belarus",
"Berghem, Netherlands",
"Graz, Austria",
"Oosterhout, Netherlands",
"Pardubice, Czech Republic",
"Smilde, Netherlands",
"Riga, LV, Latvia",
"Bihac, Bosnia and Herzegovina",
"Białystok, Poland",
"Nicosia, Cyprus",
"Radom, Poland",
"Jyväskylä, Finland",
"Hämeenlinna, Finland",
"Nivelles, Belgium",
"Alexandroupolis, Greece",
"Monaco, Monaco",
"Smilde, Netherlands",
"Florina, Greece",
"Unzmarkt, Austria",
"Breda, Netherlands",
"Mijdrecht, Netherlands",
"Limassol, Cyprus",
"København, Denmark",
"Veles, Macedonia",
"Praha, Czech Republic",
"Juragiai, Kaunas, Lithuania",
"Jyväskylä, Finland",
"Paphos, Cyprus",
"Nowy Sacz, Poland",
"Koszalin, Poland",
"Porec, Croatia",
"København, Denmark",
"Heraklion, Greece",
"Zoersel, Belgium",
"Heraklion, Greece",
"Panevežys, Lithuania",
"Kraków, Poland",
"Rabat, Malta",
"Kosove, Albania",
"Namur, Belgium",
"Kocani, Macedonia",
"Koeru, Estonia",
"Blagoevgrad, Bulgaria",
"Burgas, Bulgaria",
"Eindhoven, Netherlands",
"Kavala, Greece",
"Gosau, Austria",
"Agrinio, Greece",
"Ioannina, Greece",
"Tallinn, Estonia",
"Joensuu, Finland",
"Haapsalu, Estonia",
"Κόρινθος, Greece",
"Naaldwijk, Netherlands",
"Sarajevo, Bosnia and Herzegovina",
"Serres, Greece",
"Stara Zagora, Bulgaria",
"Staden, Belgium",
"Heemskerk, Netherlands",
"Diemen, Netherlands",
"Tofte, Norway",
"Kladno, Czech Republic",
"Copenhagen, Denmark",
"Paide, Estonia",
"Cheb, Czech Republic",
"Tilburg, Netherlands",
"Plzeň, Czech Republic",
"Brussels, Belgium",
"Charleroi, Belgium",
"Kuopio, Finland",
"Skopje, Macedonia",
"Baku, Azerbaijan",
"Chalkida, Greece",
"Ittervoort, Netherlands",
"Banja Luka, Bosnia and Herzegovina",
"Hradcany, Czech Republic",
"Wavre, Belgium",
"Victoria, Malta",
"Lopik, Netherlands",
"Corinth, Greece",
"Ioannina, Greece",
"Tallinn, Estonia",
"Amsterdam, Netherlands",
"Split, Croatia",
"Minsk, Belarus",
"Ludbreg, Croatia",
"Szczecin, Poland",
"Tamow, Poland",
"Leeuwarden, Netherlands",
"Zielona Gora, Poland",
"Rapla, Estonia",
"Yerevan, Armenia",
"Bruxelles, Belgium",
"Bitola, Macedonia",
"Reykjavík, Iceland",
"Oslo, Norway",
"Split, Croatia",
"Poznan, Poland",
"Steinsdalen, Sør-Trøndelag , Norway",
"Den Bosch, Netherlands",
"Rzeszów, Poland",
"Nesodden, Norway",
"Zenica, Bosnia and Herzegovina",
"Nicosia, Cyprus",
"Bansko, Bulgaria",
"Szczecin, Poland",
"Jemiolow, Poland",
"Drama, Greece",
"Pernå, Finland",
"Klaipeda, Klaipeda/Palanga, Lithuania",
"Zlín, Czech Republic",
"Kristiansand, Norway",
"Tallinn, Estonia",
"Swinoujscie, Poland",
"Brussels, Belgium",
"Medernach, Luxembourg",
"Dornbirn, Austria",
"Arta, Greece",
"Oulu, Finland",
"Baarle-Nassau, Netherlands",
"Tournai, Belgium",
"Nicosia, Cyprus",
"Bergen, Hordaland, Norway",
"Tivat, Montenegro",
"Tallinn, Estonia",
"Jyväskylä, Finland",
"Zamosc, Poland",
"Mariager, RE, Denmark",
"Lefkada, Greece",
"Poznan, Poland",
"Antwerp, Belgium",
"Eurajoki, Finland",
"Bruxelles, Belgium",
"Rovaniemi, Finland",
"Warszawa, Poland",
"Aarhus, Denmark",
"Sarajevo, Bosnia and Herzegovina",
"Olsztyn, Poland",
"Hilvarenbeek, NB, Netherlands",
"Spittal, Austria",
"Xanthi, Greece",
"Volos, Greece",
"Oslo, Oslo, Norway",
"Skomielna Czarna, Poland",
"Eurajoki, Finland",
"Silkeborg, Denmark",
"Gdańsk, Poland",
"Tallinn, Estonia",
"Tuzla, Bosnia and Herzegovina",
"Borovets, Bulgaria",
"Białystok, Poland",
"Westerlo, Belgium",
"Graz, Styria, Austria",
"Piekary, Poland",
"Podgorica, Montenegro",
"Tirana, Albania",
"Skierniewice, Poland",
"Viljandi, Estonia",
"Innsbruck, Austria",
"Kalisz, Poland",
"Lamia, Greece",
"Samos, Greece",
"Jyväskylä, Finland",
"Trondheim, Sr-Trndelag County, Norway",
"Rzeszów, Poland",
"Heraklion, Greece",
"Zamosc, Poland",
"Chisinau, Moldova",
"Vitebsk, Vitebsk Oblast, Belarus",
"Zielona Góra, Poland",
"Riga, Riga, Latvia",
"Reykjavík, Iceland",
"Srpska, Bosnia and Herzegovina",
"Kaunas, Lithuania",
"Zagreb, Croatia",
"Zierikzee, Netherlands",
"Limassol, Cyprus",
"Hoogezand, Netherlands",
"Rhodes, Greece",
"Balzan, Malta",
"Hellevoetsluis, Netherlands",
"Eindhoven, Netherlands",
"Gorzow Slaski, Poland",
"Struga, Macedonia",
"Amsterdam, Netherlands",
"Jihlava, Czech Republic",
"Aytos, Bulgaria",
"Cakovec, Croatia",
"Inowroclaw, Poland",
"Smilde, Netherlands",
"Sheki, Azerbaijan",
"Võru, Estonia",
"Minsk, Belarus",
"Sint-Pieters-Leeuw, Belgium",
"Vught, Netherlands",
"Belogradchik, Bulgaria",
"Minsk, Belarus",
"Gdynia, Poland",
"Geel, Belgium",
"Bitola, Macedonia",
"Deventer, Netherlands",
"Wrocław, Poland",
"Jõhvi, Narva, Estonia",
"Virovitica, Croatia",
"Tbilisi, Georgia",
"Tampere, Finland",
"Oulu, Finland",
"Riga, Latvia",
"Kuopio, Finland",
"Neerpelt, Belgium",
"Slunj, Croatia",
"Frederiksvaerk, Denmark",
"Delnice, Croatia",
"Minsk, Belarus",
"Tienen, Belgium",
"Oslo, Norway",
"Zvornik, Bosnia and Herzegovina",
"Hoorn, Netherlands",
"Larnaca, Cyprus",
"Bydgoszcz, Poland",
"Rijeka, Croatia",
"Turku, Finland",
"København, Denmark",
"Aytos, Bulgaria",
"Roosendaal, Netherlands",
"Antwerp, Belgium",
"Varaždin, Croatia",
"Orasje, Bosnia and Herzegovina",
"Heraklion, Greece",
"Smilde, Netherlands",
"Hengelo, Netherlands",
"Etten, Netherlands",
"Tórshavn, Faroe Islands",
"Uitgeest, Netherlands",
"Wielun, Poland",
"Sigulda, Latvia",
"Schiedam, Netherlands",
"Burgas, Bulgaria",
"Wellen, Belgium",
"Liège, Belgium",
"Antwerpen, Belgium",
"Valgjarve, Voru, Estonia",
"Brussels, Belgium",
"Weert, Netherlands",
"Ierapetra, Greece",
"Eys, Netherlands",
"Scherpenheuvel, Belgium",
"Hasselt, Belgium",
"Rovaniemi, Finland",
"Zielona Góra, Poland",
"Pyrgos, Greece",
"Slupsk, Poland",
"Corinth, Greece",
"Kielce, Poland",
"Fjerritslev, Denmark",
"Orestias, Greece",
"Kaunas, Lithuania",
"Koeru, Estonia",
"Kabel, Netherlands",
"Nuland, Netherlands",
"Daugavpils, Latvia",
"Trebinje, Bosnia and Herzegovina",
"Komotini, Greece",
"Pärnu, Parnu, Estonia",
"Budweis, Czech Republic",
"Leuven, Belgium",
"Copenhagen, Denmark",
"Turku, Finland",
"Zamosc, Poland",
"Wien, Austria",
"Chania, Greece",
"Kozani, Greece",
"Tuzla, Bosnia and Herzegovina",
"Valmiera, Latvia",
"Peladhi, Albania",
"Zwolle, Netherlands",
"Brest, Brest Oblast, Belarus",
"Kraków, Poland",
"Vilnius, Lithuania",
"Prague, Czech Republic",
"Luxembourg, Luxembourg",
"Egem, Belgium",
"Chisinau, Moldova",
"Λάρισα, Greece",
"Fier, Albania",
"Novska, Croatia",
"Lublin, Poland",
"De Lutte, Netherlands",
"Hrodna, Belarus",
"Tirana, Albania",
"Babruysk, Belarus",
"Vriezenveen, Netherlands",
"Bad Ischl, Austria",
"Alexandroupolis, Greece",
"Vilnius, Lithuania",
"Dudelange, Luxembourg",
"Yerevan, Armenia",
"Mierlo, Netherlands",
"Sveti Ivan Zelina, Croatia",
"Sevlievo, Bulgaria",
"Ljubic, Bosnia and Herzegovina",
"Gyumri, Armenia",
"Sarajevo, Bosnia and Herzegovina",
"Froland, Norway",
"Radenthein, Carinthia, Austria",
"Amsterdam, Netherlands",
"Varna, Bulgaria",
"Klaipeda, Lithuania",
"Poznan, Poland",
"Olomouc, Czech Republic",
"Karpenision, Greece",
"Aalborg, Denmark",
"Olomouc, Czech Republic",
"Jodoigne, Belgium",
"Larisa, Greece",
"Kavala, Greece",
"Biržai, Lithuania",
"Zakynthos, Greece",
"Chalkis, Greece",
"Pirgos, Greece",
"Westerlo, Belgium",
"Egem, Belgium",
"Tbilisi, Georgia",
"Kedzierzyn-Kozle, Poland",
"Xanthi, Greece",
"Meerssen, Netherlands",
"Rijnsburg, Netherlands",
"Tjerkgaast, Netherlands",
"Trondheim, Norway",
"Brussels, Belgium",
"Nijmegen, Netherlands",
"Amstelveen, Netherlands",
"Lahti, Finland",
"Kazbegi, Georgia",
"Paide, Estonia",
"Valasske Mezirici, Czech Republic",
"Amsterdam, Netherlands",
"Wrocław, Poland",
"Weert, Netherlands",
"Kos, Greece",
"Emmen, Netherlands",
"Mostar, Bosnia and Herzegovina",
"Bjelovar, Croatia",
"Legnica, Poland",
"Faxe, Denmark",
"Kalampaka, Greece",
"Rovaniemi, Finland",
"Rethymnon, Greece",
"Pyrgos, Greece",
"Chania, Greece",
"Silkeborg, Denmark",
"Cesis, Latvia",
"Lopik, Netherlands",
"Tirana, Albania",
"Argostoli, Κεφαλονιά, Greece",
"Warszawa, Poland",
"Heraklion, Greece",
"Goes, Netherlands",
"Sandzak, Bosnia and Herzegovina",
"Patras, Greece",
"Altforst, Netherlands",
"Dubasari, Moldova",
"Fraire, Belgium",
"Warszawa, Poland",
"Tallinn, Tallinn, Estonia",
"Sudislav nad Orlici, Czech Republic",
"Bergen, Norway",
"Sofia, Bulgaria",
"Storsand, Troms, Norway",
"Kuopio, Finland",
"Hämeenlinna, Finland",
"Klatovy, Czech Republic",
"Tartu, Estonia",
"Białystok, Poland",
"Brussels, Belgium",
"Emmen, Netherlands",
"Larnaca, Larnaca, Cyprus",
"Tilburg, Netherlands",
"Λάρισα, Greece",
"Liberec, Czech Republic",
"Charleroi, Belgium",
"Brzesko, Warsaw Warszawa, Poland",
"Kumanovo, Macedonia",
"Dronninglund, Denmark",
"Sparti, Greece",
"Alkmaar, Netherlands",
"Oulu, Finland",
"Daugavpils, Latvia",
"Lyngdal, Norway",
"Alytus, Alytus, Lithuania",
"Bielsko-Biala, Poland",
"София, Bulgaria",
"Katwijk, Netherlands",
"Rovaniemi, Finland",
"Warszawa, Poland",
"Houdeng-Aimeries, Belgium",
"Stevoort, Belgium",
"Kraków, Poland",
"Rokiškis, Lithuania",
"Megen, Netherlands",
"Vilnius, Lithuania",
"Warszawa, Poland",
"Helsinki, Finland",
"Rapla, Estonia",
"Argos, Greece",
"Goor, Netherlands",
"Hulsberg, Netherlands",
"Ede, Netherlands",
"Panaritis, Greece",
"Goes, Netherlands",
"Schijndel, Netherlands",
"Luxembourg, Luxembourg",
"Dedemsvaart, Netherlands",
"Tampere, Finland",
"Łódź, Poland",
"Tartu, Estonia",
"Ruinen, Netherlands",
"Kirchdorf an der Krems, Austria",
"Cesky Krumlov, Czech Republic",
"Shumen, Bulgaria",
"Chisinau, Moldova",
"Bruxelles, Belgium",
"Tetovo, Macedonia",
"Tetovo, Macedonia",
"Corinth, Greece",
"Den Burg, Netherlands",
"Praha, Czech Republic",
"Chania, Greece",
"Sint-Niklaas, Belgium",
"Klaksvík, Faroe Islands",
"Eupen, Belgium",
"Pleven, Bulgaria",
"Otocac, Croatia",
"Melhus, Norway",
"Hradec Králové, Czech Republic",
"Nicosia, Cyprus",
"Heraklion, Greece",
"Steyr, Austria",
"Jekabpils, Latvia",
"Usti nad Labem, Czech Republic",
"Salzburg, Austria",
"Hämeenlinna, Finland",
"Limassol, Cyprus",
"Pelekanadha, Greece",
"Stip, Macedonia",
"Częstochowa, Poland",
"Tampere, Finland",
"Hoogeveen, Netherlands",
"Muntendam, Netherlands",
"Aghios Nikolaos, Greece",
"Reykjavík, Iceland",
"Den Helder, Netherlands",
"Rotterdam, Netherlands",
"Medemblik, Netherlands",
"Praha, Czech Republic",
"Jyväskylä, Finland",
"Tartu, Estonia",
"Podlasie, Poland",
"Spijkenisse, Netherlands",
"Chania, Greece",
"Aste, Estonia",
"Rethymno, Greece",
"Kalisz, Poland",
"Nicosia, Cyprus",
"Patras, Greece",
"Meppel, Netherlands",
"Olomouc, Czech Republic",
"Zandvoort, Netherlands",
"Innsbruck, Tyrol, Austria",
"Sparti, Greece",
"Beusichem, Netherlands",
"Lahti, Finland",
"Klaipeda, Lithuania",
"Juelsminde, Denmark",
"Kaunas, Lithuania",
"Vlore, Albania",
"Janja, Bosnia and Herzegovina",
"Den Helder, Netherlands",
"Weurt, Netherlands",
"Hundested, Denmark",
"Iraklion, Greece",
"Jyväskylä, Finland",
"Zagreb, Croatia",
"Berane, Montenegro",
"Baku, Azerbaijan",
"Megen, Netherlands",
"Mladá Boleslav, Czech Republic",
"Kuldiga, Latvia",
"Telšiai, Lithuania",
"Corinth, Greece",
"Agios Nikolaos, Greece",
"Bergen, Norway",
"Przemysl, Poland",
"Teresin, Poland",
"Lochem, Netherlands",
"Siedlce, Poland",
"Kutno, Poland",
"Hilversum, Netherlands",
"Tirana, Albania",
"Wavre, Belgium",
"Genk, Belgium",
"Vlore, Albania",
"Pärnu, Parnu, Estonia",
"Meseleroi, Greece",
"Ústí nad Labem, Czech Republic",
"Amersfoort, Netherlands",
"Chios, Greece",
"Vitez, Bosnia and Herzegovina",
"Tammela, Finland",
"Zagan, Poland",
"Jirnsum, Netherlands",
"Rovinj, Croatia",
"Deinze, Belgium",
"Megen, Netherlands",
"Lovech, Bulgaria",
"Jyväskylä, Finland",
"Nicosia, Nicosia, Cyprus",
"Rotterdam, Netherlands",
"Haarlem, Netherlands",
"Yerevan, Armenia",
"St. Julian's, Malta",
"Vejle, Denmark",
"Kupres, Bosnia and Herzegovina",
"Salzburg, Austria",
"Tremelo, Belgium",
"Valasske Mezirici, Czech Republic",
"Gracac, Croatia",
"Polten, Austria",
"Bielsko-Biala, Poland",
"Bijeljina, Bosnia and Herzegovina",
"Sukhumi,  , Georgia",
"Amsterdam, Netherlands",
"Plovdiv, Bulgaria",
"Nijmegen, Netherlands",
"Culemborg, Netherlands",
"Eurajoki, Finland",
"Gomel, Belarus",
"Xanthi, Greece",
"Yerevan, Armenia",
"Hank, Netherlands",
"Chania, Greece",
"Genk, Belgium",
"Veenendaal, Netherlands",
"Wrocław, Poland",
"Paphos, Cyprus",
"Helsinki, Finland",
"Kraków, Poland",
"Haren, Netherlands",
"Lefkada, Greece",
"Kavarna, Bulgaria",
"Landgraaf, Netherlands",
"Wijchen, Netherlands",
"Vaduz, Liechtenstein",
"Sofia, Bulgaria",
"Nijmegen, Netherlands",
"Pärnu, Parnu, Estonia",
"Oslo, Norway",
"Liepaja, Latvia",
"Egem, Belgium",
"Plunge, Lithuania",
"Oulu, Finland",
"Lamia, Greece",
"Zagreb, Croatia",
"Chania, Greece",
"Prague, Prague, Czech Republic",
"Warszawa, Poland",
"Heraklion, Greece",
"Skopje, Macedonia",
"Rzeszów, Poland",
"Hollola, Finland",
"Antwerp, Belgium",
"Marijampole, Marijampole, Lithuania",
"Sofia, Sofia, Bulgaria",
"Emmeloord, Netherlands",
"Rethymno, Greece",
"Klagenfurt, Austria",
"Agrinio, Greece",
"Łódź, Poland",
"Białystok, Poland",
"Naxxar, Malta",
"Busovaca, Bosnia and Herzegovina",
"Charleroi, Belgium",
"Markelo, Netherlands",
"Smolyan, Bulgaria",
"Rhodes, Greece",
"Ayia Napa, Cyprus",
"Pirgos, Greece",
"Riga, Latvia",
"Klaipeda, Lithuania",
"Korgessaare, Estonia",
"Volos, Greece",
"Juragiai, Kaunas, Lithuania",
"Bruxelles, Belgium",
"Tammela, Finland",
"Volos, Greece",
"Opava, Czech Republic",
"Leuven, Belgium",
"Λάρισα, Greece",
"Bruxelles, Belgium",
"Pazardzhik, Bulgaria",
"Viesite, Latvia",
"Maastricht, Netherlands",
"Farsala, Greece",
"Alytus, Alytus, Lithuania",
"Riga, Latvia",
"Tartu, Estonia",
"Helsinki, Finland",
"Bad Aussee, Styria, Austria",
"Daugavpils, Riga, Latvia",
"Flobecq, Belgium",
"Katowice, Poland",
"Randers, Denmark",
"Markelo, Netherlands",
"Wloclawek, Poland",
"Homyel, Belarus",
"Tiraspol, Moldova",
"Lamia, Greece",
"Katolin, Poland",
"Frameries, Belgium",
"Nootdorp, Netherlands",
"Trutnov, Czech Republic",
"Delft, Netherlands",
"Bergen, Norway",
"Kozani, Greece",
"Landgraaf, Netherlands",
"Stavanger, Norway",
"Mierlo, Netherlands",
"Warszawa, Poland",
"Brest, Belarus",
"Assen, Netherlands",
"Copenhagen, DK, Denmark",
"Srpska, Bosnia and Herzegovina",
"Kolinkyla, Finland",
"Elbasan, Albania",
"Gorzow Wielkopolski, Poland",
"Mol, Belgium",
"Smilde, Netherlands",
"Rovaniemi, Finland",
"Zagreb, Croatia",
"Veliko Tarnovo, Bulgaria",
"Jyväskylä, Finland",
"Braslaw, Belarus",
"Kozani, Greece",
"Rybnitsa, Transnistria, Moldova",
"Nachod, Czech Republic",
"Malmedy, Belgium",
"Oslo, Norway",
"Gdańsk, Poland",
"Komotini, Greece",
"Ostrava, Czech Republic",
"Camenca, Moldova",
"Reykjavík, Iceland",
"Amdal, Aust-Agder , Norway",
"Fgura, Malta",
"Brno, Czech Republic",
"Schoten, Belgium",
"Viljandi, Estonia",
"Opole, Poland",
"Tallinn, Estonia",
"Geldrop, Netherlands",
"Scharding, Oberosterreich, Austria",
"Kielce, Poland",
"Boxmeer, Netherlands",
"Ostrów Wielkopolski, Poland",
"Markelo, Netherlands",
"Praha, Czech Republic",
"Ganshoren, Belgium",
"Hradec Králové, Czech Republic",
"Hengelo, Netherlands",
"Zagan, Poland",
"Gdańsk, Poland",
"Elblag, Poland",
"Posusje, Bosnia and Herzegovina",
"Porvoo, Finland",
"Baku, Azerbaijan",
"Rotterdam, Netherlands",
"Rotterdam, Netherlands",
"Warszawa, Poland",
"Poznan, Poland",
"Stavanger, Rogaland County, Norway",
"ARIS, Greece",
"Kaunas, Lithuania",
"Sarajevo, MD, Bosnia and Herzegovina",
"Mažeikiai, Lithuania",
"Hodonín, Czech Republic",
"Kerkenveld, Netherlands",
"Slavonski Brod, Croatia",
"Vitebsk, Vitebsk Oblast , Belarus",
"Kozani, Greece",
"Ioannina, Greece",
"Tallinn, Tallinn, Estonia",
"Osijek, Croatia",
"Serres, Greece",
"Oulu, Finland",
"Egem, Belgium",
"Šibenik, Croatia",
"Agora, Greece",
"Kraków, Poland",
"Rovaniemi, Finland",
"Stavanger, Norway",
"Bijeljina, Bosnia and Herzegovina",
"Bihac, Bosnia and Herzegovina",
"Radom, Poland",
"Καβάλα, Greece",
"Koli, Finland",
"Pabianice, Poland",
"Puhja, Estonia",
"Anykšciai, Lithuania",
"Baku, Azerbaijan",
"Zwettl an der Rodl, Austria",
"Friesland, Netherlands",
"Blagoevgrad, Bulgaria",
"Bruxelles, Belgium",
"Goirle, Netherlands",
"Tirana, Albania",
"Bielsko-Biala, Poland",
"Brussels, Belgium",
"Lamia, Greece",
"Ioannina, Greece",
"Ciechanów, Poland",
"Salte, Norway",
"Kaunas, Lithuania",
"Heraklion, Greece",
"Corfu, Greece",
"Liège, Belgium",
"Rhodes, Greece",
"Emmen, Netherlands",
"Dobrich, Bulgaria",
"Famagusta, Cyprus",
"Varnsdorf, Czech Republic",
"Olomouc, Czech Republic",
"Viljandi, Estonia",
"Tivat, Montenegro",
"Albertslund, Denmark",
"Vienna, Austria",
"Pelplin, Poland",
"Gora, Poland",
"Warszawa, Poland",
"Oslo, Norway",
"Bosanski Novi, Bosnia and Herzegovina",
"Eeklo, Belgium",
"Larnaca, Cyprus",
"Linz, Oberosterreich, Austria",
"Písek, Czech Republic",
"Nicosia, Cyprus",
"Quba, Azerbaijan",
"Rechnitz, Austria",
"Grimstad, Norway",
"Koroivos, Greece",
"Bodegraven, Netherlands",
"Feldkirchen an der Donau, Austria",
"Kyustendil, Bulgaria",
"Kraków, Poland",
"Askim, Norway",
"Vilnius, Lithuania",
"Yläne, Finland",
"Svendborg, Denmark",
"Plzeň, Czech Republic",
"Nicosia, Nicosia, Cyprus",
"Belogradchik, Bulgaria",
"Stargard Szczecinski, Poland",
"Corfu, Greece",
"Ioannina, Greece",
"Zwartsluis, Netherlands",
"Oslo, Oslo, Norway",
"Mierlo, Netherlands",
"Amsterdam, Netherlands",
"Klagenfurt, Austria",
"Amsterdam, Netherlands",
"Vsetin, Czech Republic",
"Ivaylovgrad, Bulgaria",
"Karlovac, Croatia",
"Ilawa, Poland",
"Haugesund, Norway",
"Chabaslar, Greece",
"Struga, Macedonia",
"Dobrich, Bulgaria",
"Anderlues, Belgium",
"Melhus, Norway",
"Tbilisi, GA, Georgia",
"Appelscha, Netherlands",
"Opole, Poland",
"Tervola, Finland",
"Turku, Finland",
"Jajce, Bosnia and Herzegovina",
"Joensuu, Finland",
"Liège, Belgium",
"Trikala, Greece",
"Akureyri, Iceland",
"Liège, Belgium",
"Kardla, Estonia",
"Limassol, Cyprus",
"Hilversum, Netherlands",
"Minsk, Belarus",
"Hapert, Netherlands",
"Sofiya, Bulgaria",
"Kampen, Netherlands",
"Pärnu, Parnu, Estonia",
"Tuzla, Bosnia and Herzegovina",
"Pärnu, Parnu, Estonia",
"Rzeszów, Poland",
"Ylöjärvi, Finland",
"Konitsa, Greece",
"Zwolle, Netherlands",
"Luxembourg, Luxembourg",
"Opole, Poland",
"Yerevan, Armenia",
"Kyustendil, Bulgaria",
"Jokela, Finland",
"Hollola, Finland",
"Praha, Czech Republic",
"Roosendaal, Netherlands",
"Kaunas, Kaunas, Lithuania",
"Tripolis, Greece",
"Λάρισα, Greece",
"Xanthi, Greece",
"Sanok, Poland",
"Eurajoki, Finland",
"Turku, Finland",
"Xaghra, Malta",
"Malden, Netherlands",
"Salzburg, Austria",
"Otepää, Estonia",
"Kavala, Greece",
"София, Bulgaria",
"Plzeň, Czech Republic",
"Kaarina, Finland",
"Panevežys, Lithuania",
"Gdynia, Poland",
"Woudenberg, Netherlands",
"Kavala, Greece",
"Flushing, Netherlands",
"Torsnes, Troms, Norway",
"Lappeenranta, Finland",
"Sippola, Finland",
"Oostham, Belgium",
"Kolobrzeg, Poland",
"Nicosia, Cyprus",
"Yerevan, Armenia",
"Ede, Netherlands",
"Semmering, Austria",
"Brønderslev, Denmark",
"Amsterdam, Netherlands",
"Tuzla, Bosnia and Herzegovina",
"Banja Luka, Bosnia and Herzegovina",
"Best, Netherlands",
"Meulebeke, Belgium",
"Nafplion, Greece",
"Kutaisi, Georgia",
"Nieuwerkerk aan den IJssel, Netherlands",
"Plovdiv, Bulgaria",
"Praha, Czech Republic",
"Ioannina, Greece",
"Łódź, Poland",
"Sazava, Czech Republic",
"Amsterdam, Netherlands",
"Zagreb, Croatia",
"Schiedam, Netherlands",
"Oulu, Finland",
"Loosbroek, Netherlands",
"Smolyan, Bulgaria",
"Mogilev, Belarus",
"Warszawa, Poland",
"Florina, Greece",
"Trogir, Croatia",
"Nieuwegein, Netherlands",
"Koeru, Estonia",
"Korcula, Croatia",
"Zlín, Czech Republic",
"Reykjavík, Iceland",
"Antwerp, Belgium",
"Krestena, Greece",
"Devin, Bulgaria",
"Zakros, Greece",
"Zevenbergen, Netherlands",
"Agrinio, Greece",
"Matulji, Croatia",
"Grodno, Belarus",
"Akrotiri, Cyprus",
"Helsinki, Finland",
"Białystok, Poland",
"Oulu, Finland",
"Minsk, Belarus",
"Tilburg, Netherlands",
"Schoonhoven, Netherlands",
"Veles, Macedonia",
"Corfu, Greece",
"Sarajevo, Bosnia and Herzegovina",
"Praha, Czech Republic",
"Nijmegen, Netherlands",
"Hilversum, Netherlands",
"Zapresic, Croatia",
"Mogilev, Belarus",
"Gent, Belgium",
"Vilnius, Lithuania",
"Heraklion, Greece",
"Rijeka, Croatia",
"Bones, Troms, Norway",
"Mytilini, Greece",
"Kaarina, Finland",
"Poznan, Poland",
"Cakovec, Croatia",
"Middenmeer, Netherlands",
"Varna, Bulgaria",
"Kaunas, Lithuania",
"Helsinki, Finland",
"Sint-Pieters-Leeuw, Belgium",
"Levanger, Norway",
"Nicosia, Cyprus",
"Varna, Bulgaria",
"Riga, Latvia",
"Zakynthos, Greece",
"София, Bulgaria",
"Budejovice, Czech Republic",
"Warszawa, Poland",
"Gevgelija, Macedonia",
"Luxembourg, Luxembourg",
"Wrocław, Poland",
"Nicosia, Cyprus",
"Ylöjärvi, Finland",
"Luqa, Malta",
"Opwijk, Belgium",
"Ptolemaida, Greece",
"Victoria, Malta",
"Horsholm, Denmark",
"Tampere, Finland",
"Ostend, Belgium",
"Herzele, Belgium",
"Gracanica, Bosnia and Herzegovina",
"Vanadzor, Armenia",
"Nieuw-Vennep, Netherlands",
"Sofia, Bulgaria",
"Brussels, Belgium",
"Maarssen, Netherlands",
"Piotrków Trybunalski, Poland",
"Rzeszów, Poland",
"Nicosia, Cyprus",
"Shumen, Bulgaria",
"Tartu, Tartu, Estonia",
"Split, Croatia",
"Elst, Netherlands",
"Krems, Oberosterreich, Austria",
"Sint-Niklaas, Belgium",
"Opole, Poland",
"Amsterdam, Netherlands",
"Tirana, Albania",
"Vienna, Austria",
"Utrecht, Netherlands",
"Grevena, Greece",
"Lyngdal, Aust i Vest-Agder Counties, Norway",
"Hilversum, Netherlands",
"Kalamata, Greece",
"Białystok, Poland",
"Sofia, Bulgaria",
"Praha, Czech Republic",
"Borgloon, Belgium",
"Arnhem, Netherlands",
"Karlovac, Croatia",
"Tirana, Albania",
"Salzburg, Austria",
"Antwerp, Belgium",
"Borne, Netherlands",
"Demation, Greece",
"Diepenbeek, Belgium",
"Vilnius, Lithuania",
"Oulu, Finland",
"Mława, Poland",
"Baku, Azerbaijan",
"Limnos, Greece",
"Qala, Malta",
"Taurage, Lithuania",
"České Budějovice, Czech Republic",
"Zwijndrecht, Netherlands",
"Ivanic-Grad, Zagreb, Croatia",
"Driewegen, Netherlands",
"Patras, Greece",
"Alkmaar, Netherlands",
"Mariazell, Styria, Austria",
"Wijk en Aalburg, Netherlands",
"Vilnius, Lithuania",
"Sint-Niklaas, Belgium",
"Helmond, Netherlands",
"Μυτιλήνη, Greece",
"Eurajoki, Finland",
"Groningen, Netherlands",
"Kaunas, Kaunas, Lithuania",
"Tiraspol, Pridnestrovian Moldavian Republic (Transnistria), Moldova",
"Mechelen, Belgium",
"Horsens, Denmark",
"Rotterdam, Netherlands",
"Λάρισα, Greece",
"Nunspeet, Netherlands",
"Doboj, Bosnia and Herzegovina",
"Wijhe, Netherlands",
"Λάρισα, Greece",
"Hodonín, Czech Republic",
"Hengelo, Netherlands",
"Kaarina, Finland",
"Brugge, Belgium",
"Montana, Bulgaria",
"Aalsmeer, Netherlands",
"Zelhem, Netherlands",
"Wolvega, Netherlands",
"Nijkerk, Netherlands",
"Lomza, Poland",
"Banja Luka, Bosnia and Herzegovina",
"Imst, Austria",
"Frederiksberg, Denmark",
"Stachowice, Poland",
"Patras, Greece",
"Viljandi, Estonia",
"Trondheim, Norway",
"Myadzel, Belarus",
"Bruges, Belgium",
"Samos, Greece",
"Eurajoki, Finland",
"Sint-Pieters-Leeuw, Belgium",
"Sint-Gillis-Waas, Belgium",
"Karlovy Vary, Czech Republic",
"Riga, Latvia",
"Bergen, Hordaland County, Norway",
"Iraklion, Greece",
"Heythuysen, Netherlands",
"Bad Ischl, Oberosterreich, Austria",
"Zwolle, Netherlands",
"Koprivnica, Croatia",
"Tholen, Netherlands",
"Kicevo, Macedonia",
"Amsterdam, Netherlands",
"Silistra, Bulgaria",
"Emmeloord, Netherlands",
"Oulu, Finland",
"Szczecin, Poland",
"Goes, Netherlands",
"Amsterdam, Netherlands",
"Krapina, Croatia",
"Pigadia, Greece",
"Amsterdam, Netherlands",
"Brest, Belarus",
"Vienna, Austria",
"Bar, Montenegro",
"Mandal, Norway",
"Nuenen, Netherlands",
"Lefkada, Greece",
"København, Denmark",
"Iraklion, Greece",
"Aalst, Belgium",
"Valkeakoski, Finland",
"Helsinki, Finland",
"Het Loo, Netherlands",
"Burgas, Bulgaria",
"Burgas, Bulgaria",
"Leuven, Belgium",
"Leidschendam, Netherlands",
"Amersfoort, Netherlands",
"Võru, Voru, Estonia",
"Poznan, Poland",
"Paide, Estonia",
"Lipiany, Poland",
"Hilversum, Netherlands",
"Tirol, Austria",
"Patras, Greece",
"Tammela, Finland",
"Amsterdam, Netherlands",
"Haaksbergen, Netherlands",
"Szczecin, Poland",
"Rijeka, Croatia",
"Briceni, Moldova",
"Gent, Belgium",
"Grodno, Belarus",
"Serres, Greece",
"Rousse, Bulgaria",
"Kielce, Poland",
"Reykjavík, Iceland",
"Ústí nad Labem, Czech Republic",
"Deurne, Netherlands",
"Minsk, Belarus",
"Copenhagen, Denmark",
"Κόρινθος, Greece",
"Tjerkgaast, Netherlands",
"Kraków, Poland",
"Panningen, Netherlands",
"Pilsen, Czech Republic",
"Tampere, Finland",
"Oirschot, Netherlands",
"Schoten, Belgium",
"Korgessaare, Estonia",
"Dakovo, Croatia",
"Helmond, Netherlands",
"Nieuwleusen, Netherlands",
"Sombreffe, Belgium",
"Nicosia, Cyprus",
"Smilde, Netherlands",
"Vlore, Albania",
"Praha, Czech Republic",
"Elburg, Netherlands",
"Ohrid, Macedonia",
"Zwolle, Netherlands",
"Prilep, Macedonia",
"Chania, Greece",
"Sint-Maria-Lierde, Belgium",
"Łódź, Poland",
"Gori, Georgia",
"Wien, Austria",
"Kuopio, Finland",
"Kaarina, Finland",
"Tirana, Albania",
"Kresna, Bulgaria",
"Skopje, Macedonia",
"Nicosia, Cyprus",
"Patras, Greece",
"Białystok, Poland",
"Maenttae, Finland",
"Tarnobrzeg, Poland",
"Larissa, Greece",
"Charleroi, Belgium",
"Lopik, Netherlands",
"Legnica, Poland",
"Niva, Denmark",
"Szczecin, Poland",
"Bruxelles, Belgium",
"Hrodna, Belarus",
"Huissen, Netherlands",
"Fredericia, TR, Denmark",
"Den Oever, Netherlands",
"Oudenbosch, Netherlands",
"Podgorica, Montenegro",
"Minsk, Belarus",
"Vilnius, Lithuania",
"Olsztyn, Poland",
"Megen, Netherlands",
"Oslo, Norway",
"Vroomshoop, Netherlands",
"Siroki Brijeg, Bosnia and Herzegovina",
"Vienne, Austria",
"Vidin, Bulgaria",
"Tbilisi, Georgia",
"Valga, Estonia",
"Skopje, Macedonia",
"Hilversum, Netherlands",
"Sonder Hojrup, Denmark",
"Mechelen, Belgium",
"Middenmeer, Netherlands",
"Ioannina, Greece",
"Corinth, Greece",
"Silkeborg, Denmark",
"Inowroclaw, Poland",
"Amsterdam, Netherlands",
"Rozaje, Montenegro",
"Rapla, Estonia",
"Salzburg, Salzburg, Austria",
"Winschoten, Netherlands",
"Linz, Austria",
"Schaijk, Netherlands",
"Jastrebarsko, Croatia",
"Nikopol, Bulgaria",
"Breskens, Netherlands",
"Łódź, Poland",
"Hulten, Netherlands",
"Andorra la Vella, Andorra",
"Vlaardingen, Netherlands",
"Smilde, Netherlands",
"Brasschaat, Belgium",
"Tallinn, Estonia",
"Hellouw, Netherlands",
"Warszawa, Poland",
"Lublin, Poland",
"Oslo, Norway",
"Wels, Austria",
"Brno, Czech Republic",
"Rotterdam, Netherlands",
"Riga, Latvia",
"Varna, Bulgaria",
"Łódź, Poland",
"Donk, Netherlands",
"Slobozia, Transnistria, Moldova",
"Middelharnis, Netherlands",
"Amsterdam, Netherlands",
"Nicosia, Cyprus",
"Gliwice, Poland",
"Druten, Netherlands",
"Shkodër, Albania",
"Tromsø, Norway",
"Lublin, Poland",
"Białystok, Warsaw Warszawa, Poland",
"Aarhus, Denmark",
"Blagoevgrad, Bulgaria",
"Sint-Niklaas, Belgium",
"Praha, Czech Republic",
"Aalter, Belgium",
"Frederiksberg, Denmark",
"Drammen, Norway",
"Aalborg, Denmark",
"Leoben, Austria",
"Mierlo, Netherlands",
"Salzburg, Austria",
"Rijswijk, Netherlands",
"Donja Stubica, Croatia",
"Wroclaw, Poland",
"Verviers, Belgium",
"Tallinn, Tallinn, Estonia",
"Tervola, Finland",
"Florina, Greece",
"София, Bulgaria",
"Bra, Belgium",
"Pazin, Croatia",
"Paphos, Cyprus",
"Opole, Poland",
"Jyväskylä, Finland",
"Narva, Narva, Estonia",
"Pula, Croatia",
"Liège, Belgium",
"Alexandroupoli, Greece",
"Kraków, Poland",
"Kalamata, Greece",
"Brest, Brest Voblast, Belarus",
"Jeseník, Czech Republic",
"Semmering, Niederosterreich, Austria",
"Køge, Denmark",
"Doetinchem, Netherlands",
"Dudelange, Luxembourg",
"Riga, Latvia",
"Eghezee, Belgium",
"Daugavpils, Latvia",
"Kaarina, Finland",
"Copenhagen, Denmark",
"Zaandam, Netherlands",
"Utrecht, Netherlands",
"Viljandi, Estonia",
"La Condamine, Monaco",
"Joutseno, Finland",
"Vitebsk, Belarus",
"Cetinje, Montenegro",
"Pernik, Bulgaria",
"Charleroi, Belgium",
"St. Veit, Carinthia, Austria",
"Tallinn, Estonia",
"Deventer, Netherlands",
"Bussum, Netherlands",
"Hilversum, Netherlands",
"Pandrup, Denmark",
"Praha, Czech Republic",
"Tirana, Albania",
"Coevorden, Netherlands",
"Roskilde, Denmark",
"Šiauliai, Lithuania",
"Tjerkgaast, Netherlands",
"Corinth, Greece",
"Tallinn, Estonia",
"Barbu, Troms, Norway",
"Copenhagen, Denmark",
"Kalisz, Poland",
"Domazlice, Czech Republic",
"Bergambacht, Netherlands",
"Giessen, Netherlands",
"Zwijndrecht, Netherlands",
"Poznan, Poland",
"Veldhoven, Netherlands",
"Groningen, Netherlands",
"Vilnius, Vilnius, Lithuania",
"Eidsnes, Norway",
"Breda, Netherlands",
"Sieradz, Poland",
"Bourgas, Bulgaria",
"Kardla, Estonia",
"Písek, Czech Republic",
"Zagreb, Croatia",
"Hengelo, Netherlands",
"Shkodër, Albania",
"Mierlo, Netherlands",
"Karlovy Vary, Czech Republic",
"Namur, Belgium",
"Agrinio, Greece",
"Kyrenia, Cyprus",
"Kalwaria Paclawska, Poland",
"Praha, Czech Republic",
"Tbilisi, Georgia",
"Smetanichi, Gomel Oblast, Belarus",
"Bochnia, Poland",
"Bratunac, Bosnia and Herzegovina",
"Heiloo, Netherlands",
"Prague, Czech Republic",
"Tallinn, Tallinn, Estonia",
"Srebrenica, Bosnia and Herzegovina",
"Grudziadz, Poland",
"Floria, Greece",
"Nicosia, Cyprus",
"Breda, Netherlands",
"Pogradec, Albania",
"Bloemendaal, Netherlands",
"Oslo, Norway",
"Utrecht, Netherlands",
"Rotterdam, Netherlands",
"Ostrava, Czech Republic",
"Haapsalu, Haapsalu, Estonia",
"Hilversum, Netherlands",
"Poznan, Poland",
"Kuopio, Finland",
"Preveza, Greece",
"Woerden, Netherlands",
"Patras, Greece",
"Rovaniemi, Finland",
"Nicosia, Cyprus",
"Klaipeda, Lithuania",
"Leersum, Netherlands",
"Brest, Belarus",
"Mouscron, Belgium",
"Rechnitz, Austria",
"Harderwijk, Netherlands",
"Sarajevo, Bosnia and Herzegovina",
"Odense, Denmark",
"Petrinja, Croatia",
"Lemmer, Netherlands",
"Randers, Denmark",
"Zagore, Bulgaria",
"Vidin, Bulgaria",
"Aarhus, Denmark",
"Amsterdam, Netherlands",
"Dedemsvaart, Netherlands",
"Bergen, Norway",
"Fredensborg, DK, Denmark",
"Porvoo, Finland",
"Antwerpen, Belgium",
"Komotini, Greece",
"Elbasan, Albania",
"Tirana, Albania",
"Diemen, Netherlands",
"Riga, Latvia",
"Espoo, Finland",
"Den Haag, Netherlands",
"Diemen, Netherlands",
"Poznan, Poland",
"Olsztyn, Poland",
"Serres, Greece",
"Volendam, Netherlands",
"Nicosia, Cyprus",
"Skopje, Macedonia",
"Lelystad, Netherlands",
"Marusevec, Croatia",
"Liberec, Czech Republic",
"Heraklion, Greece",
"Jevnaker, Norway",
"Baku, Azerbaijan",
"Goes, Netherlands",
"Kato Achaia, Greece",
"Vukovar, Croatia",
"Vilnius, Lithuania",
"Rotterdam, Netherlands",
"Terneuzen, Netherlands",
"Szczecin, Poland",
"Tampere, Finland",
"Gryfice, Poland",
"Kozani, Greece",
"Waddinxveen, Netherlands",
"Lushnje, Albania",
"Kotka, Finland",
"Wien, Austria",
"Iecava, Latvia",
"Võru, Estonia",
"Shumen, Bulgaria",
"Pardubice, Czech Republic",
"Zielona Góra, Poland",
"Victoria, Malta",
"Barneveld, Netherlands",
"Askøy, Norway",
"Opole, Poland",
"Hoofddorp, Netherlands",
"IJmuiden, Netherlands",
"Pniewy, Poland",
"Jyväskylä, Finland",
"Rzeszów, Poland",
"Cazma, Croatia",
"Gomel, Gomel Oblast, Belarus",
"Warszawa, Poland",
"Smilde, Netherlands",
"Katowice, Poland",
"Brno, Czech Republic",
"Tallinn, Estonia",
"Bydgoszcz, Poland",
"Delfzijl, Netherlands",
"Rotterdam, Netherlands",
"Tuzla, Bosnia and Herzegovina",
"Aalborg, Denmark",
"Steenwijk, Netherlands",
"Koszalin, Poland",
"Den Haag, Netherlands",
"Zlatar, Croatia",
"Esch-sur-Alzette, Luxembourg",
"Nida, Lithuania",
"Brno, Czech Republic",
"Pila, Poland",
"Zabbar, Malta",
"Brcko, Bosnia and Herzegovina",
"Heerhugowaard, Netherlands",
"Zoetermeer, Netherlands",
"Denderhoutem, Belgium",
"Srbac, Bosnia and Herzegovina",
"Limassol, Cyprus",
"Rijssen, Netherlands",
"Bad Gastein, Salzburg, Austria",
"Kraków, Poland",
"Rotterdam, Netherlands",
"Arnhem, Netherlands",
"Enkhuizen, Netherlands",
"Salo, Finland",
"Αθήναι, Greece",
"Šiauliai, Lithuania",
"Faaborg, Denmark",
"Genk, Belgium",
"Groesbeek, Netherlands",
"Zitineni, Macedonia",
"Chomutov, Czech Republic",
"Hodonín, Czech Republic",
"Rotterdam, Netherlands",
"Kerkira, Greece",
"Helsinki, Finland",
"Karlovy Vary, Czech Republic",
"Nordmannvik, Aust-Agder , Norway",
"Bruntal, Czech Republic",
"Melhus, Sør-Trøndelag, Norway",
"Praha, Czech Republic",
"Tartu, Estonia",
"Požega, Croatia",
"Stolwijk, Netherlands",
"Veliko Tarnovo, Bulgaria",
"Xanthi, Greece",
"Chisinau, Moldova",
"Kozani, Greece",
"Szczecin, Poland",
"Mons, Belgium",
"Silistra, Bulgaria",
"Melkas, Riga, Latvia",
"Bruges, Belgium",
"Pilsen, Czech Republic",
"Wrocław, Poland",
"Aardenburg, Netherlands",
"Valasske Mezirici, Czech Republic",
"Viborg, Denmark",
"Łódź, Poland",
"Chania, Greece",
"Porvoo, Finland",
"Veluwe, Netherlands",
"Kardzhali, Bulgaria",
"Limassol, Cyprus",
"Srebrenik, Bosnia and Herzegovina",
"Vilnius, Lithuania",
"Kozani, Greece",
"Kraków, Poland",
"Hilversum, Netherlands",
"Koprivnica, Croatia",
"Białystok, Poland",
"Ilidza, Bosnia and Herzegovina",
"Riga, Latvia",
"Vught, Netherlands",
"Zadar, Croatia",
"Kuopio, Finland",
"Elblag, Poland",
"Velika Kladuša, Bosnia and Herzegovina",
"Mons, Belgium",
"Minsk, Belarus",
"Espoo, Finland",
"Corinth, Greece",
"Vriezenveen, Netherlands",
"Kraków, Poland",
"København, Denmark",
"Marijampole, Lithuania",
"Sisak, Croatia",
"Mahilyow, Belarus",
"Pogradec, Albania",
"Silistra, Bulgaria",
"Leska, Czech Republic",
"Mostar, Bosnia and Herzegovina",
"Halle, Belgium",
"Riga, Latvia",
"Oswiecim, Poland",
"Kaunas, Kaunas, Lithuania",
"Agrinio, Greece",
"Hulsberg, Netherlands",
"Grudziadz, Poland",
"Bistrica, Croatia",
"Beli Manastir, Croatia",
"Corfu, Greece",
"Aalst, Netherlands",
"Nicosia, Cyprus",
"Alphen aan den Rijn, Netherlands",
"Vilnius, Lithuania",
"Jaunmarupe, Latvia",
"Helsinki, Finland",
"Brno, Czech Republic",
"Šiauliai, Lithuania",
"Brno, Czech Republic",
"Lelystad, Netherlands",
"Plovdiv, Bulgaria",
"Paramythia, Greece",
"Pyrgos, Greece",
"Geel, Belgium",
"Montana, Bulgaria",
"Vejle, Denmark",
"Sankt Leonhard am Forst, Austria",
"Livadia, Greece",
"Sarajevo, Bosnia and Herzegovina",
"Heraklion, Greece",
"Brno, Czech Republic",
"Hoogezand, Netherlands",
"Birkirkara, MT, Malta",
"Budejovice, Czech Republic",
"Warszawa, Poland",
"Hilversum, Netherlands",
"Pärnu, Parnu, Estonia",
"Eupen, Belgium",
"Purmerend, Netherlands",
"Petrich, Bulgaria",
"Oslo, Norway",
"Brest, Belarus",
"Chania, Greece",
"Kraków, Poland",
"Nicosia, Cyprus",
"Banja Luka, Bosnia and Herzegovina",
"Enschede, Netherlands",
"Annen, Netherlands",
"Kozani, Greece",
"Oslo, Norway",
"Chios, Greece",
"Praha, Czech Republic",
"Pardubice, Czech Republic",
"Poortugaal, Netherlands",
"Huizen, Netherlands",
"Torun, Poland",
"Gdańsk, Poland",
"Kankaanpaa, Finland",
"Kalamata, Greece",
"Roosendaal, Netherlands",
"Tórshavn, Faroe Islands",
"Nieuw-Lekkerland, Netherlands",
"Liberec, Czech Republic",
"Λάρισα, Greece",
"Tirana, Albania",
"The Hague, Netherlands",
"Braine-le-Comte, Belgium",
"Brno, Czech Republic",
"Oude Pekela, Netherlands",
"Heraklion, Greece",
"Vilnius, Lithuania",
"Made, Netherlands",
"Smolyan, Bulgaria",
"Paterswolde, Netherlands",
"Eurajoki, Finland",
"Minsk, Belarus",
"Vilnius, Lithuania",
"Wavre, Belgium",
"Marsa, Malta",
"Roosendaal, Netherlands",
"Szczecin, Poland",
"Vsetin, Czech Republic",
"Minsk, Belarus",
"Nicosia, Cyprus",
"Noordwolde, Netherlands",
"Kaunas, Lithuania",
"Arnhem, Netherlands",
"Lichtenvoorde, Netherlands",
"Brussels, Belgium",
"Nicosia, Cyprus",
"Gemert, Netherlands",
"Podgorica, Montenegro",
"Varaždin, Croatia",
"Corfu, Greece",
"Jirnsum, Netherlands",
"Dudelange, Luxembourg",
"Jaarsveld, Netherlands",
"Pardubice, Czech Republic",
"Kielce, Poland",
"Brussels, Belgium",
"Skopje, Macedonia",
"Mons, Belgium",
"Kristiansand, Aust i Vest-Agder Counties, Norway",
"Bergen op Zoom, Netherlands",
"Tirana, Albania",
"Kuressaare, Saaremaa, Estonia",
"Alytus, Alytus, Lithuania",
"Schwaz, Austria",
"Drammen, Norway",
"Gliwice, Poland",
"Brussegem, Belgium",
"Tartu, Estonia",
"Limassol, Cyprus",
"Bettembourg, Luxembourg",
"Rapla, Estonia",
"Split, Croatia",
"Heraklion, Greece",
"Karpathos, Greece",
"San Gwann, Malta",
"Prague, Czech Republic",
"Wrocław, Poland",
"Kuressaare, Estonia",
"Pernik, Bulgaria",
"Waalre, Netherlands",
"Deutschlandsberg, Austria",
"Turnhout, Belgium",
"Osijek, Croatia",
"Mogenstrup, Denmark",
"Liège, Belgium",
"Stackunai, Birzai/Kupiškis/Rokiškis, Lithuania",
"Dronten, Netherlands",
"Kraków, Poland",
"Varna, Bulgaria",
"Agia Paraskevi, Greece",
"Heraklion, Greece",
"Loutrakion, Greece",
"Patras, Greece",
"Oslo, Oslo, Norway",
"Ostrava, Czech Republic",
"Lokeren, Belgium",
"Bad Ischl, Austria",
"Szczecin, Poland",
"Rucphen, Netherlands",
"Gdańsk, Poland",
"Klagenfurt, Austria",
"Sint-Truiden, Belgium",
"Kaunas, Lithuania",
"Oulu, Finland",
"Rezekne, Latvia",
"Enschede, Netherlands",
"Chisinau, Moldova",
"The Hague, Netherlands",
"s-Gravenzande, Netherlands",
"Medugorje, Bosnia and Herzegovina",
"Søgne, Aust i Vest-Agder Counties, Norway",
"Köyliö, Finland",
"Oslo, Norway",
"Vilnius, Lithuania",
"Nowy Sacz, Poland",
"Riga, Latvia",
"Alexandroupoli, Greece",
"Ter Apel, Netherlands",
"Arslev, Denmark",
"Skopje, Macedonia",
"Aarschot, Belgium",
"Paralimni, Famagusta, Cyprus",
"Kokemäki, Finland",
"Sarajevo, Bosnia and Herzegovina",
"Elblag, Poland",
"Chania, Greece",
"Kielce, Poland",
"Ναύπλιο, Greece",
"Most, Czech Republic",
"Aegion, Greece",
"София, Bulgaria",
"Valmiera, Latvia",
"Aarhus, Denmark",
"Czestochowa, Poland",
"Riga, Latvia",
"Maardu, Estonia",
"Nieuwkerken-Waas, Belgium",
"Joensuu, Finland",
"Cheb, Czech Republic",
"Uddel, Netherlands",
"Rechnitz, Burgenland, Austria",
"Zenica, Bosnia and Herzegovina",
"София, Bulgaria",
"Wrocław, Poland",
"Poznan, Poland",
"Reykjavík, Iceland",
"Kirchdorf, Austria",
"Brest, Belarus",
"Lienz, Tyrol, Austria",
"Mreznica, Croatia",
"Rotterdam, Netherlands",
"Reykjavik, Iceland",
"Radomsko, Poland",
"Vidovec, Croatia",
"Nieuwkuijk, Netherlands",
"Helsinki, Finland",
"Tilburg, Netherlands",
"Hovin, Telemark , Norway",
"Vienna, Austria",
"Gharghur, Malta",
"Gdańsk, Poland",
"Olsztyn, Poland",
"Wien, Austria",
"Juragiai, Kaunas, Lithuania",
"Stavanger, Norway",
"Den Helder, Netherlands",
"Oldenzaal, Netherlands",
"Schoten, Belgium",
"Gomel, Belarus",
"Steenbergen, Netherlands",
"Xewkija, Malta",
"Chios, Greece",
"Gusinje, Montenegro",
"Siteia, Greece",
"Sarajevo, Bosnia and Herzegovina",
"Jesenik, Czech Republic",
"Mill, Netherlands",
"Kraków, Poland",
"Kavarna, Bulgaria",
"Pärnu, Estonia",
"Breda, Netherlands",
"Krapkowice, Poland",
"Oslo, Oslo, Norway",
"Minsk, Belarus",
"Geertruidenberg, Netherlands",
"Stein, Netherlands",
"Burgum, Netherlands",
"Vratza, Bulgaria",
"Innsbruck, Austria",
"Sofia, Sofia, Bulgaria",
"Lahti, Finland",
"Popovo, Bulgaria",
"Copenhagen, Denmark",
"Koli, Finland",
"Bjelasnica, Bosnia and Herzegovina",
"Prozor, Bosnia and Herzegovina",
"Turku, Finland",
"Nicosia, Cyprus",
"Dokkum, Netherlands",
"Plovdiv, Bulgaria",
"Nicosia, Cyprus",
"Konin, Poland",
"Hannut, Belgium",
"Brno, Czech Republic",
"Lontzen, Belgium",
"Torun, Poland",
"Baku, Azerbaijan",
"Weesp, Netherlands",
"Maglaj, Bosnia and Herzegovina",
"Tjerkgaast, Netherlands",
"Torshavn, Faroe Islands",
"Pale, Bosnia and Herzegovina",
"Znojmo, Czech Republic",
"Joutseno, Finland",
"Trondheim, Norway",
"Bjelovar, Croatia",
"Wanssum, Netherlands",
"Valga, Estonia",
"Antwerpen, Belgium",
"Rethymno, Greece",
"Itea, Greece",
"Tallinn, Estonia",
"Kravarsko, Croatia",
"Katowice, Poland",
"Popovo, Bulgaria",
"Helsinki, Finland",
"Arnhem, Netherlands",
"Almere Stad, Netherlands",
"Espoo, Finland",
"Lohja, Finland",
"Rotterdam, Netherlands",
"Graz, Austria",
"Knokke-Heist, Belgium",
"Rhodes, Greece",
"Brussels, Belgium",
"Nicosia, Cyprus",
"Ardenice, Albania",
"Yambol, Bulgaria",
"Staphorst, Netherlands",
"Balti, Moldova",
"Lienz, Osttirol, Austria",
"Fijnaart, Netherlands",
"Daruvar, Croatia",
"Hämeenlinna, Finland",
"Graz, Austria",
"Praha, Czech Republic",
"Szczecin, Poland",
"Egem, Belgium",
"Groenlo, Netherlands",
"Pravets, Bulgaria",
"Viljandi, Estonia",
"Smilde, Netherlands",
"Krems, Austria",
"Riga, Latvia",
"Ostrów Wielkopolski, Poland",
"Krosno, Poland",
"Antwerp, Belgium",
"Heraklion, Greece",
"Kresna, Bulgaria",
"Poznan, Poland",
"Kraków, Poland",
"Jihlava, Czech Republic",
"Kryezi, Albania",
"Valkeakoski, Finland",
"Heraklion, Greece",
"Egem, Belgium",
"Asperen, Netherlands",
"Rapla, Estonia",
"Tartu, Estonia",
"Hilversum, Netherlands",
"Split, Croatia",
"Mogilev, Mogilyov Oblast , Belarus",
"Warszawa, Poland",
"Lelystad, Netherlands",
"Reykjavík, Iceland",
"Eurajoki, Finland",
"Rødovre, Denmark",
"Utrecht, Netherlands",
"Jihlava, Czech Republic",
"Lublin, Poland",
"Kakanj, Bosnia and Herzegovina",
"Katowice, Poland",
"Glina, Croatia",
"Tiraspol, Moldova",
"Lochem, Netherlands",
"Wrocław, Poland",
"Jihlava, Czech Republic",
"Lahti, Finland",
"Beringen, Belgium",
"Assen, Netherlands",
"Limassol, Cyprus",
"Łódź, Poland",
"Aarhus, Denmark",
"Veliko Tarnovo, Bulgaria",
"Zielona Góra, Poland",
"Hamrun, Malta",
"Tallinn, Estonia",
"Koszalin, Poland",
"Groningen, Netherlands",
"Hazerswoude-Rijndijk, Netherlands",
"Crna Gora, Montenegro",
"Dobrochov, Czech Republic",
"Karditsa, Greece",
"Bruges, Belgium",
"Tomaszów Mazowiecki, Poland",
"Zeewolde, Netherlands",
"Valletta, Malta",
"Zurrieq, Malta",
"Iraklion, Greece",
"Soignies, Belgium",
"Luxembourg, Luxembourg",
"Sarajevo, Bosnia and Herzegovina",
"Shumen, Bulgaria",
"Rotterdam, Netherlands",
"Liège, Belgium",
"Berlicum, Netherlands",
"Jekabpils, Latvia",
"Poznan, Poland",
"Chisinau, Moldova",
"Szczecin, Poland",
"Rijswijk, Netherlands",
"Wrocław, Poland",
"Linnamae, Haapsalu, Estonia",
"Zadar, Croatia",
"Haugesund, Norway",
"Riga, Latvia",
"Kalamata, Greece",
"Helsinki, Finland",
"Tartu, Tartu, Estonia",
"Warszawa , Poland",
"Geel, Belgium",
"Olsztyn, Poland",
"Ogulin, Croatia",
"Volos, Greece",
"Borger, Netherlands",
"Skopje, Macedonia",
"Vilnius, Lithuania",
"Valgjarve, Estonia",
"Λάρισα, Greece",
"Tarnów, Poland",
"Terblijt, Netherlands",
"Volos, Greece",
"Genk, Belgium",
"Liège, Belgium",
"Pernik, Bulgaria",
"Den Oever, Netherlands",
"Ilijas, Bosnia and Herzegovina",
"Nadur, Malta",
"Boskovice, Czech Republic",
"Põlva, Estonia",
"Nicosia, Cyprus",
"Verviers, Belgium",
"Warsaw, Poland",
"Oulu, Finland",
"Zagreb, Croatia",
"Valgjarve, Voru, Estonia",
"Pelekanadha, Greece",
"Telšiai, Lithuania",
"Prijedor, Bosnia and Herzegovina",
"Kardzhali, Bulgaria",
"Warszawa, Poland",
"Amsterdam, Netherlands",
"Amsterdam, Netherlands",
"Białystok, Poland",
"Sofia, Bulgaria",
"Haapsalu, Haapsalu, Estonia",
"Koeru, Estonia",
"Tartu, Estonia",
"Skopje, Macedonia",
"Kielce, Poland",
"Liège, Belgium",
"Hasselt, Belgium",
"Vitebsk, Belarus",
"Minsk, Belarus",
"Lamia, Greece",
"Anjala, Finland",
"Genk, Belgium",
"Pärnu, Estonia",
"Argostoli, Greece",
"Wien, Austria",
"Alkmaar, Netherlands",
"Den Bosch, Netherlands",
"Kuressaare, Saaremaa, Estonia",
"Bydgoszcz, Poland",
"Winterswijk, Netherlands",
"Oss, Netherlands",
"Katowice, Poland",
"Gniezno, Poland",
"Millingen aan de Rijn, Netherlands",
"Tampere, Finland",
"Zgrada, BSP, Montenegro",
"Brussels, Belgium",
"Kristiansand, Norway",
"Nivelles, Belgium",
"Lezajsk, Poland",
"Usora, Bosnia and Herzegovina",
"Bydgoszcz, Poland",
"Praha, Czech Republic",
"Emmen, Netherlands",
"Agia, Greece",
"Vitebsk, Vitebsk Oblast, Belarus",
"Copenhagen, Denmark",
"Gorzow Slaski, Poland",
"Białystok, Poland",
"Arnhem, Netherlands",
"Sarajevo, Bosnia and Herzegovina",
"Eurajoki, Finland",
"Wageningen, Netherlands",
"Someren, Netherlands",
"Brussels, Belgium",
"Arta, Greece",
"Lamia, Greece",
"Ohrid, Macedonia",
"Hirtshals, Denmark",
"Λάρισα, Greece",
"Vilnius, Lithuania",
"Patras, Greece",
"Wierden, Netherlands",
"Haarlem, Netherlands",
"Markelo, Netherlands",
"Tammela, Finland",
"Krimpen aan den IJssel, Netherlands",
"Hilversum, Netherlands",
"Riga, Latvia",
"Korgessaare, Estonia",
"Hvidovre, Denmark",
"Oudenaarde, Belgium",
"Linnamae, Estonia",
"Utena, Lithuania",
"Klaipeda, Klaipeda/Palanga, Lithuania",
"Nivaa, Denmark",
"Skopje, Macedonia",
"Kuopio, Finland",
"Opole, Poland",
"Vilnius, Lithuania",
"Kljuc, Bosnia and Herzegovina",
"Ptolemaida, Greece",
"Ugchelen, Netherlands",
"Karditsa, Greece",
"Sippola, Finland",
"Kerkdriel, Netherlands",
"Herentals, Belgium",
"Pravets, Bulgaria",
"Ioannina, Greece",
"Bergen, Hordaland County, Norway",
"Visaginas, Lithuania",
"Schwarzach im Pongau, Austria",
"Skopje, Macedonia",
"Stara Zagora, Bulgaria",
"Umag, Croatia",
"Tórshavn, Faroe Islands",
"Baku, Azerbaijan",
"Mogilev, Belarus",
"Wien, Austria",
"Tiel, Netherlands",
"Pärnu, Estonia",
"Corfu, Greece",
"Bilzen, Belgium",
"Ioannina, Greece",
"Eupen, Belgium",
"Katowice, Poland",
"Mytilini, Greece",
"Innsbruck, Austria",
"Λάρισα, Greece",
"Peer, Belgium",
"Pazardzhik, Bulgaria",
"Bruxelles, Belgium",
"Taurage, Lithuania",
"Hilversum, Netherlands",
"Bruxelles, Belgium",
"Wien, Austria",
"Selfoss, Iceland",
"Tirana, Albania",
"Randers, Denmark",
"Sint Anthonis, Netherlands",
"Bolsward, Netherlands",
"Praha, Czech Republic",
"Copenhagen, Denmark",
"Kielce, Poland",
"Brussels, Belgium",
"Ohrid, Macedonia",
"Banja Luka, Bosnia and Herzegovina",
"Leuven, Belgium",
"Kiihtelysvaara, Finland",
"Most, Czech Republic",
"Serres, Greece",
"Gllava e Madhe, Albania",
"Travnik, Bosnia and Herzegovina",
"Florina, Greece",
"Klagenfurt, Austria",
"Vaduz, Liechtenstein",
"Rotterdam, Netherlands",
"Lekkerkerk, Netherlands",
"Võru, Estonia",
"Heraklion, Greece",
"Navapolatsk, Belarus",
"Agsu, Azerbaijan",
"Stiens, Netherlands",
"Labin, Croatia",
"Łódź, Poland",
"Leiden, Netherlands",
"Bjelovar, Croatia",
"Lublin, Poland",
"Vught, Netherlands",
"Drama, Greece",
"Nicosia, Cyprus",
"Eindhoven, Netherlands",
"Tampere, Finland",
"Geraardsbergen, Belgium",
"Tampere, Finland",
"Kavala, Greece",
"Olomouc, Czech Republic",
"Alkmaar, Netherlands",
"Minsk, Belarus",
"Oostende, Belgium",
"Tirana, Albania",
"Minsk, Belarus",
"Lezhë, Albania",
"Oulu, Finland",
"Kielce, Poland",
"Turku, Finland",
"Linz, Austria",
"Hoorn, Netherlands",
"Zagreb, Zagreb, Croatia",
"Burgas, Bulgaria",
"Ostrava, Czech Republic",
"Hollola, Finland",
"Oulu, Oulu, Finland",
"Bregenz, Austria",
"Echt, Netherlands",
"Bydgoszcz, Poland",
"Innsbruck, Austria",
"Heraklion, Greece",
"Liepaja, Latvia",
"Bileca, Bosnia and Herzegovina",
"Sandanski, Bulgaria",
"Ostrava, Czech Republic",
"Purhus, Denmark",
"Mladá Boleslav, Czech Republic",
"Haapsalu, Tartu, Estonia",
"Gdańsk, Poland",
"Rhodes, Greece",
"Minsk, Belarus",
"Tjerkgaast, Netherlands",
"Roskilde, Denmark",
"Torshavn, Faroe Islands",
"Vienna, Austria",
"Mierlo, Netherlands",
"Zielona Góra, Poland",
"Eindhoven, Netherlands",
"Ioannina, Greece",
"Oslo, Norway",
"Oslo, Norway",
"Alytus, Alytus, Lithuania",
"Villach, Carinthia, Austria",
"Philippine, Netherlands",
"Veendam, Netherlands",
"Lebork, Poland",
"Pärnu, Estonia",
"Noordwijk-Binnen, Netherlands",
"Tallinn, Tallinn, Estonia",
"Ruurlo, Netherlands",
"Hradec Králové, Czech Republic",
"Buren, Netherlands",
"Livno, Bosnia and Herzegovina",
"Harlingen, Netherlands",
"Kaarina, Finland",
"Ath, Belgium",
"Tampere, Finland",
"Semmering, Niederosterreich, Austria",
"Metkovic, Croatia",
"Valgjarve, Estonia",
"Vrazici, Bosnia and Herzegovina",
"Baku, Azerbaijan"


]

require('async').map(cities, function(city, coords) {
    getCoords(city)
        .then((coords, cities) => {
            //var infoz = [];
            infoz = [city, coords];
            //infoz.push(results)
            //results = (city + " : " + JSON.stringify(coords));
            //infoz = (infoz[0])
            //console.log(infoz)
            data = {
                "city": infoz[0],
                "coords": infoz[1]
            }
            //console.log(data)
            //return data
            fs.appendFile("final/europe_v1.json", JSON.stringify(data), function(err) {
                if (err) {
                    return console.log(err);
                }
                //console.log("The file was saved!");
            });

        });


});












