var getCoords = require('city-to-coords');
var getCoords = require('city-to-coords');
var json2csv = require('json2csv');
var fs = require('fs')
var csvjson = require('csvjson');
var cities = [
"Saint-Brieuc, France",
"Bayonne, France",
"Manosque, France",
"Perpignan, France",
"Epernay, Champagne, France",
"Grenoble, France",
"Bourges, France",
"Grenoble, France",
"Gap, France",
"Valence, France",
"Macon, France",
"Lille, Nord-Pas-de-Calais, France",
"Paris, France",
"Villeneuve-d'Ascq, France",
"Paris, France",
"Chalon-sur-Saône, France",
"Sens, France",
"Paris, France",
"Chatel-Saint-Germain, France",
"Limoges, France",
"Toulouse, France",
"Grenoble, France",
"Montpon-Menesterol, Aquitaine , France",
"Quimper, France",
"Hyères, France",
"Puy-Guillaume, France",
"Privas, France",
"Montpellier, France",
"Lezignan, France",
"Mareuil-sur-Lay-Dissais, France",
"Paris, France",
"Airvault, France",
"Rennes, France",
"Montlucon, France",
"Agen, Aquitaine , France",
"Brest, France",
"Conteville, France",
"Villebon, France",
"Paris, France",
"Caen, France",
"Chartres, Centre, France",
"Annecy, France",
"Albertville, France",
"Strasbourg, Alsace, France",
"Saint-Quentin, France",
"Macon, France",
"Tours, France",
"Béziers, Languedoc-Roussillon, France",
"Nancy, France",
"Fouras, France",
"Six-Fours-les-Plages, France",
"Agen, France",
"Épinal, France",
"Gervais, France",
"Lille, France",
"Maromme, France",
"Corbieres, Languedoc Roussillon , France",
"Paris, France",
"Saint-Herblain, France",
"Nantes, France",
"Lille, France",
"Oloron-Sainte-Marie, Aquitaine, France",
"Troyes, France",
"Aytre, France",
"Nantes, France",
"Biarritz, France",
"Orleans, France",
"Bernay, France",
"Pau, France",
"Besançon, France",
"Beauvais, France",
"Rennes, France",
"Lyon, France",
"Angoulême, France",
"Chateau, France",
"Saint Denis, France",
"Plouguerneau, France",
"Toulon, France",
"Saint-Brieuc, Bretagne, France",
"Nantes, France",
"Caen, France",
"Béziers, France",
"Pleneuf-Val-Andre, France",
"Chaumont, France",
"Nevers, France",
"Sable-sur-Sarthe, France",
"Saint-Florent-le-Vieil, France",
"Bayonne, France",
"Nice, France",
"Bourgoin, France",
"Cavaillon, France",
"Fontainebleau, France",
"Chalon-sur-Saône, Bourgogne   , France",
"Surgeres, France",
"Clamecy, France",
"Paris, France",
"Paris, France",
"Toulouse, France",
"Barentin, Haute-Normandie, France",
"Grenoble, France",
"Artenay, France",
"Lille, France",
"Strasbourg, France",
"Compiegne, France",
"Mas-des-Cours, France",
"Poitiers, France",
"Montpellier, France",
"Montpellier, France",
"La Rochelle, France",
"Rosnoen, France",
"Saint-Coulomb, France",
"Melle, France",
"Châtellerault, Poitou-Charentes, France",
"Agen, France",
"Orleans, France",
"Nice, Provence-Alpes-Côte d'Azur, France",
"Gérardmer, France",
"Bagnolet, France",
"Reims, France",
"Pithiviers, France",
"Montereau, France",
"Pons, France",
"Toulon, Provence-Alpes-Côte d'Azur, France",
"Besançon, France",
"Toulon, France",
"Castres, France",
"Angers, France",
"Montauban, France",
"Arras, France",
"Sedan, France",
"Aubenas, France",
"Paris, France",
"Saint-Brieuc, France",
"Quimper, France",
"Guyancourt, France",
"Vannes, France",
"Carcassonne, France",
"Chambéry, France",
"Dijon, France",
"Tours, France",
"Albertville, Rhône Alpes, France",
"Joyeuse, France",
"Piquecos, France",
"Brest, France",
"Paris, France",
"Les Arcs, France",
"Domerat, France",
"Ballan-Mire, France",
"Nay, France",
"Bellegarde, France",
"Draguignan, France",
"Cernay, France",
"Langon, France",
"Châteaulin, Bretagne, France",
"Béziers, France",
"Avignon, Provence-Alpes-Côte d'Azur, France",
"Apt, France",
"Toulouse, Midi-Pyrénées, France",
"Dijon, France",
"Gueret, France",
"Le Thillot, France",
"Bordeaux, France",
"Gap, Provence-Alpes-Côte d'Azur, France",
"Arcachon, France",
"Craponne-sur-Arzon, France",
"Quimperlé, France",
"Annecy, France",
"Colmar, France",
"Perpignan, Languedoc-Roussillon, France",
"Lozere, France",
"Tours, France",
"Bandol, France",
"Sommières, France",
"Auxerre, France",
"Creil, France",
"Saint-Étienne, Rhône Alpes, France",
"Sille-le-Guillaume, France",
"Paris, France",
"Clermont-Ferrand, France",
"Agde, France",
"Nice, France",
"Pertuis, France",
"Mazamet, Midi-Pyrénées, France",
"Poitiers, France",
"Sète, France",
"Troyes, France",
"Narbonne, France",
"Béziers, France",
"Nevers, France",
"Strasbourg, France",
"Alès, France",
"Charleville-Mézières, France",
"Manosque, France",
"Douvrin, France",
"Aulnoye-Aymeries, France",
"Grenoble, France",
"Gueret, France",
"Alès, France",
"Gap, France",
"Montpellier, France",
"Saint-Brieuc, France",
"Bourg-en-Bresse, France",
"Pontcharra, France",
"Morteau, France",
"Clermont-Ferrand, France",
"Carcassonne, France",
"Cercoux, France",
"Givet, France",
"Metz, Lorraine , France",
"Paris, France",
"Saint-Martin-Boulogne, France",
"Menton, France",
"Agen, France",
"Narbonne, France",
"Périgueux, France",
"Poitiers, France",
"Rouen, France",
"Avignon, France",
"Cassel, France",
"Paris, France",
"Romilly-sur-Seine, France",
"Brest, France",
"Pontcharra, France",
"Montpellier, France",
"Marseille, France",
"Toulon, France",
"Pierrelatte, France",
"Crest, France",
"Dunkirk, France",
"Louviers, France",
"Bordeaux, France",
"Lille, France",
"Pont-a-Mousson, France",
"Nancy, France",
"Brest, France",
"Millau, France",
"Grenoble, France",
"Pau, France",
"Paris, France",
"Clermont-Ferrand, Auvergne, France",
"Rennes, Bretagne, France",
"Saint-Affrique, France",
"Valenciennes, France",
"Bordeaux, France",
"Perpignan, France",
"Paris, France",
"Labastide-Saint-Pierre, France",
"Douai, France",
"Remiremont, France",
"Lorient, France",
"Bordeaux, France",
"Nevers, France",
"Le Cheylard, France",
"Saint-Pierre-des-Corps, France",
"Nérac, France",
"Montélimar, France",
"Strasbourg, France",
"Gray, France",
"Dinan, France",
"Brest, France",
"Manosque, France",
"Saint-Étienne, France",
"Dinan, Bretagne, France",
"Egletons, France",
"Alencon, France",
"Chateau-Gontier, France",
"Montmorillon, France",
"Toulouse, France",
"Beauvais, France",
"Évreux, France",
"Marseille, France",
"Nantes, France",
"Fismes, France",
"Grasse, France",
"Châteaudun, France",
"Lorient, France",
"Vauvert, France",
"Charleville-Mezieres, France",
"Flamanville, France",
"Le Mans, Pays de la Loire, France",
"Fresnay-sur-Sarthe, France",
"Saint-Julien-en-Genevois, France",
"Grenoble, France",
"Saint Denis, France",
"Toulouse, France",
"Yssingeaux, France",
"Beaumont-Hague, France",
"Limoges, France",
"Nozay, France",
"Beaumont-sur-Oise, France",
"Loches, France",
"Mulhouse, France",
"Landerneau, France",
"Saint-Meen-le-Grand, France",
"Dijon, France",
"Paris, France",
"Nogent-le-Rotrou, France",
"Nantes, Pays de la Loire, France",
"Sens, France",
"Montpellier, France",
"Nancy, France",
"Corbeil-Essonnes, France",
"Charleville-Mezieres, Champagne, France",
"Montpellier, France",
"Lille, France",
"Pau, Aquitaine, France",
"Remiremont, France",
"Charleville-Mézières, France",
"Vesoul, France",
"Bordeaux, Aquitaine, France",
"Nancy, France",
"La Ferte-sous-Jouarre, France",
"Périgueux, France",
"Bourg-en-Bresse, France",
"Argenton-sur-Creuse, Centre, France",
"Chalon, France",
"Épinal, France",
"Nantes, France",
"Les Sables, France",
"Nancy, Lorraine , France",
"Montauban, France",
"La Verpilliere, France",
"Nantes, France",
"Fleurance, France",
"Rouen, Haute-Normandie, France",
"Chemin, France",
"Capbreton, France",
"Cambrai, Nord-Pas-de-Calais, France",
"Privas, Rhône Alpes, France",
"Marseille, France",
"Mantes-la-Jolie, France",
"Tours, Centre, France",
"Saint-Hippolyte-du-Fort, France",
"Dinan, France",
"Marseille, France",
"Gueret, France",
"Dijon, France",
"Val Pompadour, France",
"Pertuis, France",
"La Roche-sur-Yon, France",
"Lyon, France",
"Nantes, France",
"Toul, France",
"Boulogne-sur-Mer, Nord-Pas-de-Calais, France",
"Limoges, France",
"Chateauroux, France",
"Cergy, France",
"Saint-Laurent-du-Var, France",
"Toulouse, France",
"Colagnies-des-Fenets, France",
"Mulhouse, France",
"Montpellier, France",
"Montpellier, France",
"Paris, France",
"Chalon-sur-Saône, France",
"Concarneau, France",
"Rochefort, France",
"Saint-Étienne, France",
"Saint-Marcel, France",
"Archamps, France",
"Montargis, France",
"Paris, France",
"Mirande, France",
"Dunkirk, France",
"Paris, France",
"Angers, France",
"Annonay, France",
"Saint-Étienne, France",
"Marseille, France",
"Calais, France",
"Bagnères-de-Bigorre, France",
"Dunkerque, France",
"Montpellier, France",
"Saint-Étienne, France",
"Alès, France",
"Lyon, France",
"Pau, France",
"Montfort, France",
"Aubenas, France",
"Rennes, France",
"Paris, France",
"Boulogne-sur-Mer, France",
"Nevers, Bourgogne, France",
"Peltre, France",
"Lyon, Rhône Alpes, France",
"Toulouse, France",
"Hérouville-Saint-Clair, France",
"Saulx-les-Chartreux, France",
"Meaux, France",
"Fréjus, France",
"Laval, France",
"Draguignan, Provence-Alpes-Côte d'Azur, France",
"Belley, France",
"Nantes, France",
"Angers, France",
"Grenoble, Rhône Alpes, France",
"Valence, France",
"Auray, France",
"Saint-Étienne, France",
"Rambouillet, France",
"Perpignan, France",
"Beauvais, France",
"Pontoise, France",
"Bordeaux, France",
"Nancy, France",
"Casteljaloux, France",
"Draguignan, France",
"Gerzat, France",
"Sarrebourg, France",
"Châteaulin, France",
"Jallieu, France",
"Lyon, France",
"Paris, France",
"Carcassonne, France",
"Saint-Jean-d'Illac, France",
"Charleville-Mezieres, France",
"Brest, Bretagne, France",
"Paris, France",
"Angers, France",
"Longwy, France",
"Lyon, France",
"Tulle, France",
"La Plagne, France",
"Perpignan, France",
"Hyères, France",
"Lyon, France",
"Toulouse, France",
"Ebreuil, France",
"Luz-Saint-Sauveur, France",
"Quimperlé, France",
"Romilly-sur-Seine, France",
"Nantes, France",
"Abbeville, Picardie, France",
"Pontcharra, France",
"Montbéliard, France",
"Montreuil, France",
"Paris, France",
"Villeurbanne, France",
"Bourges, Centre , France",
"Marseille, France",
"Vire, France",
"Vieille-Eglise, France",
"Trappes, France",
"Taverny, France",
"Tarbes, France",
"La Couyere, France",
"Mauleon-Licharre, France",
"Bellegarde, France",
"Arvert, France",
"Lorient, Bretagne, France",
"Montluçon, France",
"Brive-la-Gaillarde, Limousin, France",
"Villeneuve-sur-Lot, France",
"Paris, France",
"Hérouville-Saint-Clair, France",
"Lorient, France",
"Limoges, France",
"Lille, France",
"Pons, France",
"Albi, France",
"Longwy, France",
"Lyon, France",
"Fos-sur-Mer, France",
"Le Havre, France",
"Alès, France",
"Orleans, Centre, France",
"Orleans, France",
"Grenoble, France",
"Paris, France",
"Vitré, France",
"Saint-Philbert-de-Grand-Lieu, France",
"Chambéry, France",
"Carlepont, France",
"Angers, Pays de la Loire, France",
"Nîmes, France",
"Montpellier, France",
"Dunkerque, Nord-Pas-de-Calais, France",
"Albi, France",
"Clermont-Ferrand, France",
"Valence, France",
"Avignon, France",
"Perpignan, France",
"Lannemezan, France",
"Bassin, France",
"Limoges, France",
"Châteaubriant, France",
"Puget-Theniers, France",
"Caen, France",
"Troyes, France",
"Chaumont, France",
"Saint-Étienne, France",
"Le Havre, France",
"Le Mans, France",
"Arles, France",
"Hyères, France",
"Courtenay, Centre, France",
"Montbéliard, France",
"Bourbon-l'Archambault, France",
"Valence, France",
"Montluçon, Allier, France",
"Albertville, France",
"Draguignan, France",
"Reims, France",
"Strasbourg, France",
"Angers, France",
"Lyon, France",
"Neuville-de-Poitou, France",
"Rennes, France",
"Thiaville-sur-Meurthe, France",
"Cannes, France",
"Lille, France",
"L'Argentiere, France",
"Vichy, France",
"Amberieu-en-Bugey, France",
"Albi, Midi-Pyrénées, France",
"Nice, France",
"Dijon, Bourgogne, France",
"Toulouse, France",
"Avignon, France",
"Marseille, Provence-Alpes-Côte d'Azur, France",
"Dijon, France",
"Lyon, France",
"Bitche, France",
"Gabarret, France",
"Toulon, France",
"Peronne, France",
"Gueret, Limousin, France",
"Montélimar, France",
"Bordeaux, France",
"Montpellier, Languedoc-Roussillon, France",
"Montélimar, France",
"Saint-Jean-Pied-de-Port, France",
"Le Mans, France",
"La Rochelle, France",
"Dourdan, France",
"Boulogne-sur-Mer, France",
"Saint Jean, France",
"L'Ile-d'Yeu, France",
"Strasbourg, France",
"Nantes, France",
"La Roche-sur-Foron, France",
"Monteux, France",
"Bordeaux, France",
"Saint-Fargeau, France",
"Rosporden, France",
"Reims, France",
"Strasbourg, France",
"Périgueux, France",
"Branges, France",
"Quimperlé, France",
"Mirande, France",
"Dijon, France",
"Limoges, France",
"Grenoble, France",
"Mont, France",
"La Rochelle, France",
"Vichy, France",
"Amiens, France",
"Arras, France",
"Marseille, France",
"Lille, France",
"Oloron-Sainte-Marie, France",
"Saint-Leu-la-Foret, France",
"Chauvigny, France",
"Saint-Malo, France",
"Bourgoin-Jallieu, France",
"Bayonne, Aquitaine , France",
"Aussillon, France",
"Bordeaux, France",
"Le Vigen, France",
"Brest, France",
"Guichen, France",
"Cherbourg-Octeville, Basse Normandie, France",
"Bellignat, France",
"Tonnerre, Bourgogne, France",
"Dreux, France",
"Angers, France",
"Alençon, France",
"Pau, France",
"Remiremont, Lorraine , France",
"Mantes-la-Jolie, France",
"Dijon, France",
"Bordeaux, France",
"Brive-la-Gaillarde, France",
"Torcy, France",
"Macon, France",
"Orange, France",
"Bourg-Argental, France",
"Bourg-les-Valence, France",
"Rumilly, France",
"Besançon, France",
"Paris, France",
"Gap, France",
"Aix-en-Provence, France",
"Graulhet, France",
"Thionville, France",
"Courcouronnes, France",
"Angoulême, France",
"Saint Martin, France",
"Narbonne, France",
"Lure, France",
"Valbonne, France",
"Épernay, France",
"Grenoble, France",
"Montargis, France",
"Limoges, France",
"Borville, France",
"Toulouse, France",
"Montbrison, France",
"Limoges, France",
"Poitiers, France",
"Besançon, Franche-Comté, France",
"Nice, France",
"Castres, France",
"Rennes, France",
"Oullins, France",
"Albi, France",
"Fontenay-le-Comte, Pays de la Loire, France",
"Étampes, France",
"Port-Sainte-Marie, France",
"Chateaubriant, France",
"Pont-Saint-Esprit, France",
"Besançon, France",
"Lisieux, Basse Normandie, France",
"Gap, France",
"Avignon, France",
"Dinan, France",
"Clermont-Ferrand, France",
"Tours, France",
"Combourg, France",
"Sainte-Suzanne, France",
"Montpellier, France",
"Oloron-Sainte-Marie, France",
"Caen, Basse Normandie, France",
"Paris, France",
"Pont-a-Mousson, France",
"Saint Denis, France",
"Dunkerque, France",
"Brest, France",
"Chalon-sur-Saône, France",
"Rennes, France",
"Toulouse, France",
"Limoges, France"
]


require('async').map(cities, function(city, coords) {
    getCoords(city)
        .then((coords, cities) => {
            //var infoz = [];
            infoz = [city, coords];
            //infoz.push(results)
            //results = (city + " : " + JSON.stringify(coords));
            //infoz = (infoz[0])
            //console.log(infoz)
            data = {
                "city": infoz[0],
                "coords": infoz[1]
            }
            //console.log(data)
            //return data
            fs.appendFile("final/france_coords.json", JSON.stringify(data), function(err) {
                if (err) {
                    return console.log(err);
                }
                //console.log("The file was saved!");
            });

        });


});