{
    "startUrl": [
"http://tunein.com/radio/Argentina-r100294/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-1000:7]",
"http://tunein.com/radio/Bolivia-r100308/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-129:7]",
"http://tunein.com/radio/Sao-Paulo-r100563/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-810:7]",
"http://tunein.com/radio/Acre-r101758/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-19:7]",
"http://tunein.com/radio/Alagoas-r100584/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Amazonas-r100581/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-32:7]",
"http://tunein.com/radio/Bahia-r100561/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-328:7]",
"http://tunein.com/radio/Bauru-r101761/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-50:7]",
"http://tunein.com/radio/Campina-Grande-r100570/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-34:7]",
"http://tunein.com/radio/Campinas-r100577/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-140:7]",
"http://tunein.com/radio/Cear%C3%A1-r100574/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-284:7]",
"http://tunein.com/radio/Distrito-Federal-r100559/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-59:7]",
"http://tunein.com/radio/Esp%C3%ADrito-Santo-r100582/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Foz-do-Iguacu-r101207/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-34:7]",
"http://tunein.com/radio/Goi%C3%A1s-r100579/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-205:7]",
"http://tunein.com/radio/Joinville-r101739/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-46:7]",
"http://tunein.com/radio/Londrina-r100588/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-57:7]",
"http://tunein.com/radio/Maranh%C3%A3o-r100572/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-58:7]",
"http://tunein.com/radio/Mato-Grosso-r100565/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-106:7]",
"http://tunein.com/radio/Mato-Grosso-do-Sul-r100569/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-123:7]",
"http://tunein.com/radio/Minas-Gerais-r100585/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-596:7]",
"http://tunein.com/radio/Paran%C3%A1-r100567/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-414:7]",
"http://tunein.com/radio/Para%C3%ADba-r100568/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-114:7]",
"http://tunein.com/radio/Par%C3%A1-r100558/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-97:7]",
"http://tunein.com/radio/Pernambuco-r100586/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-235:7]",
"http://tunein.com/radio/Piau%C3%AD-r100571/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-85:7]",
"http://tunein.com/radio/Porto-Alegre-r100580/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-542:7]",
"http://tunein.com/radio/Recife-r102235/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-95:7]",
"http://tunein.com/radio/Ribeirao-Preto-r100578/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-56:7]",
"http://tunein.com/radio/Rio-Grande-do-Norte-r100575/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-94:7]",
"http://tunein.com/radio/Rio-de-Janeiro-r100587/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-226:7]",
"http://tunein.com/radio/Rond%C3%B4nia-r101760/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-56:7]",
"http://tunein.com/radio/Roraima-r101921/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-15:7]",
"http://tunein.com/radio/Santa-Catarina-r100562/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-292:7]",
"http://tunein.com/radio/Santos-r100576/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-159:7]",
"http://tunein.com/radio/Sao-Jose-dos-Campos-r100573/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-43:7]",
"http://tunein.com/radio/Sergipe-r100583/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-52:7]",
"http://tunein.com/radio/Sorocaba-r100564/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-66:7]",
"http://tunein.com/radio/Sumare-Americana-r100566/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-140:7]",
"http://tunein.com/radio/Tocantins-r101922/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-42:7]",
"http://tunein.com/radio/Uberlandia-r100560/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-27:7]",
"http://tunein.com/radio/Chile-r101229/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-127:7]",
"http://tunein.com/radio/Colombia-r100325/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-251:7]",
"http://tunein.com/radio/Ecuador-r100335/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-173:7]",
"http://tunein.com/radio/Falkland-Islands-r100340/?other=true",
"http://tunein.com/radio/French-Guiana-r100343/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-12:7]",
"http://tunein.com/radio/Guyana-r101247/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-10:7]",
"http://tunein.com/radio/Paraguay-r100395/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-138:7]",
"http://tunein.com/radio/Peru-r101285/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-211:7]",
"http://tunein.com/radio/Suriname-r101299/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-36:7]",
"http://tunein.com/radio/Uruguay-r101310/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-144:7]",
"http://tunein.com/radio/Venezuela-r101313/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-197:7]"]


,
    "selectors": [{
        "parentSelectors": ["_root"],
        "type": "SelectorLink",
        "multiple": true,
        "id": "top_link",
        "selector": "a._tooltip",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorText",
        "multiple": false,
        "id": "station",
        "selector": "div.info h1",
        "regex": "",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorText",
        "multiple": false,
        "id": "city",
        "selector": "div.info-panel li:nth-of-type(1) span",
        "regex": "",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorLink",
        "multiple": false,
        "id": "email",
        "selector": "li.link-list a:nth-of-type(2)",
        "delay": ""
    }],
    "_id": "south_america"
}