{
    "startUrl": ["http://tunein.com/radio/Algeria-r100289/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-31:7]",
"http://tunein.com/radio/al-Jazair-r100525/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-11:7]",
"http://tunein.com/radio/Angola-r101220/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-25:7]",
"http://tunein.com/radio/Benin-r100997/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-12:7]",
"http://tunein.com/radio/Botswana-r100310/?other=true",
"http://tunein.com/radio/Burkina-Faso-r100314/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-13:7]",
"http://tunein.com/radio/Burundi-r100316/?other=true",
"http://tunein.com/radio/Cameroon-r101226/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-13:7]",
"http://tunein.com/radio/Cape-Verde-r101228/?other=true",
"http://tunein.com/radio/Central-African-Republic-r100320/?other=true",
"http://tunein.com/radio/Chad-r100321/?other=true",
"http://tunein.com/radio/Comoros-r100326/?other=true",
"http://tunein.com/radio/Congo-r100327/?other=true",
"http://tunein.com/radio/Cote-Divoire-r100330/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-16:7]",
"http://tunein.com/radio/DR-Congo-r101627/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-12:7]",
"http://tunein.com/radio/Djibouti-r101234/?other=true",
"http://tunein.com/radio/Egypt-r101236/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-33:7]",
"http://tunein.com/radio/Equatorial-Guinea-r100337/?other=true",
"http://tunein.com/radio/Eritrea-r100338/?other=true",
"http://tunein.com/radio/Ethiopia-r100339/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-10:7]",
"http://tunein.com/radio/Gabon-r101241/?other=true",
"http://tunein.com/radio/Gambia-r101242/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-12:7]",
"http://tunein.com/radio/Ghana-r101243/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-107:7]",
"http://tunein.com/radio/Guinea-r100351/?other=true",
"http://tunein.com/radio/Guinea-Bissau-r101246/?other=true",
"http://tunein.com/radio/Kenya-r100363/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-45:7]",
"http://tunein.com/radio/Lesotho-r101260/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-11:7]",
"http://tunein.com/radio/Liberia-r100371/?other=true",
"http://tunein.com/radio/Libya-r101261/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-15:7]",
"http://tunein.com/radio/Madagascar-r101264/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-18:7]",
"http://tunein.com/radio/Malawi-r100376/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-13:7]",
"http://tunein.com/radio/Mali-r101267/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-26:7]",
"http://tunein.com/radio/Mauritania-r101269/?other=true",
"http://tunein.com/radio/Mauritius-r101270/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-12:7]",
"http://tunein.com/radio/Mayotte-r100379/?other=true",
"http://tunein.com/radio/Morocco-r101276/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-21:7]",
"http://tunein.com/radio/Mozambique-r101277/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-10:7]",
"http://tunein.com/radio/Namibia-r100383/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-23:7]",
"http://tunein.com/radio/Niger-r101280/?other=true",
"http://tunein.com/radio/Nigeria-r101281/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-55:7]",
"http://tunein.com/radio/Reunion-r100400/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-34:7]",
"http://tunein.com/radio/Rwanda-r101288/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-13:7]",
"http://tunein.com/radio/Sao-Tome-Principe-r100406/?other=true",
"http://tunein.com/radio/Senegal-r101292/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-36:7]",
"http://tunein.com/radio/Seychelles-r100408/?other=true",
"http://tunein.com/radio/Sierra-Leone-r100409/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-8:7]",
"http://tunein.com/radio/Somalia-r101294/?other=true",
"http://tunein.com/radio/Cape-Town-r101104/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-23:7]",
"http://tunein.com/radio/Durban-r101105/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-15:7]",
"http://tunein.com/radio/East-London-r101100/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-9:7]",
"http://tunein.com/radio/Johannesburg-r101102/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-50:7]",
"http://tunein.com/radio/Port-Elizabeth-r101103/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-8:7]",
"http://tunein.com/radio/Pretoria-r101106/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-48:7]",
"http://tunein.com/radio/St-Helena-r100417/?other=true",
"http://tunein.com/radio/Sudan-r101298/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-15:7]",
"http://tunein.com/radio/Swaziland-r100421/?other=true",
"http://tunein.com/radio/Tanzania-r101303/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-55:7]",
"http://tunein.com/radio/Togo-r101305/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-12:7]",
"http://tunein.com/radio/Tunisia-r101307/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-26:7]",
"http://tunein.com/radio/Uganda-r100433/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-48:7]",
"http://tunein.com/radio/Western-Sahara-r100444/?other=true",
"http://tunein.com/radio/Zambia-r101316/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-33:7]",
"http://tunein.com/radio/Zimbabwe-r101317/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-8:7]"
],
    "selectors": [{
        "parentSelectors": ["_root"],
        "type": "SelectorLink",
        "multiple": true,
        "id": "top_link",
        "selector": "a._tooltip",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorText",
        "multiple": false,
        "id": "station",
        "selector": "div.info h1",
        "regex": "",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorText",
        "multiple": false,
        "id": "city",
        "selector": "div.info-panel li:nth-of-type(1) span",
        "regex": "",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorLink",
        "multiple": false,
        "id": "email",
        "selector": "li.link-list a:nth-of-type(2)",
        "delay": ""
    }],
    "_id": "africa"
}