http://tunein.com/radio/Agen-r101880/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-18:7]
http://tunein.com/radio/Aix-en-Provence-r101873/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-21:7]
http://tunein.com/radio/Albi-r101881/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-14:7]
http://tunein.com/radio/Amiens-r101860/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-25:7]
http://tunein.com/radio/Ch%C3%A9rie-FM-a38304/?other=true
http://tunein.com/radio/Nostalgie-a38318/?other=true
http://tunein.com/radio/NRJ-(France)-a38225/
http://tunein.com/radio/Radio-France-a33847/
http://tunein.com/radio/RCF-France-a38217/
http://tunein.com/radio/RFI-France-a33814/
http://tunein.com/radio/RFO-(France)-a38330/
http://tunein.com/radio/Rire--Chansons-a38391/




///=====



["http://tunein.com/radio/La-Rochelle-r101846/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Chartres-r101879/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Le-Mans-r101855/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Saint-Brieuc-r101856/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Toulouse-r100747/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Dijon-r101742/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Rouen-r100751/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Marseille-r100756/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Mont%c3%a9limar-r101864/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Deauville-r101854/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Annecy-r101866/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Saint-Tropez-r101872/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Paris-r100755/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Mulhouse-r101845/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Strasbourg-r101629/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Reims-r101842/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Aix-en-Provence-r101873/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Angers-r101857/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Angoul%c3%aame-r101870/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Bourges-r101847/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Saint-Malo-r101852/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Nantes-r100749/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Ch%c3%a2teauroux-r101841/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Nice-r101191/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Quimper-r101850/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Caen-r101844/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Amiens-r101860/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Orl%c3%a9ans-r101765/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Chalon-sur-Sa%c3%b4ne-r101886/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Cherbourg-r101853/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Calais-r101843/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Lyon-r100757/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Albi-r101881/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Toulon-r100752/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Troyes-r101867/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Rennes-r100753/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Poitiers-r101858/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Dunkirk-r101884/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Biarritz-r101875/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Grenoble-r100754/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Montlu%c3%a7on-r101885/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Narbonne-r101876/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Besan%c3%a7on-r101877/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Auxerre-r101848/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/N%c3%aemes-r101863/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Nevers-r101874/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/LIle-dYeu-r101871/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Lourdes-r101868/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Lille-r101741/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Clermont-Ferrand-r101766/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Avignon-r101763/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Brest-r101849/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Valenciennes-r101883/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Charleville-M%c3%a9zi%c3%a8res-r101882/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Bayonne-r101869/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Carcassonne-r101862/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Metz-r101878/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Lorient-r101851/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Bordeaux-r100748/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Limoges-r101859/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Perpignan-r101861/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Gap-r101865/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Tours-r101764/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Nancy-r101762/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Agen-r101880/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/France-National-c473075/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Saint-Etienne-r101767/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]",
"http://tunein.com/radio/Montpellier-r101740/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-150:7]"]

///=====
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]
?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-00:7]