var getCoords = require('city-to-coords');
var getCoords = require('city-to-coords');
var json2csv = require('json2csv');
var fs = require('fs')
var csvjson = require('csvjson');
cities = [
"Oran, Regionale de l'Ouest, Algeria",
"Mahdia, Tunisia",
"Lomé, Togo",
"Port Elizabeth, South Africa",
"Kampala, Uganda",
"Ikeja, Lagos, Nigeria",
"Sunyani, Ghana",
"Nairobi, Kenya",
"Malherbes, Port Louis, Mauritius",
"Nairobi, Kenya",
"Port Louis, Mauritius",
"Boukrim, Tunisia",
"Dakar, Senegal",
"Metu, Ethiopia",
"Cairo, Egypt",
"Matola, Mozambique",
"Sunyani, Ghana",
"Johannesburg, South Africa",
"Klein Windhoek, Namibia",
"Johannesburg, South Africa",
"Gaga, Ghana",
"Kibera, Kenya",
"Combani, Mayotte",
"Mombasa, Kenya",
"Kinshasa, DR Congo",
"Moroni, Comoros",
"Saint-Leu, Reunion",
"East London, South Africa",
"Kampala, Uganda",
"Mzuzu, Malawi",
"Kumasi, Ghana",
"Jijel, Algeria",
"Bel Ombre, Mauritius",
"Abuja, Nigeria",
"Bukavu, DR Congo",
"Johannesburg, South Africa",
"Johannesburg, South Africa",
"Maputo, Mozambique",
"Lusaka, Lusaka, Zambia",
"Johannesburg, South Africa",
"Tema, Ghana",
"Bujumbura, Burundi",
"Kampala, Uganda",
"Jamestown, St. Helena",
"Johannesburg, South Africa",
"Kampala, Uganda",
"Dakar, Senegal",
"Cairo, Egypt",
"Kisaasi, Uganda",
"Lomé, Togo",
"Kigali, Rwanda",
"Kano, Nigeria",
"Zanzibar, Tanzania",
"Houghton, South Africa",
"Lusaka, Zambia",
"Takoradi, Ghana",
"Asokoro, Nigeria",
"Banjul, Gambia",
"Blantyre, Southern, Malawi",
"Saint-Pierre, Reunion",
"Lagos, Nigeria",
"Kampala, Uganda",
"Saint-Andre, Reunion",
"Port Louis, Port Louis, Mauritius",
"Accra, Ghana",
"Port Elizabeth, South Africa",
"Accra, Ghana",
"Zaghouan, Tunisia",
"Midrand, GA, South Africa",
"Beira, Mozambique",
"Dakar, Senegal",
"Dar es Salaam, Tanzania",
"Sidi Bou Said, Tunisia",
"Kigali, Rwanda",
"Johannesburg, South Africa",
"Klein Windhoek, Namibia",
"Port Louis, Mauritius",
"Cape Town, South Africa",
"Dakar, Senegal",
"Banghazi, Libyan Arab Jamahiriya",
"Monze, Zambia",
"Malherbes, Mauritius",
"Klein Windhoek, Namibia",
"Johannesburg, South Africa",
"Klein Windhoek, Namibia",
"Port Louis, Mauritius",
"Muizenberg, South Africa",
"Dar Es Salaam, Tanzania",
"Nairobi, Nairobi, Kenya",
"Johannesburg, South Africa",
"Tamale, Ghana",
"Chipata, Zambia",
"Mbale, Uganda",
"Mityana, Uganda",
"Cape Town, South Africa",
"Durban, South Africa",
"Saint-Denis, Reunion",
"Kigali, Rwanda",
"Yaoundé, Cameroon",
"Cape Town, South Africa",
"Windhoek, Namibia",
"Cape Town, South Africa",
"Cape Town, South Africa",
"Kaolack, Senegal",
"Le Port, Reunion",
"Casablanca, Morocco",
"Johannesburg, South Africa",
"Johannesburg, South Africa",
"Santa Isabel, Equatorial Guinea",
"Lomé, Togo",
"Conakry, Guinea",
"Kumasi, Ghana",
"Yamoussoukro, Côte d'Ivoire",
"Rivonia, South Africa",
"Casablanca, Morocco",
"Akumadan, Ghana",
"Accra, Ghana",
"Apac, Uganda",
"Mpumalanga, South Africa",
"Cape Town, South Africa",
"Ngong, Nairobi, Kenya",
"Dzoumogne, Mayotte",
"Johannesburg, South Africa",
"Victoria, Seychelles",
"Remada, Tunisia",
"Ouagadougou, Burkina Faso",
"Waterloo, Sierra Leone",
"Accra, Ghana",
"Bordj El Bahri, Algeria",
"Machakos, Kenya",
"Accra, Accra, Ghana",
"Dar es Salaam, Tanzania",
"Sembabule, Uganda",
"Blantyre, Malawi",
"Katima Mulilo, Namibia",
"Benin City, Nigeria",
"Cairo, Egypt",
"Eldoret, Kenya",
"Bangui, Central African Republic",
"Cairo, Egypt",
"Aba, Nigeria",
"Gaborone, Botswana",
"Mtwara, Tanzania",
"Tabora, Tanzania",
"Johannesburg, South Africa",
"Durban North, South Africa",
"Durban, South Africa",
"Nairobi, Kenya",
"Antananarivo, Madagascar",
"Nairobi, Kenya",
"Tabora, Tanzania",
"Ngara, Tanzania",
"Agadir, Morocco",
"Cape Town, South Africa",
"Windhoek, Namibia",
"Mbabane, Swaziland",
"Blantyre, Malawi",
"Cairo, Egypt",
"Kumasi, Ghana",
"Maputo, Mozambique",
"Kololi, Gambia",
"Windhoek, Namibia",
"Cairo, Egypt",
"Kumasi, Ghana",
"Kampala, Uganda",
"Kigali, Kigali, Rwanda",
"Livingstone, Zambia",
"Lomé, Togo",
"Kampala, Uganda",
"Johannesburg, South Africa",
"Cape Town, South Africa",
"Accra, Ghana",
"Bangui, Central African Republic",
"Tesano, Ghana",
"Lagos, Nigeria",
"Cotonou, Benin",
"Zanzibar, Tanzania",
"Cairo, Egypt",
"Antananarivo, Madagascar",
"Saint-Philippe, Reunion",
"Atlantis, South Africa",
"Johannesburg, South Africa",
"Victoria, Seychelles",
"Nairobi, Kenya",
"Morogoro, Tanzania",
"Durban, South Africa",
"Dar Es Salaam, Tanzania",
"Gaborone, Botswana",
"Lomé, Togo",
"Kitwe, Zambia",
"Aflou, Algeria",
"Khartoum, Sudan",
"Luanda, Luanda, Angola",
"Lagos, Nigeria",
"Accra, Ghana",
"Agona Swedru , Ghana",
"Douala, Cameroon",
"Dar es Salaam, Tanzania",
"Dakar, Senegal",
"Accra, Ghana",
"Kita, Mali, Mali",
"Algiers, Algiers, Algeria",
"Yaoundé, Cameroon",
"Maputo, Em primeiro lugar em todo lugar, Mozambique",
"Antananarivo, Madagascar",
"Blantyre, Malawi",
"Kampala, Uganda",
"Accra, Ghana",
"Kinshasa, DR Congo",
"Bunso, Ghana",
"Zanzibar, Tanzania",
"Kumasi, Ghana",
"Accra, Ghana",
"Sunyani, Ghana",
"Kinshasa, DR Congo",
"Pretoria, South Africa",
"Tygerberg Hills, South Africa",
"Klein Windhoek, Namibia",
"Kano, Nigeria",
"Khartoum, Sudan",
"Kitwe, Zambia",
"Harare, Zimbabwe",
"Manapany-les Hauts, Le Tampon, Reunion",
"Maputo, Mozambique",
"Takoradi, Ghana",
"Johannesburg, South Africa",
"Kitwe, Zambia",
"Dar es Salaam, Tanzania",
"Cape Town, South Africa",
"Mangochi, Malawi",
"Lagos, Nigeria",
"Saida, Algeria",
"Iringa, Tanzania",
"Johannesburg, South Africa",
"Victoria, Seychelles",
"Johannesburg, South Africa",
"Somanya, Ghana",
"Ouagadougou, Burkina Faso",
"Dar es Salaam, Tanzania",
"Yaounde, Cameroon",
"Kabwe, Zambia",
"Johannesburg, South Africa",
"Johannesburg, South Africa",
"Lomé, Togo",
"Kigali, Rwanda",
"Hurghada, Egypt",
"Kigali, Rwanda",
"Nairobi, Nairobi, Kenya",
"Kigali, Rwanda",
"Tamale, Ghana",
"Bonto, Gambia",
"Sere Kunda, Gambia",
"Kumasi, Ghana",
"Teso, Uganda",
"Arua, Uganda",
"Accra, Accra, Ghana",
"East London, South Africa",
"Omdurman, Sudan",
"Zomba, Malawi",
"Johannesburg, South Africa",
"Port Louis, Mauritius",
"Johannesburg, South Africa",
"Porto-Novo, Benin",
"Victoria, Seychelles",
"Khartoum, Sudan",
"Dar es Salaam, Tanzania",
"Chipata, Northeast, Zambia",
"Iringa, Tanzania",
"Nairobi, Nairobi, Kenya",
"Faravohitra, Antananarivo, Madagascar",
"Edinburgh of the Seven Seas, St. Helena",
"Klein Windhoek, Namibia",
"Randburg, South Africa",
"Jamestown, St. Helena",
"Dar es Salaam, Tanzania",
"Algiers, Algeria",
"Arusha, Arusha Region, Tanzania",
"Kumasi, Ghana",
"Dakar, Senegal",
"Avoca, Zimbabwe",
"Johannesburg, South Africa",
"Antananarivo, Madagascar",
"Eldoret, Kenya",
"Mbarara, Mbarara, Uganda",
"Kenyasi, Ghana",
"Boukrim, Tunisia",
"Gafsa, Tunisia",
"Eldoret, Kenya",
"Durban, South Africa",
"Ouagadougou, Ouagadougou, Burkina Faso",
"Johannesburg, South Africa",
"Abidjan, Côte d'Ivoire",
"Kampala, Mbarara, Uganda",
"Kumasi, Ghana",
"Accra, Ghana",
"Kampala, Uganda",
"Kampala, Uganda",
"Dar es Salaam, Tanzania",
"Antananarivo, Madagascar",
"Cape Coast, Ghana",
"Pretoria, Pretoria, South Africa",
"Port Elizabeth, South Africa",
"Sétif, Algeria",
"Johannesburg, South Africa",
"Tarkwa, Ghana",
"Abeokuta, Nigeria",
"East London, Eastern Cape Prov., South Africa",
"Kitwe, Zambia",
"Douala, Cameroon",
"Accra, Ghana",
"Accra, Ghana",
"Port Elizabeth, South Africa",
"Dakar, Senegal",
"Luanda, Luanda, Angola",
"Morogoro, Tanzania",
"Freetown, Sierra Leone",
"Luanda, Angola",
"Addis Abeba, Ethiopia",
"Saint-Paul, Le Port/Saint-Paul, Reunion",
"Gafsa, Tunisia",
"Vereeniging, South Africa",
"Ouagadougou, Burkina Faso",
"Nairobi, Kenya",
"Nairobi, Kenya",
"Port Louis, Mauritius",
"Pretoria, South Africa",
"Klein Windhoek, Namibia",
"Kaduna, Nigeria",
"Cairo, Egypt",
"Klein Windhoek, Namibia",
"Dar es Salaam, Dar es Salaam, Tanzania",
"Tripoli, Libyan Arab Jamahiriya",
"Banjul, Gambia",
"Tunis, Tunisia",
"Dakar, Senegal",
"Nakuru, Kenya",
"Durban, South Africa",
"Nairobi, Kenya",
"Port Harcourt, Nigeria",
"Durban, South Africa",
"Lomé, Togo",
"Kampala, Uganda",
"Tunis, Tunisia",
"Lomé, Togo",
"Klein Windhoek, Namibia",
"Cape Town, South Africa",
"Nairobi, Kenya",
"Techiman, Ghana",
"Sfax, Tunisia",
"Accra, Ghana",
"Johannesburg, South Africa",
"Ouagadougou, Burkina Faso",
"Lusaka, Lusaka, Zambia",
"Bangui, Central African Republic",
"Accra, Ghana",
"Kaloko, Zambia",
"Nairobi, Kenya",
"Kigali, Rwanda",
"Lagos, Nigeria",
"Soweto, South Africa",
"Kigali, Rwanda",
"Bogoso, Ghana",
"Yaounde, Cameroon",
"Tunis, Tunisia",
"Dakar, Senegal",
"Ikosi, Nigeria",
"Yenagoa, Nigeria",
"Abidjan, Côte d'Ivoire",
"Citronelle, Rodrigues Island, Mauritius",
"Abidjan, Côte d'Ivoire",
"Nouakchott, Mauritania",
"Cotonou, Benin",
"Stellenbosch, South Africa",
"Gafsa, Tunisia",
"Lagos, Nigeria",
"Nairobi, Kenya",
"Nouakchott, Mauritania",
"Abuja, Nigeria",
"Dar Es Salaam, Tanzania",
"Omdurman, Sudan",
"Yaoundé, Cameroon",
"Kampala, Uganda",
"Annaba, Algeria",
"Accra, Ghana",
"Pretoria, South Africa",
"Lusaka, Lusaka, Zambia",
"Algiers , Algeria",
"Koulikoro, Mali",
"Moshi, Tanzania",
"Johannesburg, South Africa",
"Dakar, Senegal",
"Lavumisa, Swaziland",
"Lagos, Nigeria",
"Accra, Ghana",
"Kampala, Uganda",
"Saint-Denis, Reunion",
"Sunyani, Ghana",
"Cairo, Egypt",
"Kano, Nigeria",
"Dar es Salaam, Tanzania",
"Casablanca, Morocco",
"Saint-Denis, Reunion",
"Nairobi, Kenya",
"Wad Madani, Sudan",
"Takoradi, Ghana",
"Kumasi, Ghana",
"Gaborone, Botswana",
"NkawKaw, KW, Ghana",
"Kampala, Uganda",
"Lagos, Nigeria",
"Accra, Ghana",
"Berekum, Ghana",
"Blantyre, Malawi",
"Koforidua, Ghana",
"Antalaha, Madagascar",
"Kumasi, Ghana",
"Kigali, Rwanda",
"Limuru, Nairobi, Kenya",
"Gaborone, Botswana",
"Antananarivo, Madagascar",
"Masaka, Uganda",
"Dar es Salaam, Tanzania",
"Luanda, Angola",
"Dakar, Senegal",
"Nairobi, Kenya",
"Ouagadougou, Burkina Faso",
"Mombasa, Mombasa, Kenya",
"Kisumu, Kenya",
"Kumasi, Ghana",
"Khartoum, Sudan",
"East London, South Africa",
"LE PORT, Reunion",
"Fizi, DR Congo",
"Accra, Ghana",
"Dakar, Senegal",
"Lusaka, Zambia",
"Bamako, Mali",
"Accra, Ghana",
"Kitale, Kenya",
"Saint-Denis, Reunion",
"Farafenni, Gambia",
"Diebougou, Burkina Faso",
"Johannesburg, South Africa",
"Abeokuta, Nigeria",
"Kumasi, Ghana",
"Kampala, Kampala, Uganda",
"Freetown, Sierra Leone",
"Johannesburg, South Africa",
"Dar es Salaam, Tanzania",
"Maputo, Mozambique",
"Abuja, Nigeria",
"Ikeja, Nigeria",
"Tunis, Tunisia",
"Sekondi-Takoradi, Ghana",
"Tanga, Tanzania",
"Mamba, FM, Uganda",
"Bujumbura, Burundi",
"Luanda, Angola",
"Niamey, Niger",
"Benghazi, Libyan Arab Jamahiriya",
"Goaso, Ghana",
"Bujumbura, Burundi",
"'Ain Temouchent, Algeria",
"Arusha, Tanzania",
"Lusaka, Zambia",
"Lagos, Nigeria",
"Kumasi, Ghana",
"Cairo, Egypt",
"Nouakchott, Mauritania",
"Port Louis, Mauritius",
"Luanda, Angola",
"Lagos, Nigeria",
"Nakuru, Kenya",
"Dakar, Senegal",
"Sunyani, Ghana",
"Dala, Nigeria",
"Mwanza, Tanzania",
"Kumasi, Ghana",
"Tripoli, Libyan Arab Jamahiriya",
"Freetown, Sierra Leone",
"Bamako, Bamako, Mali",
"Maputo, Mozambique",
"Takoradi, Ghana",
"Benghazi, Libyan Arab Jamahiriya",
"Port Harcourt, Rivers, Nigeria",
"Biskra, Algeria",
"Kumasi, Ghana",
"Kisumu, Kenya",
"Johannesburg, South Africa",
"N'Djamena, Chad",
"Bellville, South Africa",
"Remada, Tunisia",
"Tygerberg Hills, South Africa",
"Kigali, Rwanda",
"Touba, Mali",
"Parsons Hill, South Africa",
"Abidjan, Côte d'Ivoire",
"Masaka, Uganda",
"Nairobi, Kenya",
"Conakry, Guinea",
"Moroni, Comoros",
"Addis Abeba, Ethiopia",
"Bamako, Mali",
"Saint-Denis, Reunion",
"Johannesburg, South Africa",
"Kigali, Kigali, Rwanda",
"Skikda, Algeria",
"Kaduna, Nigeria",
"Yaoundé, Cameroon",
"Kano, Nigeria",
"Dakar, Senegal",
"Saint-Denis, Reunion",
"Kinshasa, DR Congo",
"Berekum, Ghana",
"KONONGO, Ghana",
"Isheri-Olofin, Nigeria",
"Arua, Uganda",
"Casablanca, Morocco",
"Durban, South Africa",
"Mombasa, Kenya",
"Kitwe, Zambia",
"Kumasi, Ghana",
"Accra, Ghana",
"Freetown, Sierra Leone",
"Mbarara, Uganda",
"Tunis, Tunisia",
"Nairobi, Kenya",
"Bangui, Central African Republic",
"Toamasina, Madagascar",
"Accra, Ghana",
"Japekrom, Ghana",
"Soroti, Uganda",
"Ilorin, Nigeria",
"Douala, Cameroon",
"Johannesburg, South Africa",
"Maseru, Lesotho",
"Durban, South Africa",
"Ouagadougou, Ouagadougou, Burkina Faso",
"La Riviere, Reunion",
"Moyamba, Sierra Leone",
"Addis Ababa, Ethiopia",
"Johannesburg, South Africa",
"Cape Town, South Africa",
"Lagos, Nigeria",
"Kitwe, Zambia",
"Helderberg, South Africa",
"Accra, Ghana",
"Libreville, Gabon",
"Lagos, Nigeria",
"Abuja, Nigeria",
"Bolgatanga, Ghana",
"Khartoum, Sudan",
"Kinshassa, Congo",
"Port Harcourt, Nigeria",
"Bamako, Mali",
"Rabat, Morocco",
"Soroti, Uganda",
"Tangier, Morocco",
"Iringa, Tanzania",
"Enugu, Nigeria",
"Banjul, Gambia",
"Ibadan, Nigeria",
"Johannesburg, South Africa",
"El Kef, Tunisia",
"Arusha, Tanzania",
"Sousse, Tunisia",
"Accra, Greater Accra, Ghana",
"Bellville, South Africa",
"Algiers, Algeria",
"Kigali, Rwanda",
"Gabès, Tunisia",
"Bamako, Mali"

]
require('async').map(cities, function(city, coords) {
    getCoords(city)
        .then((coords, cities) => {
            //var infoz = [];
            infoz = [city, coords];
            //infoz.push(results)
            //results = (city + " : " + JSON.stringify(coords));
            //infoz = (infoz[0])
            //console.log(infoz)
            data = {
                "city": infoz[0],
                "coords": infoz[1]
            }
            //console.log(data)
            //return data
            fs.appendFile("africa_coords.json", JSON.stringify(data), function(err) {
                if (err) {
                    return console.log(err);
                }
                //console.log("The file was saved!");
            });

        });


});