module.exports = [

"Pago Pago, AS",
"Auckland, New Zealand",
"Matavera, Cook Islands",
"New Plymouth, New Zealand",
"Whakatane, New Zealand",
"Auckland, New Zealand",
"Masterton, New Zealand",
"Suva, Fiji",
"St George's Basin, NSW, Australia",
"Port Moresby, Papua New Guinea",
"Hastings, New Zealand",
"Kadina, SA, Australia",
"Papeete, French Polynesia",
"Wanaka, New Zealand",
"Deniliquin, NSW, Australia",
"Auckland, New Zealand",
"Paraparaumu, New Zealand",
"Papatoetoe, New Zealand",
"Whangarei, New Zealand",
"Invercargill, New Zealand",
"North Mount Egmont, New Zealand",
"Lightning Ridge, NSW, Australia",
"Invercargill, New Zealand",
"Canberra, ACT, Australia",
"Lower Hutt, New Zealand",
"Auckland, New Zealand",
"Kingaroy, QLD, Australia",
"Wanaka, New Zealand",
"Barrington, NSW, Australia",
"Seymour, VIC, Australia",
"Masterton, New Zealand",
"Rotorua, New Zealand",
"Kingaroy, QLD, Australia",
"Auckland, New Zealand",
"Te Aroha, New Zealand",
"Tumut, NSW, Australia",
"Napier, New Zealand",
"Hagåtña, GU",
"Marlborough , New Zealand",
"Blenheim, Marlborough, New Zealand",
"Auckland, New Zealand",
"Whangarei, New Zealand",
"Dunedin, New Zealand",
"Newlands, New Zealand",
"Auckland, New Zealand",
"Christchurch, New Zealand",
"Wanaka, New Zealand",
"Tokoroa, New Zealand",
"Auckland, New Zealand",
"Oneroa, New Zealand",
"Burwood, New Zealand",
"Nelson, New Zealand",
"Echuca, VIC, Australia",
"Wellington, New Zealand",
"Bourke, NSW, Australia",
"Martinborough, New Zealand",
"Wellington, New Zealand",
"Augusta, WA, Australia",
"Manukau City, New Zealand",
"Christchurch, New Zealand",
"Perth, WA, Australia",
"Barrigada, GU",
"Adelaide Lead, VIC, Australia",
"Kinglake, VIC, Australia",
"Palmerston North, New Zealand",
"Agat, GU",
"Wanganui, New Zealand",
"Rotorua, New Zealand",
"Mudgee, NSW, Australia",
"Picton, Marlborough, New Zealand",
"Hamilton, New Zealand",
"Melbourne, VIC, Australia",
"Port Moresby, Papua New Guinea",
"Auckland, New Zealand",
"Dunedin, New Zealand",
"Auckland, New Zealand",
"Narrogin, WA, Australia",
"Hastings, New Zealand",
"Nelson, New Zealand",
"Papeete, French Polynesia",
"Palmerston North, New Zealand",
"Wellington, New Zealand",
"Hastings, New Zealand",
"Sydney, NSW, Australia",
"Rangiora, New Zealand",
"Tauranga, New Zealand",
"Dunedin, New Zealand",
"Auckland, New Zealand",
"Tenterfield, NSW, Australia",
"Otematata, New Zealand",
"Eyre Creek, New Zealand",
"Kempsey, NSW, Australia",
"Raglan, New Zealand",
"Pago Pago, AS",
"Papeete, French Polynesia",
"Rotorua, New Zealand",
"Katoomba, NSW, Australia",
"Gove, NT, Australia",
"Rotorua, New Zealand",
"Wellington, New Zealand",
"Katanning, WA, Australia",
"Whangarei, New Zealand",
"Eildon, VIC, Australia",
"Alexandra, Central Otago, New Zealand",
"Gisborne, New Zealand",
"New Plymouth, New Zealand",
"Grafton, NSW, Australia",
"Hamilton, New Zealand",
"Palmerston North, New Zealand",
"Dunedin, New Zealand",
"Timaru, New Zealand",
"Grafton, NSW, Australia",
"Levin, New Zealand",
"Timaru, New Zealand",
"Wellington, New Zealand",
"Hamilton, New Zealand",
"Auckland, New Zealand",
"Tara, QLD, Australia",
"Auckland, New Zealand",
"Sydney, NSW, Australia",
"Wellington, New Zealand",
"Kaiapoi, New Zealand",
"Gisborne, New Zealand",
"Roxby Downs, SA, Australia",
"Dunedin, New Zealand",
"Apollo Bay, VIC, Australia",
"Gisborne, New Zealand",
"Invercargill, New Zealand",
"Suva, Fiji",
"Bridgetown, WA, Australia",
"Auckland, New Zealand",
"Oatlands, TAS, Australia",
"Meekatharra, WA, Australia",
"Bantam Village, Cocos (Keeling) Islands",
"Cooma, NSW, Australia",
"Moranbah, QLD, Australia",
"Sydney, NSW, Australia",
"Hastings, New Zealand",
"Roma, QLD, Australia",
"Wanganui, Taranaki, New Zealand",
"Narrabri, NSW, Australia",
"Auckland, New Zealand",
"Bright, VIC, Australia",
"Tumon, GU",
"Mangawhai, New Zealand",
"Auckland, New Zealand",
"Palmerston North, New Zealand",
"Otaki, New Zealand",
"Dunedin, New Zealand",
"Waikanae, New Zealand",
"Porirua, New Zealand",
"Peak Hill, NSW, Australia",
"Hamilton, New Zealand",
"Tauranga, New Zealand",
"Wellington, New Zealand",
"Nadi, Fiji",
"Christchurch, New Zealand",
"Sydney, NSW, Australia",
"Auckland, New Zealand",
"Drumsite, Christmas Island",
"Murrayville, VIC, Australia",
"Christchurch, New Zealand",
"Woori Yallock, VIC, Australia",
"Whakatane, New Zealand",
"Pirae, French Polynesia",
"Cardiff, New Zealand",
"Mangilao, Guam",
"Wellington, New Zealand",
"Auckland, New Zealand",
"Wellington, New Zealand",
"Invercargill, New Zealand",
"Thames, New Zealand",
"Kyneton, VIC, Australia",
"Christchurch, New Zealand",
"Suva, Fiji",
"Nelson, New Zealand",
"Whangarei, New Zealand",
"Hauraki, New Zealand",
"Wellington, New Zealand",
"North Mount Egmont, New Zealand",
"Ngaruawahia, New Zealand",
"Auckland, New Zealand",
"Papeete, French Polynesia",
"Maryborough, VIC, Australia",
"Auckland, New Zealand",
"Suva, Fiji",
"Matamata, New Zealand",
"Wainui, New Zealand",
"Tauranga, New Zealand",
"Auckland, New Zealand",
"Blenheim, New Zealand",
"Palmerston North, New Zealand",
"Te Kuiti, New Zealand",
"Wellington, New Zealand",
"Palmerston North, New Zealand",
"Nuku'alofa, Tonga",
"Gisborne, New Zealand",
"Otaki, New Zealand",
"Perth, WA, Australia",
"Whitianga, New Zealand",
"Christchurch, New Zealand",
"Rotorua, New Zealand",
"Nelson, New Zealand",
"Whangarei, New Zealand",
"Hamilton, New Zealand",
"Lyttelton, New Zealand",
"Tauranga, New Zealand",
"North Mount Egmont, New Zealand",
"Leone, AS",
"Auckland, New Zealand",
"Wellington, New Zealand",
"Eden, NSW, Australia",
"Sydney, NSW, Australia",
"Wellington, New Zealand",
"Whangamata, New Zealand",
"Sydney, NSW, Australia",
"Melbourne, VIC, Australia",
"Te Aroha, New Zealand",
"Gisborne, New Zealand",
"Gunnedah, NSW, Australia",
"Dunedin, New Zealand",
"Christchurch, New Zealand",
"Melbourne, VIC, Australia",
"Christchurch, New Zealand",
"Onetangi, New Zealand",
"Whangarei, New Zealand",
"Wanganui, New Zealand",
"Auckland, New Zealand",
"Alexandra, New Zealand",
"Auckland, New Zealand",
"Dunedin, New Zealand",
"North Mount Egmont, New Zealand",
"Hamilton, New Zealand",
"Gloucester, NSW, Australia",
"Ayr, QLD, Australia",
"Seymour, VIC, Australia",
"Wanganui, New Zealand",
"Palmerston North, New Zealand",
"Hawera, New Zealand",
"Hamilton, New Zealand",
"Coromandel, New Zealand",
"Tenterfield, NSW, Australia",
"Christchurch, New Zealand",
"Dunedin, New Zealand",
"Gisborne, New Zealand",
"Samberigi, Papua New Guinea",
"Dunedin, New Zealand",
"Te Aroha, New Zealand",
"Nelson, New Zealand",
"Moruya, NSW, Australia",
"Wellington, New Zealand",
"Piha, New Zealand",
"North Mount Egmont, New Zealand",
"New Plymouth, New Zealand",
"Bourke, NSW, Australia",
"Adelaide, SA, Australia",
"Wellington, New Zealand",
"Christchurch, New Zealand",
"Kaikohe, New Zealand",
"Auckland, New Zealand",
"Auckland, New Zealand",
"Auckland, New Zealand",
"Whakatane, New Zealand",
"Invercargill, New Zealand",
"Palmerston North, New Zealand",
"Christchurch, New Zealand",
"Sydney, NSW, Australia",
"Hamilton, New Zealand",
"Lithgow, NSW, Australia",
"Wellington, New Zealand",
"Auckland, New Zealand",
"Paraparaumu, New Zealand",
"Wellington, New Zealand",
"Wondai, QLD, Australia",
"Auckland, New Zealand",
"Dunedin, New Zealand",
"Wellington, New Zealand",
"Picton, New Zealand",
"Northam, WA, Australia",
"Queenstown, New Zealand",
"Merredin, WA, Australia",
"Deepwater, NSW, Australia",
"Tauranga, New Zealand",
"Young, NSW, Australia",
"Toogoolawah, QLD, Australia",
"Hamilton, New Zealand",
"Wellington, New Zealand",
"New Plymouth, New Zealand",
"Kingaroy, QLD, Australia",
"Auckland, New Zealand",
"Tauranga, New Zealand",
"Tauranga, New Zealand",
"Inglewood, QLD, Australia",
"Murray Bridge, SA, Australia",
"Dunedin, New Zealand",
"Sydney, NSW, Australia",
"Kingsland, New Zealand",
"Cooma, NSW, Australia",
"Christchurch, New Zealand",
"Queenstown, New Zealand",
"North Mount Egmont, New Zealand",
"Kingston, Norfolk Island",
"Auckland, New Zealand",
"Nelson, New Zealand",
"Queenstown, New Zealand",
"Wellington, New Zealand",
"Oakura, New Zealand",
"Mata'utu, Wallis and Futuna Islands",
"Napier, New Zealand",
"Melbourne, VIC, Australia",
"Masterton, New Zealand",
"Garapan, MP",
"Kapunda, SA, Australia",
"Wanganui, New Zealand",
"Milton, QLD, Australia",
"Murray Bridge, SA, Australia",
"Wellington, New Zealand",
"Dannevirke, New Zealand",
"Te Aroha, New Zealand",
"Palmerston North, New Zealand",
"Whakatane, New Zealand",
"Invercargill, New Zealand",
"Peak Hill, NSW, Australia",
"Dargaville, New Zealand",
"Sydney, NSW, Australia",
"Gisborne, New Zealand",
"Wellington, New Zealand",
"Korumburra, VIC, Australia",
"Christchurch, New Zealand",
"Suva, Fiji",
"Napier, New Zealand",
"Paeroa, WA, New Zealand",
"Nelson, New Zealand",
"Flemington, New Zealand",
"Hamilton, New Zealand",
"Napier, New Zealand",
"Auckland, New Zealand",
"Deniliquin, NSW, Australia",
"Wellington, New Zealand",
"Tokoroa, New Zealand",
"Nelson, New Zealand",
"Port Vila, Vanuatu",
"Christchurch, New Zealand",
"Melbourne, VIC, Australia",
"Mansfield, VIC, Australia",
"Invercargill, Southland, New Zealand",
"Dumbea, New Caledonia",
"Adelaide, SA, Australia",
"Tauranga, New Zealand",
"Rotorua, New Zealand",
"Dunedin, New Zealand",
"Avarua, Cook Islands",
"Auckland, New Zealand",
"New Plymouth, New Zealand",
"Otaki, New Zealand",
"Wanganui, New Zealand",
"Nelson, New Zealand",
"Tauranga, New Zealand",
"Nelson, New Zealand",
"Kelburn, New Zealand",
"Timaru, New Zealand",
"Dunedin, New Zealand",
"Nelson, New Zealand",
"Rotorua, New Zealand",
"Palmerston North, New Zealand",
"Sydney, NSW, Australia",
"New Plymouth, New Zealand",
"Invercargill, New Zealand",
"Invercargill, New Zealand",
"Sydney, NSW, Australia",
"Wellington, New Zealand",
"Halls Creek, WA, Australia",
"Christchurch, New Zealand",
"Rotorua, New Zealand",
"Lautoka, Fiji",
"Wellington, New Zealand",
"Palmerston North, New Zealand",
"Napier, New Zealand",
"Sydney, NSW, Australia",
"Ruatoria, New Zealand",
"Papeete, French Polynesia",
"Spreydon, New Zealand",
"Queenstown, TAS, Australia",
"Shannon,  Horowhenua, New Zealand",
"Napier, New Zealand",
"Rotorua, New Zealand",
"Mangawhai, New Zealand",
"Christchurch, New Zealand",
"Auckland, New Zealand",
"Rotorua, New Zealand",
"Whakatane, New Zealand",
"Innisfail, QLD, Australia",
"Dunedin, New Zealand",
"Victor Harbor, SA, Australia",
"Christchurch, New Zealand",
"Hamilton, New Zealand",
"Maryborough, VIC, Australia",
"Tauranga, New Zealand",
"Alexandra, New Zealand",
"Paeroa, New Zealand",
"Christchurch, New Zealand",
"Suva, Fiji",
"Sydney, NSW, Australia",
"Auckland, New Zealand",
"Gore, New Zealand",
"Bridgetown, WA, Australia",
"Sydney, NSW, Australia",
"Napier, New Zealand",
"Tauranga, New Zealand",
"Bondi, NSW, Australia",
"Dunedin, New Zealand",
"Perth, WA, Australia",
"Timaru, New Zealand",
"Timaru, New Zealand",
"Faga`itua, AS",
"Rotorua, New Zealand",
"Porirua, New Zealand",
"Palmerston North, New Zealand",
"Yarraman, QLD, Australia",
"Brisbane, QLD, Australia",
"Lower Hutt, New Zealand",
"Sydney, NSW, Australia",
"Auckland, New Zealand",
"Christchurch, New Zealand",
"Dunedin, New Zealand",
"Pyrmont, NSW, Australia",
"Whangarei, New Zealand",
"Roma, QLD, Australia",
"Mabel Bush, New Zealand",
"Suva, Fiji",
"Sydney, NSW, Australia",
"Woodcocks, New Zealand",
"Christchurch, New Zealand",
"Whangarei, New Zealand",
"Blenheim, New Zealand",
"Wellington, New Zealand",
"Leeman, WA, Australia",
"Sydney, NSW, Australia",
"Dunedin, New Zealand",
"Invercargill, New Zealand",
"Gisborne, New Zealand",
"Christchurch, New Zealand",
"Gisborne, New Zealand",
"Hamilton, New Zealand",
"Alexandra, New Zealand",
"Goondiwindi, QLD, Australia",
"Settlement, Christmas Island",
"Gisborne, New Zealand",
"Nelson, New Zealand",
"Waipukurau, New Zealand",
"Invercargill, New Zealand",
"Richmond, QLD, Australia",
"Auckland, New Zealand",
"Timaru, New Zealand",
"Tauranga, New Zealand",
"Ponsonby, New Zealand",
"Christchurch, New Zealand",
"Koror, Palau",
"Colac, VIC, Australia",
"Matamau, New Zealand",
"Alexandra, New Zealand",
"Auckland, New Zealand",
"Auckland, New Zealand",
"Suva, Fiji",
"Invercargill, New Zealand",
"Melbourne, VIC, Australia",
"Saint Helens, TAS, Australia",
"Kaikohe, New Zealand",
"Christchurch, New Zealand",
"Auckland, New Zealand",
"Sydney, NSW, Australia"
]