{
    "startUrl": [
"http://tunein.com/radio/stations/ABC-(Australia)-a38206/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Australian-Capital-Territory-r101574/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/New-South-Wales-r101569/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Northern-Territory-r101570/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Queensland-r100504/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/stations/Radio-Australia-a33804/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/South-Australia-r101571/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Tasmania-r101573/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Victoria-r101572/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Western-Australia-r101568/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-100:7]",
"http://tunein.com/radio/Auckland-r100994/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Christchurch-r101618/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Coromandel-r102288/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Dunedin-r101619/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Gisborne-r101621/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Hamilton-r101725/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Hastings-r101721/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Invercargill-r101623/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Nelson-r101719/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/New-Plymouth-r101622/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Otago-r102283/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Palmerston-North-r101723/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Queenstown-r101720/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/stations/RNZ-New-Zealand-a33827/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Rotorua-r101724/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Ruatoria-r101728/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Tauranga-r101738/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Timaru-r101729/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Wanganui-r101726/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Wellington-r101620/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Whakatane-r101727/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/Whangarei-r101722/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-80:7]",
"http://tunein.com/radio/American-Samoa-r101565/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Christmas-Island-r100323/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Cocos-Islands-r100324/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Cook-Islands-r100329/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Federated-States-of-Micronesia-r100463/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Fiji-r101238/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/French-Polynesia-r100344/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Guam-r100465/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Kiribati-r100365/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Marshall-Islands-r100377/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Nauru-r100384/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/New-Caledonia-r100387/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Norfolk-Island-r100390/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Northern-Mariana-Islands-r100481/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Palau-r100502/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Papua-New-Guinea-r100394/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Samoa-r100405/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Solomon-Islands-r100413/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Tonga-r100428/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Tuvalu-r100432/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Vanuatu-r100438/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]",
"http://tunein.com/radio/Wallis-Futuna-Islands-r100443/?other=true&page=true&filter=!p%3a!e&other=true&offset=[0-30:7]"
]
,
    "selectors": [{
        "parentSelectors": ["_root"],
        "type": "SelectorLink",
        "multiple": true,
        "id": "top_link",
        "selector": "a._tooltip",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorText",
        "multiple": false,
        "id": "station",
        "selector": "div.info h1",
        "regex": "",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorText",
        "multiple": false,
        "id": "city",
        "selector": "div.info-panel li:nth-of-type(1) span",
        "regex": "",
        "delay": ""
    }, {
        "parentSelectors": ["top_link"],
        "type": "SelectorLink",
        "multiple": false,
        "id": "email",
        "selector": "li.link-list a:nth-of-type(2)",
        "delay": ""
    }],
    "_id": "australasia"
}